/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.bysoftware.ct.service.base;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.bean.IdentifiableBean;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.model.PersistedModel;
import com.liferay.portal.service.BaseLocalServiceImpl;
import com.liferay.portal.service.PersistedModelLocalServiceRegistryUtil;
import com.liferay.portal.service.persistence.UserPersistence;

import it.bysoftware.ct.model.DestinatariDiversi;
import it.bysoftware.ct.service.DestinatariDiversiLocalService;
import it.bysoftware.ct.service.persistence.AnagraficaAssociatoOPPersistence;
import it.bysoftware.ct.service.persistence.AnagraficaPersistence;
import it.bysoftware.ct.service.persistence.ArticoliAssociatoOPPersistence;
import it.bysoftware.ct.service.persistence.ArticoliPersistence;
import it.bysoftware.ct.service.persistence.AspettoEsterioreBeniPersistence;
import it.bysoftware.ct.service.persistence.AssociatoPersistence;
import it.bysoftware.ct.service.persistence.BancheAppoggioPersistence;
import it.bysoftware.ct.service.persistence.CMRPersistence;
import it.bysoftware.ct.service.persistence.CausaleTrasportoPersistence;
import it.bysoftware.ct.service.persistence.CessioneCreditoPersistence;
import it.bysoftware.ct.service.persistence.ClientiDatiAggPersistence;
import it.bysoftware.ct.service.persistence.CuraTrasportoPersistence;
import it.bysoftware.ct.service.persistence.DescrizioniDocumentiPersistence;
import it.bysoftware.ct.service.persistence.DescrizioniVariantiPersistence;
import it.bysoftware.ct.service.persistence.DestinatariDiversiPersistence;
import it.bysoftware.ct.service.persistence.FileUploaderPersistence;
import it.bysoftware.ct.service.persistence.OrganizzazioneProduttoriPersistence;
import it.bysoftware.ct.service.persistence.PortoPersistence;
import it.bysoftware.ct.service.persistence.ProgressivoPersistence;
import it.bysoftware.ct.service.persistence.RigoDocumentoPersistence;
import it.bysoftware.ct.service.persistence.TestataDocumentoPersistence;
import it.bysoftware.ct.service.persistence.TracciabilitaGrezziPersistence;
import it.bysoftware.ct.service.persistence.TracciabilitaSchedaPersistence;
import it.bysoftware.ct.service.persistence.VettoriPersistence;
import it.bysoftware.ct.service.persistence.VociIvaPersistence;
import it.bysoftware.ct.service.persistence.WKRigoDocumentoPersistence;
import it.bysoftware.ct.service.persistence.WKTestataDocumentoPersistence;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the destinatari diversi local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link it.bysoftware.ct.service.impl.DestinatariDiversiLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see it.bysoftware.ct.service.impl.DestinatariDiversiLocalServiceImpl
 * @see it.bysoftware.ct.service.DestinatariDiversiLocalServiceUtil
 * @generated
 */
public abstract class DestinatariDiversiLocalServiceBaseImpl
	extends BaseLocalServiceImpl implements DestinatariDiversiLocalService,
		IdentifiableBean {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link it.bysoftware.ct.service.DestinatariDiversiLocalServiceUtil} to access the destinatari diversi local service.
	 */

	/**
	 * Adds the destinatari diversi to the database. Also notifies the appropriate model listeners.
	 *
	 * @param destinatariDiversi the destinatari diversi
	 * @return the destinatari diversi that was added
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public DestinatariDiversi addDestinatariDiversi(
		DestinatariDiversi destinatariDiversi) throws SystemException {
		destinatariDiversi.setNew(true);

		return destinatariDiversiPersistence.update(destinatariDiversi);
	}

	/**
	 * Creates a new destinatari diversi with the primary key. Does not add the destinatari diversi to the database.
	 *
	 * @param codiceAnagrafica the primary key for the new destinatari diversi
	 * @return the new destinatari diversi
	 */
	@Override
	public DestinatariDiversi createDestinatariDiversi(String codiceAnagrafica) {
		return destinatariDiversiPersistence.create(codiceAnagrafica);
	}

	/**
	 * Deletes the destinatari diversi with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param codiceAnagrafica the primary key of the destinatari diversi
	 * @return the destinatari diversi that was removed
	 * @throws PortalException if a destinatari diversi with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public DestinatariDiversi deleteDestinatariDiversi(String codiceAnagrafica)
		throws PortalException, SystemException {
		return destinatariDiversiPersistence.remove(codiceAnagrafica);
	}

	/**
	 * Deletes the destinatari diversi from the database. Also notifies the appropriate model listeners.
	 *
	 * @param destinatariDiversi the destinatari diversi
	 * @return the destinatari diversi that was removed
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public DestinatariDiversi deleteDestinatariDiversi(
		DestinatariDiversi destinatariDiversi) throws SystemException {
		return destinatariDiversiPersistence.remove(destinatariDiversi);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(DestinatariDiversi.class,
			clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery)
		throws SystemException {
		return destinatariDiversiPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link it.bysoftware.ct.model.impl.DestinatariDiversiModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end)
		throws SystemException {
		return destinatariDiversiPersistence.findWithDynamicQuery(dynamicQuery,
			start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link it.bysoftware.ct.model.impl.DestinatariDiversiModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator orderByComparator) throws SystemException {
		return destinatariDiversiPersistence.findWithDynamicQuery(dynamicQuery,
			start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows that match the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows that match the dynamic query
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery)
		throws SystemException {
		return destinatariDiversiPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows that match the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows that match the dynamic query
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery,
		Projection projection) throws SystemException {
		return destinatariDiversiPersistence.countWithDynamicQuery(dynamicQuery,
			projection);
	}

	@Override
	public DestinatariDiversi fetchDestinatariDiversi(String codiceAnagrafica)
		throws SystemException {
		return destinatariDiversiPersistence.fetchByPrimaryKey(codiceAnagrafica);
	}

	/**
	 * Returns the destinatari diversi with the primary key.
	 *
	 * @param codiceAnagrafica the primary key of the destinatari diversi
	 * @return the destinatari diversi
	 * @throws PortalException if a destinatari diversi with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public DestinatariDiversi getDestinatariDiversi(String codiceAnagrafica)
		throws PortalException, SystemException {
		return destinatariDiversiPersistence.findByPrimaryKey(codiceAnagrafica);
	}

	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException, SystemException {
		return destinatariDiversiPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the destinatari diversis.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link it.bysoftware.ct.model.impl.DestinatariDiversiModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param start the lower bound of the range of destinatari diversis
	 * @param end the upper bound of the range of destinatari diversis (not inclusive)
	 * @return the range of destinatari diversis
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public List<DestinatariDiversi> getDestinatariDiversis(int start, int end)
		throws SystemException {
		return destinatariDiversiPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of destinatari diversis.
	 *
	 * @return the number of destinatari diversis
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public int getDestinatariDiversisCount() throws SystemException {
		return destinatariDiversiPersistence.countAll();
	}

	/**
	 * Updates the destinatari diversi in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param destinatariDiversi the destinatari diversi
	 * @return the destinatari diversi that was updated
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public DestinatariDiversi updateDestinatariDiversi(
		DestinatariDiversi destinatariDiversi) throws SystemException {
		return destinatariDiversiPersistence.update(destinatariDiversi);
	}

	/**
	 * Returns the anagrafica local service.
	 *
	 * @return the anagrafica local service
	 */
	public it.bysoftware.ct.service.AnagraficaLocalService getAnagraficaLocalService() {
		return anagraficaLocalService;
	}

	/**
	 * Sets the anagrafica local service.
	 *
	 * @param anagraficaLocalService the anagrafica local service
	 */
	public void setAnagraficaLocalService(
		it.bysoftware.ct.service.AnagraficaLocalService anagraficaLocalService) {
		this.anagraficaLocalService = anagraficaLocalService;
	}

	/**
	 * Returns the anagrafica remote service.
	 *
	 * @return the anagrafica remote service
	 */
	public it.bysoftware.ct.service.AnagraficaService getAnagraficaService() {
		return anagraficaService;
	}

	/**
	 * Sets the anagrafica remote service.
	 *
	 * @param anagraficaService the anagrafica remote service
	 */
	public void setAnagraficaService(
		it.bysoftware.ct.service.AnagraficaService anagraficaService) {
		this.anagraficaService = anagraficaService;
	}

	/**
	 * Returns the anagrafica persistence.
	 *
	 * @return the anagrafica persistence
	 */
	public AnagraficaPersistence getAnagraficaPersistence() {
		return anagraficaPersistence;
	}

	/**
	 * Sets the anagrafica persistence.
	 *
	 * @param anagraficaPersistence the anagrafica persistence
	 */
	public void setAnagraficaPersistence(
		AnagraficaPersistence anagraficaPersistence) {
		this.anagraficaPersistence = anagraficaPersistence;
	}

	/**
	 * Returns the anagrafica associato o p local service.
	 *
	 * @return the anagrafica associato o p local service
	 */
	public it.bysoftware.ct.service.AnagraficaAssociatoOPLocalService getAnagraficaAssociatoOPLocalService() {
		return anagraficaAssociatoOPLocalService;
	}

	/**
	 * Sets the anagrafica associato o p local service.
	 *
	 * @param anagraficaAssociatoOPLocalService the anagrafica associato o p local service
	 */
	public void setAnagraficaAssociatoOPLocalService(
		it.bysoftware.ct.service.AnagraficaAssociatoOPLocalService anagraficaAssociatoOPLocalService) {
		this.anagraficaAssociatoOPLocalService = anagraficaAssociatoOPLocalService;
	}

	/**
	 * Returns the anagrafica associato o p remote service.
	 *
	 * @return the anagrafica associato o p remote service
	 */
	public it.bysoftware.ct.service.AnagraficaAssociatoOPService getAnagraficaAssociatoOPService() {
		return anagraficaAssociatoOPService;
	}

	/**
	 * Sets the anagrafica associato o p remote service.
	 *
	 * @param anagraficaAssociatoOPService the anagrafica associato o p remote service
	 */
	public void setAnagraficaAssociatoOPService(
		it.bysoftware.ct.service.AnagraficaAssociatoOPService anagraficaAssociatoOPService) {
		this.anagraficaAssociatoOPService = anagraficaAssociatoOPService;
	}

	/**
	 * Returns the anagrafica associato o p persistence.
	 *
	 * @return the anagrafica associato o p persistence
	 */
	public AnagraficaAssociatoOPPersistence getAnagraficaAssociatoOPPersistence() {
		return anagraficaAssociatoOPPersistence;
	}

	/**
	 * Sets the anagrafica associato o p persistence.
	 *
	 * @param anagraficaAssociatoOPPersistence the anagrafica associato o p persistence
	 */
	public void setAnagraficaAssociatoOPPersistence(
		AnagraficaAssociatoOPPersistence anagraficaAssociatoOPPersistence) {
		this.anagraficaAssociatoOPPersistence = anagraficaAssociatoOPPersistence;
	}

	/**
	 * Returns the articoli local service.
	 *
	 * @return the articoli local service
	 */
	public it.bysoftware.ct.service.ArticoliLocalService getArticoliLocalService() {
		return articoliLocalService;
	}

	/**
	 * Sets the articoli local service.
	 *
	 * @param articoliLocalService the articoli local service
	 */
	public void setArticoliLocalService(
		it.bysoftware.ct.service.ArticoliLocalService articoliLocalService) {
		this.articoliLocalService = articoliLocalService;
	}

	/**
	 * Returns the articoli remote service.
	 *
	 * @return the articoli remote service
	 */
	public it.bysoftware.ct.service.ArticoliService getArticoliService() {
		return articoliService;
	}

	/**
	 * Sets the articoli remote service.
	 *
	 * @param articoliService the articoli remote service
	 */
	public void setArticoliService(
		it.bysoftware.ct.service.ArticoliService articoliService) {
		this.articoliService = articoliService;
	}

	/**
	 * Returns the articoli persistence.
	 *
	 * @return the articoli persistence
	 */
	public ArticoliPersistence getArticoliPersistence() {
		return articoliPersistence;
	}

	/**
	 * Sets the articoli persistence.
	 *
	 * @param articoliPersistence the articoli persistence
	 */
	public void setArticoliPersistence(ArticoliPersistence articoliPersistence) {
		this.articoliPersistence = articoliPersistence;
	}

	/**
	 * Returns the articoli associato o p local service.
	 *
	 * @return the articoli associato o p local service
	 */
	public it.bysoftware.ct.service.ArticoliAssociatoOPLocalService getArticoliAssociatoOPLocalService() {
		return articoliAssociatoOPLocalService;
	}

	/**
	 * Sets the articoli associato o p local service.
	 *
	 * @param articoliAssociatoOPLocalService the articoli associato o p local service
	 */
	public void setArticoliAssociatoOPLocalService(
		it.bysoftware.ct.service.ArticoliAssociatoOPLocalService articoliAssociatoOPLocalService) {
		this.articoliAssociatoOPLocalService = articoliAssociatoOPLocalService;
	}

	/**
	 * Returns the articoli associato o p remote service.
	 *
	 * @return the articoli associato o p remote service
	 */
	public it.bysoftware.ct.service.ArticoliAssociatoOPService getArticoliAssociatoOPService() {
		return articoliAssociatoOPService;
	}

	/**
	 * Sets the articoli associato o p remote service.
	 *
	 * @param articoliAssociatoOPService the articoli associato o p remote service
	 */
	public void setArticoliAssociatoOPService(
		it.bysoftware.ct.service.ArticoliAssociatoOPService articoliAssociatoOPService) {
		this.articoliAssociatoOPService = articoliAssociatoOPService;
	}

	/**
	 * Returns the articoli associato o p persistence.
	 *
	 * @return the articoli associato o p persistence
	 */
	public ArticoliAssociatoOPPersistence getArticoliAssociatoOPPersistence() {
		return articoliAssociatoOPPersistence;
	}

	/**
	 * Sets the articoli associato o p persistence.
	 *
	 * @param articoliAssociatoOPPersistence the articoli associato o p persistence
	 */
	public void setArticoliAssociatoOPPersistence(
		ArticoliAssociatoOPPersistence articoliAssociatoOPPersistence) {
		this.articoliAssociatoOPPersistence = articoliAssociatoOPPersistence;
	}

	/**
	 * Returns the aspetto esteriore beni local service.
	 *
	 * @return the aspetto esteriore beni local service
	 */
	public it.bysoftware.ct.service.AspettoEsterioreBeniLocalService getAspettoEsterioreBeniLocalService() {
		return aspettoEsterioreBeniLocalService;
	}

	/**
	 * Sets the aspetto esteriore beni local service.
	 *
	 * @param aspettoEsterioreBeniLocalService the aspetto esteriore beni local service
	 */
	public void setAspettoEsterioreBeniLocalService(
		it.bysoftware.ct.service.AspettoEsterioreBeniLocalService aspettoEsterioreBeniLocalService) {
		this.aspettoEsterioreBeniLocalService = aspettoEsterioreBeniLocalService;
	}

	/**
	 * Returns the aspetto esteriore beni remote service.
	 *
	 * @return the aspetto esteriore beni remote service
	 */
	public it.bysoftware.ct.service.AspettoEsterioreBeniService getAspettoEsterioreBeniService() {
		return aspettoEsterioreBeniService;
	}

	/**
	 * Sets the aspetto esteriore beni remote service.
	 *
	 * @param aspettoEsterioreBeniService the aspetto esteriore beni remote service
	 */
	public void setAspettoEsterioreBeniService(
		it.bysoftware.ct.service.AspettoEsterioreBeniService aspettoEsterioreBeniService) {
		this.aspettoEsterioreBeniService = aspettoEsterioreBeniService;
	}

	/**
	 * Returns the aspetto esteriore beni persistence.
	 *
	 * @return the aspetto esteriore beni persistence
	 */
	public AspettoEsterioreBeniPersistence getAspettoEsterioreBeniPersistence() {
		return aspettoEsterioreBeniPersistence;
	}

	/**
	 * Sets the aspetto esteriore beni persistence.
	 *
	 * @param aspettoEsterioreBeniPersistence the aspetto esteriore beni persistence
	 */
	public void setAspettoEsterioreBeniPersistence(
		AspettoEsterioreBeniPersistence aspettoEsterioreBeniPersistence) {
		this.aspettoEsterioreBeniPersistence = aspettoEsterioreBeniPersistence;
	}

	/**
	 * Returns the associato local service.
	 *
	 * @return the associato local service
	 */
	public it.bysoftware.ct.service.AssociatoLocalService getAssociatoLocalService() {
		return associatoLocalService;
	}

	/**
	 * Sets the associato local service.
	 *
	 * @param associatoLocalService the associato local service
	 */
	public void setAssociatoLocalService(
		it.bysoftware.ct.service.AssociatoLocalService associatoLocalService) {
		this.associatoLocalService = associatoLocalService;
	}

	/**
	 * Returns the associato remote service.
	 *
	 * @return the associato remote service
	 */
	public it.bysoftware.ct.service.AssociatoService getAssociatoService() {
		return associatoService;
	}

	/**
	 * Sets the associato remote service.
	 *
	 * @param associatoService the associato remote service
	 */
	public void setAssociatoService(
		it.bysoftware.ct.service.AssociatoService associatoService) {
		this.associatoService = associatoService;
	}

	/**
	 * Returns the associato persistence.
	 *
	 * @return the associato persistence
	 */
	public AssociatoPersistence getAssociatoPersistence() {
		return associatoPersistence;
	}

	/**
	 * Sets the associato persistence.
	 *
	 * @param associatoPersistence the associato persistence
	 */
	public void setAssociatoPersistence(
		AssociatoPersistence associatoPersistence) {
		this.associatoPersistence = associatoPersistence;
	}

	/**
	 * Returns the banche appoggio local service.
	 *
	 * @return the banche appoggio local service
	 */
	public it.bysoftware.ct.service.BancheAppoggioLocalService getBancheAppoggioLocalService() {
		return bancheAppoggioLocalService;
	}

	/**
	 * Sets the banche appoggio local service.
	 *
	 * @param bancheAppoggioLocalService the banche appoggio local service
	 */
	public void setBancheAppoggioLocalService(
		it.bysoftware.ct.service.BancheAppoggioLocalService bancheAppoggioLocalService) {
		this.bancheAppoggioLocalService = bancheAppoggioLocalService;
	}

	/**
	 * Returns the banche appoggio remote service.
	 *
	 * @return the banche appoggio remote service
	 */
	public it.bysoftware.ct.service.BancheAppoggioService getBancheAppoggioService() {
		return bancheAppoggioService;
	}

	/**
	 * Sets the banche appoggio remote service.
	 *
	 * @param bancheAppoggioService the banche appoggio remote service
	 */
	public void setBancheAppoggioService(
		it.bysoftware.ct.service.BancheAppoggioService bancheAppoggioService) {
		this.bancheAppoggioService = bancheAppoggioService;
	}

	/**
	 * Returns the banche appoggio persistence.
	 *
	 * @return the banche appoggio persistence
	 */
	public BancheAppoggioPersistence getBancheAppoggioPersistence() {
		return bancheAppoggioPersistence;
	}

	/**
	 * Sets the banche appoggio persistence.
	 *
	 * @param bancheAppoggioPersistence the banche appoggio persistence
	 */
	public void setBancheAppoggioPersistence(
		BancheAppoggioPersistence bancheAppoggioPersistence) {
		this.bancheAppoggioPersistence = bancheAppoggioPersistence;
	}

	/**
	 * Returns the causale trasporto local service.
	 *
	 * @return the causale trasporto local service
	 */
	public it.bysoftware.ct.service.CausaleTrasportoLocalService getCausaleTrasportoLocalService() {
		return causaleTrasportoLocalService;
	}

	/**
	 * Sets the causale trasporto local service.
	 *
	 * @param causaleTrasportoLocalService the causale trasporto local service
	 */
	public void setCausaleTrasportoLocalService(
		it.bysoftware.ct.service.CausaleTrasportoLocalService causaleTrasportoLocalService) {
		this.causaleTrasportoLocalService = causaleTrasportoLocalService;
	}

	/**
	 * Returns the causale trasporto remote service.
	 *
	 * @return the causale trasporto remote service
	 */
	public it.bysoftware.ct.service.CausaleTrasportoService getCausaleTrasportoService() {
		return causaleTrasportoService;
	}

	/**
	 * Sets the causale trasporto remote service.
	 *
	 * @param causaleTrasportoService the causale trasporto remote service
	 */
	public void setCausaleTrasportoService(
		it.bysoftware.ct.service.CausaleTrasportoService causaleTrasportoService) {
		this.causaleTrasportoService = causaleTrasportoService;
	}

	/**
	 * Returns the causale trasporto persistence.
	 *
	 * @return the causale trasporto persistence
	 */
	public CausaleTrasportoPersistence getCausaleTrasportoPersistence() {
		return causaleTrasportoPersistence;
	}

	/**
	 * Sets the causale trasporto persistence.
	 *
	 * @param causaleTrasportoPersistence the causale trasporto persistence
	 */
	public void setCausaleTrasportoPersistence(
		CausaleTrasportoPersistence causaleTrasportoPersistence) {
		this.causaleTrasportoPersistence = causaleTrasportoPersistence;
	}

	/**
	 * Returns the cessione credito local service.
	 *
	 * @return the cessione credito local service
	 */
	public it.bysoftware.ct.service.CessioneCreditoLocalService getCessioneCreditoLocalService() {
		return cessioneCreditoLocalService;
	}

	/**
	 * Sets the cessione credito local service.
	 *
	 * @param cessioneCreditoLocalService the cessione credito local service
	 */
	public void setCessioneCreditoLocalService(
		it.bysoftware.ct.service.CessioneCreditoLocalService cessioneCreditoLocalService) {
		this.cessioneCreditoLocalService = cessioneCreditoLocalService;
	}

	/**
	 * Returns the cessione credito remote service.
	 *
	 * @return the cessione credito remote service
	 */
	public it.bysoftware.ct.service.CessioneCreditoService getCessioneCreditoService() {
		return cessioneCreditoService;
	}

	/**
	 * Sets the cessione credito remote service.
	 *
	 * @param cessioneCreditoService the cessione credito remote service
	 */
	public void setCessioneCreditoService(
		it.bysoftware.ct.service.CessioneCreditoService cessioneCreditoService) {
		this.cessioneCreditoService = cessioneCreditoService;
	}

	/**
	 * Returns the cessione credito persistence.
	 *
	 * @return the cessione credito persistence
	 */
	public CessioneCreditoPersistence getCessioneCreditoPersistence() {
		return cessioneCreditoPersistence;
	}

	/**
	 * Sets the cessione credito persistence.
	 *
	 * @param cessioneCreditoPersistence the cessione credito persistence
	 */
	public void setCessioneCreditoPersistence(
		CessioneCreditoPersistence cessioneCreditoPersistence) {
		this.cessioneCreditoPersistence = cessioneCreditoPersistence;
	}

	/**
	 * Returns the clienti dati agg local service.
	 *
	 * @return the clienti dati agg local service
	 */
	public it.bysoftware.ct.service.ClientiDatiAggLocalService getClientiDatiAggLocalService() {
		return clientiDatiAggLocalService;
	}

	/**
	 * Sets the clienti dati agg local service.
	 *
	 * @param clientiDatiAggLocalService the clienti dati agg local service
	 */
	public void setClientiDatiAggLocalService(
		it.bysoftware.ct.service.ClientiDatiAggLocalService clientiDatiAggLocalService) {
		this.clientiDatiAggLocalService = clientiDatiAggLocalService;
	}

	/**
	 * Returns the clienti dati agg remote service.
	 *
	 * @return the clienti dati agg remote service
	 */
	public it.bysoftware.ct.service.ClientiDatiAggService getClientiDatiAggService() {
		return clientiDatiAggService;
	}

	/**
	 * Sets the clienti dati agg remote service.
	 *
	 * @param clientiDatiAggService the clienti dati agg remote service
	 */
	public void setClientiDatiAggService(
		it.bysoftware.ct.service.ClientiDatiAggService clientiDatiAggService) {
		this.clientiDatiAggService = clientiDatiAggService;
	}

	/**
	 * Returns the clienti dati agg persistence.
	 *
	 * @return the clienti dati agg persistence
	 */
	public ClientiDatiAggPersistence getClientiDatiAggPersistence() {
		return clientiDatiAggPersistence;
	}

	/**
	 * Sets the clienti dati agg persistence.
	 *
	 * @param clientiDatiAggPersistence the clienti dati agg persistence
	 */
	public void setClientiDatiAggPersistence(
		ClientiDatiAggPersistence clientiDatiAggPersistence) {
		this.clientiDatiAggPersistence = clientiDatiAggPersistence;
	}

	/**
	 * Returns the c m r local service.
	 *
	 * @return the c m r local service
	 */
	public it.bysoftware.ct.service.CMRLocalService getCMRLocalService() {
		return cmrLocalService;
	}

	/**
	 * Sets the c m r local service.
	 *
	 * @param cmrLocalService the c m r local service
	 */
	public void setCMRLocalService(
		it.bysoftware.ct.service.CMRLocalService cmrLocalService) {
		this.cmrLocalService = cmrLocalService;
	}

	/**
	 * Returns the c m r remote service.
	 *
	 * @return the c m r remote service
	 */
	public it.bysoftware.ct.service.CMRService getCMRService() {
		return cmrService;
	}

	/**
	 * Sets the c m r remote service.
	 *
	 * @param cmrService the c m r remote service
	 */
	public void setCMRService(it.bysoftware.ct.service.CMRService cmrService) {
		this.cmrService = cmrService;
	}

	/**
	 * Returns the c m r persistence.
	 *
	 * @return the c m r persistence
	 */
	public CMRPersistence getCMRPersistence() {
		return cmrPersistence;
	}

	/**
	 * Sets the c m r persistence.
	 *
	 * @param cmrPersistence the c m r persistence
	 */
	public void setCMRPersistence(CMRPersistence cmrPersistence) {
		this.cmrPersistence = cmrPersistence;
	}

	/**
	 * Returns the cura trasporto local service.
	 *
	 * @return the cura trasporto local service
	 */
	public it.bysoftware.ct.service.CuraTrasportoLocalService getCuraTrasportoLocalService() {
		return curaTrasportoLocalService;
	}

	/**
	 * Sets the cura trasporto local service.
	 *
	 * @param curaTrasportoLocalService the cura trasporto local service
	 */
	public void setCuraTrasportoLocalService(
		it.bysoftware.ct.service.CuraTrasportoLocalService curaTrasportoLocalService) {
		this.curaTrasportoLocalService = curaTrasportoLocalService;
	}

	/**
	 * Returns the cura trasporto remote service.
	 *
	 * @return the cura trasporto remote service
	 */
	public it.bysoftware.ct.service.CuraTrasportoService getCuraTrasportoService() {
		return curaTrasportoService;
	}

	/**
	 * Sets the cura trasporto remote service.
	 *
	 * @param curaTrasportoService the cura trasporto remote service
	 */
	public void setCuraTrasportoService(
		it.bysoftware.ct.service.CuraTrasportoService curaTrasportoService) {
		this.curaTrasportoService = curaTrasportoService;
	}

	/**
	 * Returns the cura trasporto persistence.
	 *
	 * @return the cura trasporto persistence
	 */
	public CuraTrasportoPersistence getCuraTrasportoPersistence() {
		return curaTrasportoPersistence;
	}

	/**
	 * Sets the cura trasporto persistence.
	 *
	 * @param curaTrasportoPersistence the cura trasporto persistence
	 */
	public void setCuraTrasportoPersistence(
		CuraTrasportoPersistence curaTrasportoPersistence) {
		this.curaTrasportoPersistence = curaTrasportoPersistence;
	}

	/**
	 * Returns the descrizioni documenti local service.
	 *
	 * @return the descrizioni documenti local service
	 */
	public it.bysoftware.ct.service.DescrizioniDocumentiLocalService getDescrizioniDocumentiLocalService() {
		return descrizioniDocumentiLocalService;
	}

	/**
	 * Sets the descrizioni documenti local service.
	 *
	 * @param descrizioniDocumentiLocalService the descrizioni documenti local service
	 */
	public void setDescrizioniDocumentiLocalService(
		it.bysoftware.ct.service.DescrizioniDocumentiLocalService descrizioniDocumentiLocalService) {
		this.descrizioniDocumentiLocalService = descrizioniDocumentiLocalService;
	}

	/**
	 * Returns the descrizioni documenti remote service.
	 *
	 * @return the descrizioni documenti remote service
	 */
	public it.bysoftware.ct.service.DescrizioniDocumentiService getDescrizioniDocumentiService() {
		return descrizioniDocumentiService;
	}

	/**
	 * Sets the descrizioni documenti remote service.
	 *
	 * @param descrizioniDocumentiService the descrizioni documenti remote service
	 */
	public void setDescrizioniDocumentiService(
		it.bysoftware.ct.service.DescrizioniDocumentiService descrizioniDocumentiService) {
		this.descrizioniDocumentiService = descrizioniDocumentiService;
	}

	/**
	 * Returns the descrizioni documenti persistence.
	 *
	 * @return the descrizioni documenti persistence
	 */
	public DescrizioniDocumentiPersistence getDescrizioniDocumentiPersistence() {
		return descrizioniDocumentiPersistence;
	}

	/**
	 * Sets the descrizioni documenti persistence.
	 *
	 * @param descrizioniDocumentiPersistence the descrizioni documenti persistence
	 */
	public void setDescrizioniDocumentiPersistence(
		DescrizioniDocumentiPersistence descrizioniDocumentiPersistence) {
		this.descrizioniDocumentiPersistence = descrizioniDocumentiPersistence;
	}

	/**
	 * Returns the descrizioni varianti local service.
	 *
	 * @return the descrizioni varianti local service
	 */
	public it.bysoftware.ct.service.DescrizioniVariantiLocalService getDescrizioniVariantiLocalService() {
		return descrizioniVariantiLocalService;
	}

	/**
	 * Sets the descrizioni varianti local service.
	 *
	 * @param descrizioniVariantiLocalService the descrizioni varianti local service
	 */
	public void setDescrizioniVariantiLocalService(
		it.bysoftware.ct.service.DescrizioniVariantiLocalService descrizioniVariantiLocalService) {
		this.descrizioniVariantiLocalService = descrizioniVariantiLocalService;
	}

	/**
	 * Returns the descrizioni varianti remote service.
	 *
	 * @return the descrizioni varianti remote service
	 */
	public it.bysoftware.ct.service.DescrizioniVariantiService getDescrizioniVariantiService() {
		return descrizioniVariantiService;
	}

	/**
	 * Sets the descrizioni varianti remote service.
	 *
	 * @param descrizioniVariantiService the descrizioni varianti remote service
	 */
	public void setDescrizioniVariantiService(
		it.bysoftware.ct.service.DescrizioniVariantiService descrizioniVariantiService) {
		this.descrizioniVariantiService = descrizioniVariantiService;
	}

	/**
	 * Returns the descrizioni varianti persistence.
	 *
	 * @return the descrizioni varianti persistence
	 */
	public DescrizioniVariantiPersistence getDescrizioniVariantiPersistence() {
		return descrizioniVariantiPersistence;
	}

	/**
	 * Sets the descrizioni varianti persistence.
	 *
	 * @param descrizioniVariantiPersistence the descrizioni varianti persistence
	 */
	public void setDescrizioniVariantiPersistence(
		DescrizioniVariantiPersistence descrizioniVariantiPersistence) {
		this.descrizioniVariantiPersistence = descrizioniVariantiPersistence;
	}

	/**
	 * Returns the destinatari diversi local service.
	 *
	 * @return the destinatari diversi local service
	 */
	public it.bysoftware.ct.service.DestinatariDiversiLocalService getDestinatariDiversiLocalService() {
		return destinatariDiversiLocalService;
	}

	/**
	 * Sets the destinatari diversi local service.
	 *
	 * @param destinatariDiversiLocalService the destinatari diversi local service
	 */
	public void setDestinatariDiversiLocalService(
		it.bysoftware.ct.service.DestinatariDiversiLocalService destinatariDiversiLocalService) {
		this.destinatariDiversiLocalService = destinatariDiversiLocalService;
	}

	/**
	 * Returns the destinatari diversi remote service.
	 *
	 * @return the destinatari diversi remote service
	 */
	public it.bysoftware.ct.service.DestinatariDiversiService getDestinatariDiversiService() {
		return destinatariDiversiService;
	}

	/**
	 * Sets the destinatari diversi remote service.
	 *
	 * @param destinatariDiversiService the destinatari diversi remote service
	 */
	public void setDestinatariDiversiService(
		it.bysoftware.ct.service.DestinatariDiversiService destinatariDiversiService) {
		this.destinatariDiversiService = destinatariDiversiService;
	}

	/**
	 * Returns the destinatari diversi persistence.
	 *
	 * @return the destinatari diversi persistence
	 */
	public DestinatariDiversiPersistence getDestinatariDiversiPersistence() {
		return destinatariDiversiPersistence;
	}

	/**
	 * Sets the destinatari diversi persistence.
	 *
	 * @param destinatariDiversiPersistence the destinatari diversi persistence
	 */
	public void setDestinatariDiversiPersistence(
		DestinatariDiversiPersistence destinatariDiversiPersistence) {
		this.destinatariDiversiPersistence = destinatariDiversiPersistence;
	}

	/**
	 * Returns the file uploader local service.
	 *
	 * @return the file uploader local service
	 */
	public it.bysoftware.ct.service.FileUploaderLocalService getFileUploaderLocalService() {
		return fileUploaderLocalService;
	}

	/**
	 * Sets the file uploader local service.
	 *
	 * @param fileUploaderLocalService the file uploader local service
	 */
	public void setFileUploaderLocalService(
		it.bysoftware.ct.service.FileUploaderLocalService fileUploaderLocalService) {
		this.fileUploaderLocalService = fileUploaderLocalService;
	}

	/**
	 * Returns the file uploader remote service.
	 *
	 * @return the file uploader remote service
	 */
	public it.bysoftware.ct.service.FileUploaderService getFileUploaderService() {
		return fileUploaderService;
	}

	/**
	 * Sets the file uploader remote service.
	 *
	 * @param fileUploaderService the file uploader remote service
	 */
	public void setFileUploaderService(
		it.bysoftware.ct.service.FileUploaderService fileUploaderService) {
		this.fileUploaderService = fileUploaderService;
	}

	/**
	 * Returns the file uploader persistence.
	 *
	 * @return the file uploader persistence
	 */
	public FileUploaderPersistence getFileUploaderPersistence() {
		return fileUploaderPersistence;
	}

	/**
	 * Sets the file uploader persistence.
	 *
	 * @param fileUploaderPersistence the file uploader persistence
	 */
	public void setFileUploaderPersistence(
		FileUploaderPersistence fileUploaderPersistence) {
		this.fileUploaderPersistence = fileUploaderPersistence;
	}

	/**
	 * Returns the organizzazione produttori local service.
	 *
	 * @return the organizzazione produttori local service
	 */
	public it.bysoftware.ct.service.OrganizzazioneProduttoriLocalService getOrganizzazioneProduttoriLocalService() {
		return organizzazioneProduttoriLocalService;
	}

	/**
	 * Sets the organizzazione produttori local service.
	 *
	 * @param organizzazioneProduttoriLocalService the organizzazione produttori local service
	 */
	public void setOrganizzazioneProduttoriLocalService(
		it.bysoftware.ct.service.OrganizzazioneProduttoriLocalService organizzazioneProduttoriLocalService) {
		this.organizzazioneProduttoriLocalService = organizzazioneProduttoriLocalService;
	}

	/**
	 * Returns the organizzazione produttori remote service.
	 *
	 * @return the organizzazione produttori remote service
	 */
	public it.bysoftware.ct.service.OrganizzazioneProduttoriService getOrganizzazioneProduttoriService() {
		return organizzazioneProduttoriService;
	}

	/**
	 * Sets the organizzazione produttori remote service.
	 *
	 * @param organizzazioneProduttoriService the organizzazione produttori remote service
	 */
	public void setOrganizzazioneProduttoriService(
		it.bysoftware.ct.service.OrganizzazioneProduttoriService organizzazioneProduttoriService) {
		this.organizzazioneProduttoriService = organizzazioneProduttoriService;
	}

	/**
	 * Returns the organizzazione produttori persistence.
	 *
	 * @return the organizzazione produttori persistence
	 */
	public OrganizzazioneProduttoriPersistence getOrganizzazioneProduttoriPersistence() {
		return organizzazioneProduttoriPersistence;
	}

	/**
	 * Sets the organizzazione produttori persistence.
	 *
	 * @param organizzazioneProduttoriPersistence the organizzazione produttori persistence
	 */
	public void setOrganizzazioneProduttoriPersistence(
		OrganizzazioneProduttoriPersistence organizzazioneProduttoriPersistence) {
		this.organizzazioneProduttoriPersistence = organizzazioneProduttoriPersistence;
	}

	/**
	 * Returns the porto local service.
	 *
	 * @return the porto local service
	 */
	public it.bysoftware.ct.service.PortoLocalService getPortoLocalService() {
		return portoLocalService;
	}

	/**
	 * Sets the porto local service.
	 *
	 * @param portoLocalService the porto local service
	 */
	public void setPortoLocalService(
		it.bysoftware.ct.service.PortoLocalService portoLocalService) {
		this.portoLocalService = portoLocalService;
	}

	/**
	 * Returns the porto remote service.
	 *
	 * @return the porto remote service
	 */
	public it.bysoftware.ct.service.PortoService getPortoService() {
		return portoService;
	}

	/**
	 * Sets the porto remote service.
	 *
	 * @param portoService the porto remote service
	 */
	public void setPortoService(
		it.bysoftware.ct.service.PortoService portoService) {
		this.portoService = portoService;
	}

	/**
	 * Returns the porto persistence.
	 *
	 * @return the porto persistence
	 */
	public PortoPersistence getPortoPersistence() {
		return portoPersistence;
	}

	/**
	 * Sets the porto persistence.
	 *
	 * @param portoPersistence the porto persistence
	 */
	public void setPortoPersistence(PortoPersistence portoPersistence) {
		this.portoPersistence = portoPersistence;
	}

	/**
	 * Returns the progressivo local service.
	 *
	 * @return the progressivo local service
	 */
	public it.bysoftware.ct.service.ProgressivoLocalService getProgressivoLocalService() {
		return progressivoLocalService;
	}

	/**
	 * Sets the progressivo local service.
	 *
	 * @param progressivoLocalService the progressivo local service
	 */
	public void setProgressivoLocalService(
		it.bysoftware.ct.service.ProgressivoLocalService progressivoLocalService) {
		this.progressivoLocalService = progressivoLocalService;
	}

	/**
	 * Returns the progressivo remote service.
	 *
	 * @return the progressivo remote service
	 */
	public it.bysoftware.ct.service.ProgressivoService getProgressivoService() {
		return progressivoService;
	}

	/**
	 * Sets the progressivo remote service.
	 *
	 * @param progressivoService the progressivo remote service
	 */
	public void setProgressivoService(
		it.bysoftware.ct.service.ProgressivoService progressivoService) {
		this.progressivoService = progressivoService;
	}

	/**
	 * Returns the progressivo persistence.
	 *
	 * @return the progressivo persistence
	 */
	public ProgressivoPersistence getProgressivoPersistence() {
		return progressivoPersistence;
	}

	/**
	 * Sets the progressivo persistence.
	 *
	 * @param progressivoPersistence the progressivo persistence
	 */
	public void setProgressivoPersistence(
		ProgressivoPersistence progressivoPersistence) {
		this.progressivoPersistence = progressivoPersistence;
	}

	/**
	 * Returns the rigo documento local service.
	 *
	 * @return the rigo documento local service
	 */
	public it.bysoftware.ct.service.RigoDocumentoLocalService getRigoDocumentoLocalService() {
		return rigoDocumentoLocalService;
	}

	/**
	 * Sets the rigo documento local service.
	 *
	 * @param rigoDocumentoLocalService the rigo documento local service
	 */
	public void setRigoDocumentoLocalService(
		it.bysoftware.ct.service.RigoDocumentoLocalService rigoDocumentoLocalService) {
		this.rigoDocumentoLocalService = rigoDocumentoLocalService;
	}

	/**
	 * Returns the rigo documento remote service.
	 *
	 * @return the rigo documento remote service
	 */
	public it.bysoftware.ct.service.RigoDocumentoService getRigoDocumentoService() {
		return rigoDocumentoService;
	}

	/**
	 * Sets the rigo documento remote service.
	 *
	 * @param rigoDocumentoService the rigo documento remote service
	 */
	public void setRigoDocumentoService(
		it.bysoftware.ct.service.RigoDocumentoService rigoDocumentoService) {
		this.rigoDocumentoService = rigoDocumentoService;
	}

	/**
	 * Returns the rigo documento persistence.
	 *
	 * @return the rigo documento persistence
	 */
	public RigoDocumentoPersistence getRigoDocumentoPersistence() {
		return rigoDocumentoPersistence;
	}

	/**
	 * Sets the rigo documento persistence.
	 *
	 * @param rigoDocumentoPersistence the rigo documento persistence
	 */
	public void setRigoDocumentoPersistence(
		RigoDocumentoPersistence rigoDocumentoPersistence) {
		this.rigoDocumentoPersistence = rigoDocumentoPersistence;
	}

	/**
	 * Returns the testata documento local service.
	 *
	 * @return the testata documento local service
	 */
	public it.bysoftware.ct.service.TestataDocumentoLocalService getTestataDocumentoLocalService() {
		return testataDocumentoLocalService;
	}

	/**
	 * Sets the testata documento local service.
	 *
	 * @param testataDocumentoLocalService the testata documento local service
	 */
	public void setTestataDocumentoLocalService(
		it.bysoftware.ct.service.TestataDocumentoLocalService testataDocumentoLocalService) {
		this.testataDocumentoLocalService = testataDocumentoLocalService;
	}

	/**
	 * Returns the testata documento remote service.
	 *
	 * @return the testata documento remote service
	 */
	public it.bysoftware.ct.service.TestataDocumentoService getTestataDocumentoService() {
		return testataDocumentoService;
	}

	/**
	 * Sets the testata documento remote service.
	 *
	 * @param testataDocumentoService the testata documento remote service
	 */
	public void setTestataDocumentoService(
		it.bysoftware.ct.service.TestataDocumentoService testataDocumentoService) {
		this.testataDocumentoService = testataDocumentoService;
	}

	/**
	 * Returns the testata documento persistence.
	 *
	 * @return the testata documento persistence
	 */
	public TestataDocumentoPersistence getTestataDocumentoPersistence() {
		return testataDocumentoPersistence;
	}

	/**
	 * Sets the testata documento persistence.
	 *
	 * @param testataDocumentoPersistence the testata documento persistence
	 */
	public void setTestataDocumentoPersistence(
		TestataDocumentoPersistence testataDocumentoPersistence) {
		this.testataDocumentoPersistence = testataDocumentoPersistence;
	}

	/**
	 * Returns the tracciabilita grezzi local service.
	 *
	 * @return the tracciabilita grezzi local service
	 */
	public it.bysoftware.ct.service.TracciabilitaGrezziLocalService getTracciabilitaGrezziLocalService() {
		return tracciabilitaGrezziLocalService;
	}

	/**
	 * Sets the tracciabilita grezzi local service.
	 *
	 * @param tracciabilitaGrezziLocalService the tracciabilita grezzi local service
	 */
	public void setTracciabilitaGrezziLocalService(
		it.bysoftware.ct.service.TracciabilitaGrezziLocalService tracciabilitaGrezziLocalService) {
		this.tracciabilitaGrezziLocalService = tracciabilitaGrezziLocalService;
	}

	/**
	 * Returns the tracciabilita grezzi remote service.
	 *
	 * @return the tracciabilita grezzi remote service
	 */
	public it.bysoftware.ct.service.TracciabilitaGrezziService getTracciabilitaGrezziService() {
		return tracciabilitaGrezziService;
	}

	/**
	 * Sets the tracciabilita grezzi remote service.
	 *
	 * @param tracciabilitaGrezziService the tracciabilita grezzi remote service
	 */
	public void setTracciabilitaGrezziService(
		it.bysoftware.ct.service.TracciabilitaGrezziService tracciabilitaGrezziService) {
		this.tracciabilitaGrezziService = tracciabilitaGrezziService;
	}

	/**
	 * Returns the tracciabilita grezzi persistence.
	 *
	 * @return the tracciabilita grezzi persistence
	 */
	public TracciabilitaGrezziPersistence getTracciabilitaGrezziPersistence() {
		return tracciabilitaGrezziPersistence;
	}

	/**
	 * Sets the tracciabilita grezzi persistence.
	 *
	 * @param tracciabilitaGrezziPersistence the tracciabilita grezzi persistence
	 */
	public void setTracciabilitaGrezziPersistence(
		TracciabilitaGrezziPersistence tracciabilitaGrezziPersistence) {
		this.tracciabilitaGrezziPersistence = tracciabilitaGrezziPersistence;
	}

	/**
	 * Returns the tracciabilita scheda local service.
	 *
	 * @return the tracciabilita scheda local service
	 */
	public it.bysoftware.ct.service.TracciabilitaSchedaLocalService getTracciabilitaSchedaLocalService() {
		return tracciabilitaSchedaLocalService;
	}

	/**
	 * Sets the tracciabilita scheda local service.
	 *
	 * @param tracciabilitaSchedaLocalService the tracciabilita scheda local service
	 */
	public void setTracciabilitaSchedaLocalService(
		it.bysoftware.ct.service.TracciabilitaSchedaLocalService tracciabilitaSchedaLocalService) {
		this.tracciabilitaSchedaLocalService = tracciabilitaSchedaLocalService;
	}

	/**
	 * Returns the tracciabilita scheda remote service.
	 *
	 * @return the tracciabilita scheda remote service
	 */
	public it.bysoftware.ct.service.TracciabilitaSchedaService getTracciabilitaSchedaService() {
		return tracciabilitaSchedaService;
	}

	/**
	 * Sets the tracciabilita scheda remote service.
	 *
	 * @param tracciabilitaSchedaService the tracciabilita scheda remote service
	 */
	public void setTracciabilitaSchedaService(
		it.bysoftware.ct.service.TracciabilitaSchedaService tracciabilitaSchedaService) {
		this.tracciabilitaSchedaService = tracciabilitaSchedaService;
	}

	/**
	 * Returns the tracciabilita scheda persistence.
	 *
	 * @return the tracciabilita scheda persistence
	 */
	public TracciabilitaSchedaPersistence getTracciabilitaSchedaPersistence() {
		return tracciabilitaSchedaPersistence;
	}

	/**
	 * Sets the tracciabilita scheda persistence.
	 *
	 * @param tracciabilitaSchedaPersistence the tracciabilita scheda persistence
	 */
	public void setTracciabilitaSchedaPersistence(
		TracciabilitaSchedaPersistence tracciabilitaSchedaPersistence) {
		this.tracciabilitaSchedaPersistence = tracciabilitaSchedaPersistence;
	}

	/**
	 * Returns the vettori local service.
	 *
	 * @return the vettori local service
	 */
	public it.bysoftware.ct.service.VettoriLocalService getVettoriLocalService() {
		return vettoriLocalService;
	}

	/**
	 * Sets the vettori local service.
	 *
	 * @param vettoriLocalService the vettori local service
	 */
	public void setVettoriLocalService(
		it.bysoftware.ct.service.VettoriLocalService vettoriLocalService) {
		this.vettoriLocalService = vettoriLocalService;
	}

	/**
	 * Returns the vettori remote service.
	 *
	 * @return the vettori remote service
	 */
	public it.bysoftware.ct.service.VettoriService getVettoriService() {
		return vettoriService;
	}

	/**
	 * Sets the vettori remote service.
	 *
	 * @param vettoriService the vettori remote service
	 */
	public void setVettoriService(
		it.bysoftware.ct.service.VettoriService vettoriService) {
		this.vettoriService = vettoriService;
	}

	/**
	 * Returns the vettori persistence.
	 *
	 * @return the vettori persistence
	 */
	public VettoriPersistence getVettoriPersistence() {
		return vettoriPersistence;
	}

	/**
	 * Sets the vettori persistence.
	 *
	 * @param vettoriPersistence the vettori persistence
	 */
	public void setVettoriPersistence(VettoriPersistence vettoriPersistence) {
		this.vettoriPersistence = vettoriPersistence;
	}

	/**
	 * Returns the voci iva local service.
	 *
	 * @return the voci iva local service
	 */
	public it.bysoftware.ct.service.VociIvaLocalService getVociIvaLocalService() {
		return vociIvaLocalService;
	}

	/**
	 * Sets the voci iva local service.
	 *
	 * @param vociIvaLocalService the voci iva local service
	 */
	public void setVociIvaLocalService(
		it.bysoftware.ct.service.VociIvaLocalService vociIvaLocalService) {
		this.vociIvaLocalService = vociIvaLocalService;
	}

	/**
	 * Returns the voci iva remote service.
	 *
	 * @return the voci iva remote service
	 */
	public it.bysoftware.ct.service.VociIvaService getVociIvaService() {
		return vociIvaService;
	}

	/**
	 * Sets the voci iva remote service.
	 *
	 * @param vociIvaService the voci iva remote service
	 */
	public void setVociIvaService(
		it.bysoftware.ct.service.VociIvaService vociIvaService) {
		this.vociIvaService = vociIvaService;
	}

	/**
	 * Returns the voci iva persistence.
	 *
	 * @return the voci iva persistence
	 */
	public VociIvaPersistence getVociIvaPersistence() {
		return vociIvaPersistence;
	}

	/**
	 * Sets the voci iva persistence.
	 *
	 * @param vociIvaPersistence the voci iva persistence
	 */
	public void setVociIvaPersistence(VociIvaPersistence vociIvaPersistence) {
		this.vociIvaPersistence = vociIvaPersistence;
	}

	/**
	 * Returns the w k rigo documento local service.
	 *
	 * @return the w k rigo documento local service
	 */
	public it.bysoftware.ct.service.WKRigoDocumentoLocalService getWKRigoDocumentoLocalService() {
		return wkRigoDocumentoLocalService;
	}

	/**
	 * Sets the w k rigo documento local service.
	 *
	 * @param wkRigoDocumentoLocalService the w k rigo documento local service
	 */
	public void setWKRigoDocumentoLocalService(
		it.bysoftware.ct.service.WKRigoDocumentoLocalService wkRigoDocumentoLocalService) {
		this.wkRigoDocumentoLocalService = wkRigoDocumentoLocalService;
	}

	/**
	 * Returns the w k rigo documento remote service.
	 *
	 * @return the w k rigo documento remote service
	 */
	public it.bysoftware.ct.service.WKRigoDocumentoService getWKRigoDocumentoService() {
		return wkRigoDocumentoService;
	}

	/**
	 * Sets the w k rigo documento remote service.
	 *
	 * @param wkRigoDocumentoService the w k rigo documento remote service
	 */
	public void setWKRigoDocumentoService(
		it.bysoftware.ct.service.WKRigoDocumentoService wkRigoDocumentoService) {
		this.wkRigoDocumentoService = wkRigoDocumentoService;
	}

	/**
	 * Returns the w k rigo documento persistence.
	 *
	 * @return the w k rigo documento persistence
	 */
	public WKRigoDocumentoPersistence getWKRigoDocumentoPersistence() {
		return wkRigoDocumentoPersistence;
	}

	/**
	 * Sets the w k rigo documento persistence.
	 *
	 * @param wkRigoDocumentoPersistence the w k rigo documento persistence
	 */
	public void setWKRigoDocumentoPersistence(
		WKRigoDocumentoPersistence wkRigoDocumentoPersistence) {
		this.wkRigoDocumentoPersistence = wkRigoDocumentoPersistence;
	}

	/**
	 * Returns the w k testata documento local service.
	 *
	 * @return the w k testata documento local service
	 */
	public it.bysoftware.ct.service.WKTestataDocumentoLocalService getWKTestataDocumentoLocalService() {
		return wkTestataDocumentoLocalService;
	}

	/**
	 * Sets the w k testata documento local service.
	 *
	 * @param wkTestataDocumentoLocalService the w k testata documento local service
	 */
	public void setWKTestataDocumentoLocalService(
		it.bysoftware.ct.service.WKTestataDocumentoLocalService wkTestataDocumentoLocalService) {
		this.wkTestataDocumentoLocalService = wkTestataDocumentoLocalService;
	}

	/**
	 * Returns the w k testata documento remote service.
	 *
	 * @return the w k testata documento remote service
	 */
	public it.bysoftware.ct.service.WKTestataDocumentoService getWKTestataDocumentoService() {
		return wkTestataDocumentoService;
	}

	/**
	 * Sets the w k testata documento remote service.
	 *
	 * @param wkTestataDocumentoService the w k testata documento remote service
	 */
	public void setWKTestataDocumentoService(
		it.bysoftware.ct.service.WKTestataDocumentoService wkTestataDocumentoService) {
		this.wkTestataDocumentoService = wkTestataDocumentoService;
	}

	/**
	 * Returns the w k testata documento persistence.
	 *
	 * @return the w k testata documento persistence
	 */
	public WKTestataDocumentoPersistence getWKTestataDocumentoPersistence() {
		return wkTestataDocumentoPersistence;
	}

	/**
	 * Sets the w k testata documento persistence.
	 *
	 * @param wkTestataDocumentoPersistence the w k testata documento persistence
	 */
	public void setWKTestataDocumentoPersistence(
		WKTestataDocumentoPersistence wkTestataDocumentoPersistence) {
		this.wkTestataDocumentoPersistence = wkTestataDocumentoPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public com.liferay.portal.service.UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(
		com.liferay.portal.service.UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		Class<?> clazz = getClass();

		_classLoader = clazz.getClassLoader();

		PersistedModelLocalServiceRegistryUtil.register("it.bysoftware.ct.model.DestinatariDiversi",
			destinatariDiversiLocalService);
	}

	public void destroy() {
		PersistedModelLocalServiceRegistryUtil.unregister(
			"it.bysoftware.ct.model.DestinatariDiversi");
	}

	/**
	 * Returns the Spring bean ID for this bean.
	 *
	 * @return the Spring bean ID for this bean
	 */
	@Override
	public String getBeanIdentifier() {
		return _beanIdentifier;
	}

	/**
	 * Sets the Spring bean ID for this bean.
	 *
	 * @param beanIdentifier the Spring bean ID for this bean
	 */
	@Override
	public void setBeanIdentifier(String beanIdentifier) {
		_beanIdentifier = beanIdentifier;
	}

	@Override
	public Object invokeMethod(String name, String[] parameterTypes,
		Object[] arguments) throws Throwable {
		Thread currentThread = Thread.currentThread();

		ClassLoader contextClassLoader = currentThread.getContextClassLoader();

		if (contextClassLoader != _classLoader) {
			currentThread.setContextClassLoader(_classLoader);
		}

		try {
			return _clpInvoker.invokeMethod(name, parameterTypes, arguments);
		}
		finally {
			if (contextClassLoader != _classLoader) {
				currentThread.setContextClassLoader(contextClassLoader);
			}
		}
	}

	protected Class<?> getModelClass() {
		return DestinatariDiversi.class;
	}

	protected String getModelClassName() {
		return DestinatariDiversi.class.getName();
	}

	/**
	 * Performs an SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) throws SystemException {
		try {
			DataSource dataSource = destinatariDiversiPersistence.getDataSource();

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql, new int[0]);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = it.bysoftware.ct.service.AnagraficaLocalService.class)
	protected it.bysoftware.ct.service.AnagraficaLocalService anagraficaLocalService;
	@BeanReference(type = it.bysoftware.ct.service.AnagraficaService.class)
	protected it.bysoftware.ct.service.AnagraficaService anagraficaService;
	@BeanReference(type = AnagraficaPersistence.class)
	protected AnagraficaPersistence anagraficaPersistence;
	@BeanReference(type = it.bysoftware.ct.service.AnagraficaAssociatoOPLocalService.class)
	protected it.bysoftware.ct.service.AnagraficaAssociatoOPLocalService anagraficaAssociatoOPLocalService;
	@BeanReference(type = it.bysoftware.ct.service.AnagraficaAssociatoOPService.class)
	protected it.bysoftware.ct.service.AnagraficaAssociatoOPService anagraficaAssociatoOPService;
	@BeanReference(type = AnagraficaAssociatoOPPersistence.class)
	protected AnagraficaAssociatoOPPersistence anagraficaAssociatoOPPersistence;
	@BeanReference(type = it.bysoftware.ct.service.ArticoliLocalService.class)
	protected it.bysoftware.ct.service.ArticoliLocalService articoliLocalService;
	@BeanReference(type = it.bysoftware.ct.service.ArticoliService.class)
	protected it.bysoftware.ct.service.ArticoliService articoliService;
	@BeanReference(type = ArticoliPersistence.class)
	protected ArticoliPersistence articoliPersistence;
	@BeanReference(type = it.bysoftware.ct.service.ArticoliAssociatoOPLocalService.class)
	protected it.bysoftware.ct.service.ArticoliAssociatoOPLocalService articoliAssociatoOPLocalService;
	@BeanReference(type = it.bysoftware.ct.service.ArticoliAssociatoOPService.class)
	protected it.bysoftware.ct.service.ArticoliAssociatoOPService articoliAssociatoOPService;
	@BeanReference(type = ArticoliAssociatoOPPersistence.class)
	protected ArticoliAssociatoOPPersistence articoliAssociatoOPPersistence;
	@BeanReference(type = it.bysoftware.ct.service.AspettoEsterioreBeniLocalService.class)
	protected it.bysoftware.ct.service.AspettoEsterioreBeniLocalService aspettoEsterioreBeniLocalService;
	@BeanReference(type = it.bysoftware.ct.service.AspettoEsterioreBeniService.class)
	protected it.bysoftware.ct.service.AspettoEsterioreBeniService aspettoEsterioreBeniService;
	@BeanReference(type = AspettoEsterioreBeniPersistence.class)
	protected AspettoEsterioreBeniPersistence aspettoEsterioreBeniPersistence;
	@BeanReference(type = it.bysoftware.ct.service.AssociatoLocalService.class)
	protected it.bysoftware.ct.service.AssociatoLocalService associatoLocalService;
	@BeanReference(type = it.bysoftware.ct.service.AssociatoService.class)
	protected it.bysoftware.ct.service.AssociatoService associatoService;
	@BeanReference(type = AssociatoPersistence.class)
	protected AssociatoPersistence associatoPersistence;
	@BeanReference(type = it.bysoftware.ct.service.BancheAppoggioLocalService.class)
	protected it.bysoftware.ct.service.BancheAppoggioLocalService bancheAppoggioLocalService;
	@BeanReference(type = it.bysoftware.ct.service.BancheAppoggioService.class)
	protected it.bysoftware.ct.service.BancheAppoggioService bancheAppoggioService;
	@BeanReference(type = BancheAppoggioPersistence.class)
	protected BancheAppoggioPersistence bancheAppoggioPersistence;
	@BeanReference(type = it.bysoftware.ct.service.CausaleTrasportoLocalService.class)
	protected it.bysoftware.ct.service.CausaleTrasportoLocalService causaleTrasportoLocalService;
	@BeanReference(type = it.bysoftware.ct.service.CausaleTrasportoService.class)
	protected it.bysoftware.ct.service.CausaleTrasportoService causaleTrasportoService;
	@BeanReference(type = CausaleTrasportoPersistence.class)
	protected CausaleTrasportoPersistence causaleTrasportoPersistence;
	@BeanReference(type = it.bysoftware.ct.service.CessioneCreditoLocalService.class)
	protected it.bysoftware.ct.service.CessioneCreditoLocalService cessioneCreditoLocalService;
	@BeanReference(type = it.bysoftware.ct.service.CessioneCreditoService.class)
	protected it.bysoftware.ct.service.CessioneCreditoService cessioneCreditoService;
	@BeanReference(type = CessioneCreditoPersistence.class)
	protected CessioneCreditoPersistence cessioneCreditoPersistence;
	@BeanReference(type = it.bysoftware.ct.service.ClientiDatiAggLocalService.class)
	protected it.bysoftware.ct.service.ClientiDatiAggLocalService clientiDatiAggLocalService;
	@BeanReference(type = it.bysoftware.ct.service.ClientiDatiAggService.class)
	protected it.bysoftware.ct.service.ClientiDatiAggService clientiDatiAggService;
	@BeanReference(type = ClientiDatiAggPersistence.class)
	protected ClientiDatiAggPersistence clientiDatiAggPersistence;
	@BeanReference(type = it.bysoftware.ct.service.CMRLocalService.class)
	protected it.bysoftware.ct.service.CMRLocalService cmrLocalService;
	@BeanReference(type = it.bysoftware.ct.service.CMRService.class)
	protected it.bysoftware.ct.service.CMRService cmrService;
	@BeanReference(type = CMRPersistence.class)
	protected CMRPersistence cmrPersistence;
	@BeanReference(type = it.bysoftware.ct.service.CuraTrasportoLocalService.class)
	protected it.bysoftware.ct.service.CuraTrasportoLocalService curaTrasportoLocalService;
	@BeanReference(type = it.bysoftware.ct.service.CuraTrasportoService.class)
	protected it.bysoftware.ct.service.CuraTrasportoService curaTrasportoService;
	@BeanReference(type = CuraTrasportoPersistence.class)
	protected CuraTrasportoPersistence curaTrasportoPersistence;
	@BeanReference(type = it.bysoftware.ct.service.DescrizioniDocumentiLocalService.class)
	protected it.bysoftware.ct.service.DescrizioniDocumentiLocalService descrizioniDocumentiLocalService;
	@BeanReference(type = it.bysoftware.ct.service.DescrizioniDocumentiService.class)
	protected it.bysoftware.ct.service.DescrizioniDocumentiService descrizioniDocumentiService;
	@BeanReference(type = DescrizioniDocumentiPersistence.class)
	protected DescrizioniDocumentiPersistence descrizioniDocumentiPersistence;
	@BeanReference(type = it.bysoftware.ct.service.DescrizioniVariantiLocalService.class)
	protected it.bysoftware.ct.service.DescrizioniVariantiLocalService descrizioniVariantiLocalService;
	@BeanReference(type = it.bysoftware.ct.service.DescrizioniVariantiService.class)
	protected it.bysoftware.ct.service.DescrizioniVariantiService descrizioniVariantiService;
	@BeanReference(type = DescrizioniVariantiPersistence.class)
	protected DescrizioniVariantiPersistence descrizioniVariantiPersistence;
	@BeanReference(type = it.bysoftware.ct.service.DestinatariDiversiLocalService.class)
	protected it.bysoftware.ct.service.DestinatariDiversiLocalService destinatariDiversiLocalService;
	@BeanReference(type = it.bysoftware.ct.service.DestinatariDiversiService.class)
	protected it.bysoftware.ct.service.DestinatariDiversiService destinatariDiversiService;
	@BeanReference(type = DestinatariDiversiPersistence.class)
	protected DestinatariDiversiPersistence destinatariDiversiPersistence;
	@BeanReference(type = it.bysoftware.ct.service.FileUploaderLocalService.class)
	protected it.bysoftware.ct.service.FileUploaderLocalService fileUploaderLocalService;
	@BeanReference(type = it.bysoftware.ct.service.FileUploaderService.class)
	protected it.bysoftware.ct.service.FileUploaderService fileUploaderService;
	@BeanReference(type = FileUploaderPersistence.class)
	protected FileUploaderPersistence fileUploaderPersistence;
	@BeanReference(type = it.bysoftware.ct.service.OrganizzazioneProduttoriLocalService.class)
	protected it.bysoftware.ct.service.OrganizzazioneProduttoriLocalService organizzazioneProduttoriLocalService;
	@BeanReference(type = it.bysoftware.ct.service.OrganizzazioneProduttoriService.class)
	protected it.bysoftware.ct.service.OrganizzazioneProduttoriService organizzazioneProduttoriService;
	@BeanReference(type = OrganizzazioneProduttoriPersistence.class)
	protected OrganizzazioneProduttoriPersistence organizzazioneProduttoriPersistence;
	@BeanReference(type = it.bysoftware.ct.service.PortoLocalService.class)
	protected it.bysoftware.ct.service.PortoLocalService portoLocalService;
	@BeanReference(type = it.bysoftware.ct.service.PortoService.class)
	protected it.bysoftware.ct.service.PortoService portoService;
	@BeanReference(type = PortoPersistence.class)
	protected PortoPersistence portoPersistence;
	@BeanReference(type = it.bysoftware.ct.service.ProgressivoLocalService.class)
	protected it.bysoftware.ct.service.ProgressivoLocalService progressivoLocalService;
	@BeanReference(type = it.bysoftware.ct.service.ProgressivoService.class)
	protected it.bysoftware.ct.service.ProgressivoService progressivoService;
	@BeanReference(type = ProgressivoPersistence.class)
	protected ProgressivoPersistence progressivoPersistence;
	@BeanReference(type = it.bysoftware.ct.service.RigoDocumentoLocalService.class)
	protected it.bysoftware.ct.service.RigoDocumentoLocalService rigoDocumentoLocalService;
	@BeanReference(type = it.bysoftware.ct.service.RigoDocumentoService.class)
	protected it.bysoftware.ct.service.RigoDocumentoService rigoDocumentoService;
	@BeanReference(type = RigoDocumentoPersistence.class)
	protected RigoDocumentoPersistence rigoDocumentoPersistence;
	@BeanReference(type = it.bysoftware.ct.service.TestataDocumentoLocalService.class)
	protected it.bysoftware.ct.service.TestataDocumentoLocalService testataDocumentoLocalService;
	@BeanReference(type = it.bysoftware.ct.service.TestataDocumentoService.class)
	protected it.bysoftware.ct.service.TestataDocumentoService testataDocumentoService;
	@BeanReference(type = TestataDocumentoPersistence.class)
	protected TestataDocumentoPersistence testataDocumentoPersistence;
	@BeanReference(type = it.bysoftware.ct.service.TracciabilitaGrezziLocalService.class)
	protected it.bysoftware.ct.service.TracciabilitaGrezziLocalService tracciabilitaGrezziLocalService;
	@BeanReference(type = it.bysoftware.ct.service.TracciabilitaGrezziService.class)
	protected it.bysoftware.ct.service.TracciabilitaGrezziService tracciabilitaGrezziService;
	@BeanReference(type = TracciabilitaGrezziPersistence.class)
	protected TracciabilitaGrezziPersistence tracciabilitaGrezziPersistence;
	@BeanReference(type = it.bysoftware.ct.service.TracciabilitaSchedaLocalService.class)
	protected it.bysoftware.ct.service.TracciabilitaSchedaLocalService tracciabilitaSchedaLocalService;
	@BeanReference(type = it.bysoftware.ct.service.TracciabilitaSchedaService.class)
	protected it.bysoftware.ct.service.TracciabilitaSchedaService tracciabilitaSchedaService;
	@BeanReference(type = TracciabilitaSchedaPersistence.class)
	protected TracciabilitaSchedaPersistence tracciabilitaSchedaPersistence;
	@BeanReference(type = it.bysoftware.ct.service.VettoriLocalService.class)
	protected it.bysoftware.ct.service.VettoriLocalService vettoriLocalService;
	@BeanReference(type = it.bysoftware.ct.service.VettoriService.class)
	protected it.bysoftware.ct.service.VettoriService vettoriService;
	@BeanReference(type = VettoriPersistence.class)
	protected VettoriPersistence vettoriPersistence;
	@BeanReference(type = it.bysoftware.ct.service.VociIvaLocalService.class)
	protected it.bysoftware.ct.service.VociIvaLocalService vociIvaLocalService;
	@BeanReference(type = it.bysoftware.ct.service.VociIvaService.class)
	protected it.bysoftware.ct.service.VociIvaService vociIvaService;
	@BeanReference(type = VociIvaPersistence.class)
	protected VociIvaPersistence vociIvaPersistence;
	@BeanReference(type = it.bysoftware.ct.service.WKRigoDocumentoLocalService.class)
	protected it.bysoftware.ct.service.WKRigoDocumentoLocalService wkRigoDocumentoLocalService;
	@BeanReference(type = it.bysoftware.ct.service.WKRigoDocumentoService.class)
	protected it.bysoftware.ct.service.WKRigoDocumentoService wkRigoDocumentoService;
	@BeanReference(type = WKRigoDocumentoPersistence.class)
	protected WKRigoDocumentoPersistence wkRigoDocumentoPersistence;
	@BeanReference(type = it.bysoftware.ct.service.WKTestataDocumentoLocalService.class)
	protected it.bysoftware.ct.service.WKTestataDocumentoLocalService wkTestataDocumentoLocalService;
	@BeanReference(type = it.bysoftware.ct.service.WKTestataDocumentoService.class)
	protected it.bysoftware.ct.service.WKTestataDocumentoService wkTestataDocumentoService;
	@BeanReference(type = WKTestataDocumentoPersistence.class)
	protected WKTestataDocumentoPersistence wkTestataDocumentoPersistence;
	@BeanReference(type = com.liferay.counter.service.CounterLocalService.class)
	protected com.liferay.counter.service.CounterLocalService counterLocalService;
	@BeanReference(type = com.liferay.portal.service.ResourceLocalService.class)
	protected com.liferay.portal.service.ResourceLocalService resourceLocalService;
	@BeanReference(type = com.liferay.portal.service.UserLocalService.class)
	protected com.liferay.portal.service.UserLocalService userLocalService;
	@BeanReference(type = com.liferay.portal.service.UserService.class)
	protected com.liferay.portal.service.UserService userService;
	@BeanReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	private String _beanIdentifier;
	private ClassLoader _classLoader;
	private DestinatariDiversiLocalServiceClpInvoker _clpInvoker = new DestinatariDiversiLocalServiceClpInvoker();
}