/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.bysoftware.ct.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;

import it.bysoftware.ct.model.AnagraficaAssociatoOP;
import it.bysoftware.ct.model.AnagraficaAssociatoOPModel;
import it.bysoftware.ct.model.AnagraficaAssociatoOPSoap;
import it.bysoftware.ct.service.persistence.AnagraficaAssociatoOPPK;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the AnagraficaAssociatoOP service. Represents a row in the &quot;anagrafica_associato_op&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link it.bysoftware.ct.model.AnagraficaAssociatoOPModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AnagraficaAssociatoOPImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AnagraficaAssociatoOPImpl
 * @see it.bysoftware.ct.model.AnagraficaAssociatoOP
 * @see it.bysoftware.ct.model.AnagraficaAssociatoOPModel
 * @generated
 */
@JSON(strict = true)
public class AnagraficaAssociatoOPModelImpl extends BaseModelImpl<AnagraficaAssociatoOP>
	implements AnagraficaAssociatoOPModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a anagrafica associato o p model instance should use the {@link it.bysoftware.ct.model.AnagraficaAssociatoOP} interface instead.
	 */
	public static final String TABLE_NAME = "anagrafica_associato_op";
	public static final Object[][] TABLE_COLUMNS = {
			{ "id_associato", Types.BIGINT },
			{ "codice_sogetto_associato", Types.VARCHAR },
			{ "codice_sogetto_op", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table anagrafica_associato_op (id_associato LONG not null,codice_sogetto_associato VARCHAR(75) not null,codice_sogetto_op VARCHAR(75) null,primary key (id_associato, codice_sogetto_associato))";
	public static final String TABLE_SQL_DROP = "drop table anagrafica_associato_op";
	public static final String ORDER_BY_JPQL = " ORDER BY anagraficaAssociatoOP.id.idAssociato ASC, anagraficaAssociatoOP.id.codiceSogettoAssociato ASC";
	public static final String ORDER_BY_SQL = " ORDER BY anagrafica_associato_op.id_associato ASC, anagrafica_associato_op.codice_sogetto_associato ASC";
	public static final String DATA_SOURCE = "gestionaleOPDataSource";
	public static final String SESSION_FACTORY = "gestionaleOPSessionFactory";
	public static final String TX_MANAGER = "gestionaleOPTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.it.bysoftware.ct.model.AnagraficaAssociatoOP"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.it.bysoftware.ct.model.AnagraficaAssociatoOP"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static AnagraficaAssociatoOP toModel(
		AnagraficaAssociatoOPSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		AnagraficaAssociatoOP model = new AnagraficaAssociatoOPImpl();

		model.setIdAssociato(soapModel.getIdAssociato());
		model.setCodiceSogettoAssociato(soapModel.getCodiceSogettoAssociato());
		model.setCodiceSogettoOP(soapModel.getCodiceSogettoOP());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<AnagraficaAssociatoOP> toModels(
		AnagraficaAssociatoOPSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<AnagraficaAssociatoOP> models = new ArrayList<AnagraficaAssociatoOP>(soapModels.length);

		for (AnagraficaAssociatoOPSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.it.bysoftware.ct.model.AnagraficaAssociatoOP"));

	public AnagraficaAssociatoOPModelImpl() {
	}

	@Override
	public AnagraficaAssociatoOPPK getPrimaryKey() {
		return new AnagraficaAssociatoOPPK(_idAssociato, _codiceSogettoAssociato);
	}

	@Override
	public void setPrimaryKey(AnagraficaAssociatoOPPK primaryKey) {
		setIdAssociato(primaryKey.idAssociato);
		setCodiceSogettoAssociato(primaryKey.codiceSogettoAssociato);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return new AnagraficaAssociatoOPPK(_idAssociato, _codiceSogettoAssociato);
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey((AnagraficaAssociatoOPPK)primaryKeyObj);
	}

	@Override
	public Class<?> getModelClass() {
		return AnagraficaAssociatoOP.class;
	}

	@Override
	public String getModelClassName() {
		return AnagraficaAssociatoOP.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("idAssociato", getIdAssociato());
		attributes.put("codiceSogettoAssociato", getCodiceSogettoAssociato());
		attributes.put("codiceSogettoOP", getCodiceSogettoOP());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long idAssociato = (Long)attributes.get("idAssociato");

		if (idAssociato != null) {
			setIdAssociato(idAssociato);
		}

		String codiceSogettoAssociato = (String)attributes.get(
				"codiceSogettoAssociato");

		if (codiceSogettoAssociato != null) {
			setCodiceSogettoAssociato(codiceSogettoAssociato);
		}

		String codiceSogettoOP = (String)attributes.get("codiceSogettoOP");

		if (codiceSogettoOP != null) {
			setCodiceSogettoOP(codiceSogettoOP);
		}
	}

	@JSON
	@Override
	public long getIdAssociato() {
		return _idAssociato;
	}

	@Override
	public void setIdAssociato(long idAssociato) {
		_idAssociato = idAssociato;
	}

	@JSON
	@Override
	public String getCodiceSogettoAssociato() {
		if (_codiceSogettoAssociato == null) {
			return StringPool.BLANK;
		}
		else {
			return _codiceSogettoAssociato;
		}
	}

	@Override
	public void setCodiceSogettoAssociato(String codiceSogettoAssociato) {
		_codiceSogettoAssociato = codiceSogettoAssociato;
	}

	@JSON
	@Override
	public String getCodiceSogettoOP() {
		if (_codiceSogettoOP == null) {
			return StringPool.BLANK;
		}
		else {
			return _codiceSogettoOP;
		}
	}

	@Override
	public void setCodiceSogettoOP(String codiceSogettoOP) {
		_codiceSogettoOP = codiceSogettoOP;
	}

	@Override
	public AnagraficaAssociatoOP toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (AnagraficaAssociatoOP)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		AnagraficaAssociatoOPImpl anagraficaAssociatoOPImpl = new AnagraficaAssociatoOPImpl();

		anagraficaAssociatoOPImpl.setIdAssociato(getIdAssociato());
		anagraficaAssociatoOPImpl.setCodiceSogettoAssociato(getCodiceSogettoAssociato());
		anagraficaAssociatoOPImpl.setCodiceSogettoOP(getCodiceSogettoOP());

		anagraficaAssociatoOPImpl.resetOriginalValues();

		return anagraficaAssociatoOPImpl;
	}

	@Override
	public int compareTo(AnagraficaAssociatoOP anagraficaAssociatoOP) {
		AnagraficaAssociatoOPPK primaryKey = anagraficaAssociatoOP.getPrimaryKey();

		return getPrimaryKey().compareTo(primaryKey);
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof AnagraficaAssociatoOP)) {
			return false;
		}

		AnagraficaAssociatoOP anagraficaAssociatoOP = (AnagraficaAssociatoOP)obj;

		AnagraficaAssociatoOPPK primaryKey = anagraficaAssociatoOP.getPrimaryKey();

		if (getPrimaryKey().equals(primaryKey)) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<AnagraficaAssociatoOP> toCacheModel() {
		AnagraficaAssociatoOPCacheModel anagraficaAssociatoOPCacheModel = new AnagraficaAssociatoOPCacheModel();

		anagraficaAssociatoOPCacheModel.idAssociato = getIdAssociato();

		anagraficaAssociatoOPCacheModel.codiceSogettoAssociato = getCodiceSogettoAssociato();

		String codiceSogettoAssociato = anagraficaAssociatoOPCacheModel.codiceSogettoAssociato;

		if ((codiceSogettoAssociato != null) &&
				(codiceSogettoAssociato.length() == 0)) {
			anagraficaAssociatoOPCacheModel.codiceSogettoAssociato = null;
		}

		anagraficaAssociatoOPCacheModel.codiceSogettoOP = getCodiceSogettoOP();

		String codiceSogettoOP = anagraficaAssociatoOPCacheModel.codiceSogettoOP;

		if ((codiceSogettoOP != null) && (codiceSogettoOP.length() == 0)) {
			anagraficaAssociatoOPCacheModel.codiceSogettoOP = null;
		}

		return anagraficaAssociatoOPCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(7);

		sb.append("{idAssociato=");
		sb.append(getIdAssociato());
		sb.append(", codiceSogettoAssociato=");
		sb.append(getCodiceSogettoAssociato());
		sb.append(", codiceSogettoOP=");
		sb.append(getCodiceSogettoOP());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(13);

		sb.append("<model><model-name>");
		sb.append("it.bysoftware.ct.model.AnagraficaAssociatoOP");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>idAssociato</column-name><column-value><![CDATA[");
		sb.append(getIdAssociato());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>codiceSogettoAssociato</column-name><column-value><![CDATA[");
		sb.append(getCodiceSogettoAssociato());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>codiceSogettoOP</column-name><column-value><![CDATA[");
		sb.append(getCodiceSogettoOP());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = AnagraficaAssociatoOP.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			AnagraficaAssociatoOP.class
		};
	private long _idAssociato;
	private String _codiceSogettoAssociato;
	private String _codiceSogettoOP;
	private AnagraficaAssociatoOP _escapedModel;
}