/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.bysoftware.ct.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;

import it.bysoftware.ct.model.Articoli;
import it.bysoftware.ct.model.ArticoliModel;
import it.bysoftware.ct.model.ArticoliSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the Articoli service. Represents a row in the &quot;Articoli&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link it.bysoftware.ct.model.ArticoliModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ArticoliImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ArticoliImpl
 * @see it.bysoftware.ct.model.Articoli
 * @see it.bysoftware.ct.model.ArticoliModel
 * @generated
 */
@JSON(strict = true)
public class ArticoliModelImpl extends BaseModelImpl<Articoli>
	implements ArticoliModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a articoli model instance should use the {@link it.bysoftware.ct.model.Articoli} interface instead.
	 */
	public static final String TABLE_NAME = "Articoli";
	public static final Object[][] TABLE_COLUMNS = {
			{ "RanCodart", Types.VARCHAR },
			{ "RanCatmer", Types.VARCHAR },
			{ "RanDescri", Types.VARCHAR },
			{ "RanDesdoc", Types.VARCHAR },
			{ "RanDesfis", Types.VARCHAR },
			{ "RanUnimis", Types.VARCHAR },
			{ "RanLibDbl1", Types.DOUBLE },
			{ "RanCodiva", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table Articoli (RanCodart VARCHAR(75) not null primary key,RanCatmer VARCHAR(75) null,RanDescri VARCHAR(75) null,RanDesdoc VARCHAR(75) null,RanDesfis VARCHAR(75) null,RanUnimis VARCHAR(75) null,RanLibDbl1 DOUBLE,RanCodiva VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table Articoli";
	public static final String ORDER_BY_JPQL = " ORDER BY articoli.codiceArticolo ASC";
	public static final String ORDER_BY_SQL = " ORDER BY Articoli.RanCodart ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.it.bysoftware.ct.model.Articoli"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.it.bysoftware.ct.model.Articoli"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.it.bysoftware.ct.model.Articoli"),
			true);
	public static long CATEGORIAMERCEOLOGICA_COLUMN_BITMASK = 1L;
	public static long CODICEARTICOLO_COLUMN_BITMASK = 2L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static Articoli toModel(ArticoliSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		Articoli model = new ArticoliImpl();

		model.setCodiceArticolo(soapModel.getCodiceArticolo());
		model.setCategoriaMerceologica(soapModel.getCategoriaMerceologica());
		model.setDescrizione(soapModel.getDescrizione());
		model.setDescrizioneDocumento(soapModel.getDescrizioneDocumento());
		model.setDescrizioneFiscale(soapModel.getDescrizioneFiscale());
		model.setUnitaMisura(soapModel.getUnitaMisura());
		model.setTara(soapModel.getTara());
		model.setCodiceIVA(soapModel.getCodiceIVA());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<Articoli> toModels(ArticoliSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<Articoli> models = new ArrayList<Articoli>(soapModels.length);

		for (ArticoliSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.it.bysoftware.ct.model.Articoli"));

	public ArticoliModelImpl() {
	}

	@Override
	public String getPrimaryKey() {
		return _codiceArticolo;
	}

	@Override
	public void setPrimaryKey(String primaryKey) {
		setCodiceArticolo(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _codiceArticolo;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey((String)primaryKeyObj);
	}

	@Override
	public Class<?> getModelClass() {
		return Articoli.class;
	}

	@Override
	public String getModelClassName() {
		return Articoli.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("codiceArticolo", getCodiceArticolo());
		attributes.put("categoriaMerceologica", getCategoriaMerceologica());
		attributes.put("descrizione", getDescrizione());
		attributes.put("descrizioneDocumento", getDescrizioneDocumento());
		attributes.put("descrizioneFiscale", getDescrizioneFiscale());
		attributes.put("unitaMisura", getUnitaMisura());
		attributes.put("tara", getTara());
		attributes.put("codiceIVA", getCodiceIVA());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		String codiceArticolo = (String)attributes.get("codiceArticolo");

		if (codiceArticolo != null) {
			setCodiceArticolo(codiceArticolo);
		}

		String categoriaMerceologica = (String)attributes.get(
				"categoriaMerceologica");

		if (categoriaMerceologica != null) {
			setCategoriaMerceologica(categoriaMerceologica);
		}

		String descrizione = (String)attributes.get("descrizione");

		if (descrizione != null) {
			setDescrizione(descrizione);
		}

		String descrizioneDocumento = (String)attributes.get(
				"descrizioneDocumento");

		if (descrizioneDocumento != null) {
			setDescrizioneDocumento(descrizioneDocumento);
		}

		String descrizioneFiscale = (String)attributes.get("descrizioneFiscale");

		if (descrizioneFiscale != null) {
			setDescrizioneFiscale(descrizioneFiscale);
		}

		String unitaMisura = (String)attributes.get("unitaMisura");

		if (unitaMisura != null) {
			setUnitaMisura(unitaMisura);
		}

		Double tara = (Double)attributes.get("tara");

		if (tara != null) {
			setTara(tara);
		}

		String codiceIVA = (String)attributes.get("codiceIVA");

		if (codiceIVA != null) {
			setCodiceIVA(codiceIVA);
		}
	}

	@JSON
	@Override
	public String getCodiceArticolo() {
		if (_codiceArticolo == null) {
			return StringPool.BLANK;
		}
		else {
			return _codiceArticolo;
		}
	}

	@Override
	public void setCodiceArticolo(String codiceArticolo) {
		_codiceArticolo = codiceArticolo;
	}

	@JSON
	@Override
	public String getCategoriaMerceologica() {
		if (_categoriaMerceologica == null) {
			return StringPool.BLANK;
		}
		else {
			return _categoriaMerceologica;
		}
	}

	@Override
	public void setCategoriaMerceologica(String categoriaMerceologica) {
		_columnBitmask |= CATEGORIAMERCEOLOGICA_COLUMN_BITMASK;

		if (_originalCategoriaMerceologica == null) {
			_originalCategoriaMerceologica = _categoriaMerceologica;
		}

		_categoriaMerceologica = categoriaMerceologica;
	}

	public String getOriginalCategoriaMerceologica() {
		return GetterUtil.getString(_originalCategoriaMerceologica);
	}

	@JSON
	@Override
	public String getDescrizione() {
		if (_descrizione == null) {
			return StringPool.BLANK;
		}
		else {
			return _descrizione;
		}
	}

	@Override
	public void setDescrizione(String descrizione) {
		_descrizione = descrizione;
	}

	@JSON
	@Override
	public String getDescrizioneDocumento() {
		if (_descrizioneDocumento == null) {
			return StringPool.BLANK;
		}
		else {
			return _descrizioneDocumento;
		}
	}

	@Override
	public void setDescrizioneDocumento(String descrizioneDocumento) {
		_descrizioneDocumento = descrizioneDocumento;
	}

	@JSON
	@Override
	public String getDescrizioneFiscale() {
		if (_descrizioneFiscale == null) {
			return StringPool.BLANK;
		}
		else {
			return _descrizioneFiscale;
		}
	}

	@Override
	public void setDescrizioneFiscale(String descrizioneFiscale) {
		_descrizioneFiscale = descrizioneFiscale;
	}

	@JSON
	@Override
	public String getUnitaMisura() {
		if (_unitaMisura == null) {
			return StringPool.BLANK;
		}
		else {
			return _unitaMisura;
		}
	}

	@Override
	public void setUnitaMisura(String unitaMisura) {
		_unitaMisura = unitaMisura;
	}

	@JSON
	@Override
	public double getTara() {
		return _tara;
	}

	@Override
	public void setTara(double tara) {
		_tara = tara;
	}

	@JSON
	@Override
	public String getCodiceIVA() {
		if (_codiceIVA == null) {
			return StringPool.BLANK;
		}
		else {
			return _codiceIVA;
		}
	}

	@Override
	public void setCodiceIVA(String codiceIVA) {
		_codiceIVA = codiceIVA;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public Articoli toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (Articoli)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ArticoliImpl articoliImpl = new ArticoliImpl();

		articoliImpl.setCodiceArticolo(getCodiceArticolo());
		articoliImpl.setCategoriaMerceologica(getCategoriaMerceologica());
		articoliImpl.setDescrizione(getDescrizione());
		articoliImpl.setDescrizioneDocumento(getDescrizioneDocumento());
		articoliImpl.setDescrizioneFiscale(getDescrizioneFiscale());
		articoliImpl.setUnitaMisura(getUnitaMisura());
		articoliImpl.setTara(getTara());
		articoliImpl.setCodiceIVA(getCodiceIVA());

		articoliImpl.resetOriginalValues();

		return articoliImpl;
	}

	@Override
	public int compareTo(Articoli articoli) {
		String primaryKey = articoli.getPrimaryKey();

		return getPrimaryKey().compareTo(primaryKey);
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof Articoli)) {
			return false;
		}

		Articoli articoli = (Articoli)obj;

		String primaryKey = articoli.getPrimaryKey();

		if (getPrimaryKey().equals(primaryKey)) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	@Override
	public void resetOriginalValues() {
		ArticoliModelImpl articoliModelImpl = this;

		articoliModelImpl._originalCategoriaMerceologica = articoliModelImpl._categoriaMerceologica;

		articoliModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<Articoli> toCacheModel() {
		ArticoliCacheModel articoliCacheModel = new ArticoliCacheModel();

		articoliCacheModel.codiceArticolo = getCodiceArticolo();

		String codiceArticolo = articoliCacheModel.codiceArticolo;

		if ((codiceArticolo != null) && (codiceArticolo.length() == 0)) {
			articoliCacheModel.codiceArticolo = null;
		}

		articoliCacheModel.categoriaMerceologica = getCategoriaMerceologica();

		String categoriaMerceologica = articoliCacheModel.categoriaMerceologica;

		if ((categoriaMerceologica != null) &&
				(categoriaMerceologica.length() == 0)) {
			articoliCacheModel.categoriaMerceologica = null;
		}

		articoliCacheModel.descrizione = getDescrizione();

		String descrizione = articoliCacheModel.descrizione;

		if ((descrizione != null) && (descrizione.length() == 0)) {
			articoliCacheModel.descrizione = null;
		}

		articoliCacheModel.descrizioneDocumento = getDescrizioneDocumento();

		String descrizioneDocumento = articoliCacheModel.descrizioneDocumento;

		if ((descrizioneDocumento != null) &&
				(descrizioneDocumento.length() == 0)) {
			articoliCacheModel.descrizioneDocumento = null;
		}

		articoliCacheModel.descrizioneFiscale = getDescrizioneFiscale();

		String descrizioneFiscale = articoliCacheModel.descrizioneFiscale;

		if ((descrizioneFiscale != null) && (descrizioneFiscale.length() == 0)) {
			articoliCacheModel.descrizioneFiscale = null;
		}

		articoliCacheModel.unitaMisura = getUnitaMisura();

		String unitaMisura = articoliCacheModel.unitaMisura;

		if ((unitaMisura != null) && (unitaMisura.length() == 0)) {
			articoliCacheModel.unitaMisura = null;
		}

		articoliCacheModel.tara = getTara();

		articoliCacheModel.codiceIVA = getCodiceIVA();

		String codiceIVA = articoliCacheModel.codiceIVA;

		if ((codiceIVA != null) && (codiceIVA.length() == 0)) {
			articoliCacheModel.codiceIVA = null;
		}

		return articoliCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(17);

		sb.append("{codiceArticolo=");
		sb.append(getCodiceArticolo());
		sb.append(", categoriaMerceologica=");
		sb.append(getCategoriaMerceologica());
		sb.append(", descrizione=");
		sb.append(getDescrizione());
		sb.append(", descrizioneDocumento=");
		sb.append(getDescrizioneDocumento());
		sb.append(", descrizioneFiscale=");
		sb.append(getDescrizioneFiscale());
		sb.append(", unitaMisura=");
		sb.append(getUnitaMisura());
		sb.append(", tara=");
		sb.append(getTara());
		sb.append(", codiceIVA=");
		sb.append(getCodiceIVA());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(28);

		sb.append("<model><model-name>");
		sb.append("it.bysoftware.ct.model.Articoli");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>codiceArticolo</column-name><column-value><![CDATA[");
		sb.append(getCodiceArticolo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>categoriaMerceologica</column-name><column-value><![CDATA[");
		sb.append(getCategoriaMerceologica());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>descrizione</column-name><column-value><![CDATA[");
		sb.append(getDescrizione());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>descrizioneDocumento</column-name><column-value><![CDATA[");
		sb.append(getDescrizioneDocumento());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>descrizioneFiscale</column-name><column-value><![CDATA[");
		sb.append(getDescrizioneFiscale());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>unitaMisura</column-name><column-value><![CDATA[");
		sb.append(getUnitaMisura());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tara</column-name><column-value><![CDATA[");
		sb.append(getTara());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>codiceIVA</column-name><column-value><![CDATA[");
		sb.append(getCodiceIVA());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = Articoli.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			Articoli.class
		};
	private String _codiceArticolo;
	private String _categoriaMerceologica;
	private String _originalCategoriaMerceologica;
	private String _descrizione;
	private String _descrizioneDocumento;
	private String _descrizioneFiscale;
	private String _unitaMisura;
	private double _tara;
	private String _codiceIVA;
	private long _columnBitmask;
	private Articoli _escapedModel;
}