/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.bysoftware.ct.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;

import it.bysoftware.ct.model.ArticoliAssociatoOP;
import it.bysoftware.ct.model.ArticoliAssociatoOPModel;
import it.bysoftware.ct.model.ArticoliAssociatoOPSoap;
import it.bysoftware.ct.service.persistence.ArticoliAssociatoOPPK;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the ArticoliAssociatoOP service. Represents a row in the &quot;articoli_associato_op&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link it.bysoftware.ct.model.ArticoliAssociatoOPModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ArticoliAssociatoOPImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ArticoliAssociatoOPImpl
 * @see it.bysoftware.ct.model.ArticoliAssociatoOP
 * @see it.bysoftware.ct.model.ArticoliAssociatoOPModel
 * @generated
 */
@JSON(strict = true)
public class ArticoliAssociatoOPModelImpl extends BaseModelImpl<ArticoliAssociatoOP>
	implements ArticoliAssociatoOPModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a articoli associato o p model instance should use the {@link it.bysoftware.ct.model.ArticoliAssociatoOP} interface instead.
	 */
	public static final String TABLE_NAME = "articoli_associato_op";
	public static final Object[][] TABLE_COLUMNS = {
			{ "id_associato", Types.BIGINT },
			{ "codice_articolo_associato", Types.VARCHAR },
			{ "codice_articolo_op", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table articoli_associato_op (id_associato LONG not null,codice_articolo_associato VARCHAR(75) not null,codice_articolo_op VARCHAR(75) null,primary key (id_associato, codice_articolo_associato))";
	public static final String TABLE_SQL_DROP = "drop table articoli_associato_op";
	public static final String ORDER_BY_JPQL = " ORDER BY articoliAssociatoOP.id.idAssociato ASC, articoliAssociatoOP.id.codiceArticoloAssociato ASC";
	public static final String ORDER_BY_SQL = " ORDER BY articoli_associato_op.id_associato ASC, articoli_associato_op.codice_articolo_associato ASC";
	public static final String DATA_SOURCE = "gestionaleOPDataSource";
	public static final String SESSION_FACTORY = "gestionaleOPSessionFactory";
	public static final String TX_MANAGER = "gestionaleOPTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.it.bysoftware.ct.model.ArticoliAssociatoOP"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.it.bysoftware.ct.model.ArticoliAssociatoOP"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static ArticoliAssociatoOP toModel(ArticoliAssociatoOPSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		ArticoliAssociatoOP model = new ArticoliAssociatoOPImpl();

		model.setIdAssociato(soapModel.getIdAssociato());
		model.setCodiceArticoloAssociato(soapModel.getCodiceArticoloAssociato());
		model.setCodiceArticoloOP(soapModel.getCodiceArticoloOP());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<ArticoliAssociatoOP> toModels(
		ArticoliAssociatoOPSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<ArticoliAssociatoOP> models = new ArrayList<ArticoliAssociatoOP>(soapModels.length);

		for (ArticoliAssociatoOPSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.it.bysoftware.ct.model.ArticoliAssociatoOP"));

	public ArticoliAssociatoOPModelImpl() {
	}

	@Override
	public ArticoliAssociatoOPPK getPrimaryKey() {
		return new ArticoliAssociatoOPPK(_idAssociato, _codiceArticoloAssociato);
	}

	@Override
	public void setPrimaryKey(ArticoliAssociatoOPPK primaryKey) {
		setIdAssociato(primaryKey.idAssociato);
		setCodiceArticoloAssociato(primaryKey.codiceArticoloAssociato);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return new ArticoliAssociatoOPPK(_idAssociato, _codiceArticoloAssociato);
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey((ArticoliAssociatoOPPK)primaryKeyObj);
	}

	@Override
	public Class<?> getModelClass() {
		return ArticoliAssociatoOP.class;
	}

	@Override
	public String getModelClassName() {
		return ArticoliAssociatoOP.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("idAssociato", getIdAssociato());
		attributes.put("codiceArticoloAssociato", getCodiceArticoloAssociato());
		attributes.put("codiceArticoloOP", getCodiceArticoloOP());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long idAssociato = (Long)attributes.get("idAssociato");

		if (idAssociato != null) {
			setIdAssociato(idAssociato);
		}

		String codiceArticoloAssociato = (String)attributes.get(
				"codiceArticoloAssociato");

		if (codiceArticoloAssociato != null) {
			setCodiceArticoloAssociato(codiceArticoloAssociato);
		}

		String codiceArticoloOP = (String)attributes.get("codiceArticoloOP");

		if (codiceArticoloOP != null) {
			setCodiceArticoloOP(codiceArticoloOP);
		}
	}

	@JSON
	@Override
	public long getIdAssociato() {
		return _idAssociato;
	}

	@Override
	public void setIdAssociato(long idAssociato) {
		_idAssociato = idAssociato;
	}

	@JSON
	@Override
	public String getCodiceArticoloAssociato() {
		if (_codiceArticoloAssociato == null) {
			return StringPool.BLANK;
		}
		else {
			return _codiceArticoloAssociato;
		}
	}

	@Override
	public void setCodiceArticoloAssociato(String codiceArticoloAssociato) {
		_codiceArticoloAssociato = codiceArticoloAssociato;
	}

	@JSON
	@Override
	public String getCodiceArticoloOP() {
		if (_codiceArticoloOP == null) {
			return StringPool.BLANK;
		}
		else {
			return _codiceArticoloOP;
		}
	}

	@Override
	public void setCodiceArticoloOP(String codiceArticoloOP) {
		_codiceArticoloOP = codiceArticoloOP;
	}

	@Override
	public ArticoliAssociatoOP toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (ArticoliAssociatoOP)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ArticoliAssociatoOPImpl articoliAssociatoOPImpl = new ArticoliAssociatoOPImpl();

		articoliAssociatoOPImpl.setIdAssociato(getIdAssociato());
		articoliAssociatoOPImpl.setCodiceArticoloAssociato(getCodiceArticoloAssociato());
		articoliAssociatoOPImpl.setCodiceArticoloOP(getCodiceArticoloOP());

		articoliAssociatoOPImpl.resetOriginalValues();

		return articoliAssociatoOPImpl;
	}

	@Override
	public int compareTo(ArticoliAssociatoOP articoliAssociatoOP) {
		ArticoliAssociatoOPPK primaryKey = articoliAssociatoOP.getPrimaryKey();

		return getPrimaryKey().compareTo(primaryKey);
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof ArticoliAssociatoOP)) {
			return false;
		}

		ArticoliAssociatoOP articoliAssociatoOP = (ArticoliAssociatoOP)obj;

		ArticoliAssociatoOPPK primaryKey = articoliAssociatoOP.getPrimaryKey();

		if (getPrimaryKey().equals(primaryKey)) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<ArticoliAssociatoOP> toCacheModel() {
		ArticoliAssociatoOPCacheModel articoliAssociatoOPCacheModel = new ArticoliAssociatoOPCacheModel();

		articoliAssociatoOPCacheModel.idAssociato = getIdAssociato();

		articoliAssociatoOPCacheModel.codiceArticoloAssociato = getCodiceArticoloAssociato();

		String codiceArticoloAssociato = articoliAssociatoOPCacheModel.codiceArticoloAssociato;

		if ((codiceArticoloAssociato != null) &&
				(codiceArticoloAssociato.length() == 0)) {
			articoliAssociatoOPCacheModel.codiceArticoloAssociato = null;
		}

		articoliAssociatoOPCacheModel.codiceArticoloOP = getCodiceArticoloOP();

		String codiceArticoloOP = articoliAssociatoOPCacheModel.codiceArticoloOP;

		if ((codiceArticoloOP != null) && (codiceArticoloOP.length() == 0)) {
			articoliAssociatoOPCacheModel.codiceArticoloOP = null;
		}

		return articoliAssociatoOPCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(7);

		sb.append("{idAssociato=");
		sb.append(getIdAssociato());
		sb.append(", codiceArticoloAssociato=");
		sb.append(getCodiceArticoloAssociato());
		sb.append(", codiceArticoloOP=");
		sb.append(getCodiceArticoloOP());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(13);

		sb.append("<model><model-name>");
		sb.append("it.bysoftware.ct.model.ArticoliAssociatoOP");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>idAssociato</column-name><column-value><![CDATA[");
		sb.append(getIdAssociato());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>codiceArticoloAssociato</column-name><column-value><![CDATA[");
		sb.append(getCodiceArticoloAssociato());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>codiceArticoloOP</column-name><column-value><![CDATA[");
		sb.append(getCodiceArticoloOP());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = ArticoliAssociatoOP.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			ArticoliAssociatoOP.class
		};
	private long _idAssociato;
	private String _codiceArticoloAssociato;
	private String _codiceArticoloOP;
	private ArticoliAssociatoOP _escapedModel;
}