/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.bysoftware.ct.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;

import it.bysoftware.ct.model.BancheAppoggio;
import it.bysoftware.ct.model.BancheAppoggioModel;
import it.bysoftware.ct.model.BancheAppoggioSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the BancheAppoggio service. Represents a row in the &quot;BancheAppoggio&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link it.bysoftware.ct.model.BancheAppoggioModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link BancheAppoggioImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see BancheAppoggioImpl
 * @see it.bysoftware.ct.model.BancheAppoggio
 * @see it.bysoftware.ct.model.BancheAppoggioModel
 * @generated
 */
@JSON(strict = true)
public class BancheAppoggioModelImpl extends BaseModelImpl<BancheAppoggio>
	implements BancheAppoggioModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a banche appoggio model instance should use the {@link it.bysoftware.ct.model.BancheAppoggio} interface instead.
	 */
	public static final String TABLE_NAME = "BancheAppoggio";
	public static final Object[][] TABLE_COLUMNS = {
			{ "`RbaCbanca`", Types.VARCHAR },
			{ "RbaCodabi", Types.INTEGER },
			{ "RbaCodagn", Types.VARCHAR },
			{ "RbaCodban", Types.VARCHAR },
			{ "RbaCodcab", Types.INTEGER },
			{ "RbaDescri", Types.VARCHAR },
			{ "RbaPiazza", Types.VARCHAR },
			{ "RbaCodiaz", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table BancheAppoggio (`RbaCbanca` VARCHAR(75) null,RbaCodabi INTEGER,RbaCodagn VARCHAR(75) null,RbaCodban VARCHAR(75) not null primary key,RbaCodcab INTEGER,RbaDescri VARCHAR(75) null,RbaPiazza VARCHAR(75) null,RbaCodiaz VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table BancheAppoggio";
	public static final String ORDER_BY_JPQL = " ORDER BY bancheAppoggio.codiceBanca ASC";
	public static final String ORDER_BY_SQL = " ORDER BY BancheAppoggio.RbaCodban ASC";
	public static final String DATA_SOURCE = "gestionaleOPDataSource";
	public static final String SESSION_FACTORY = "gestionaleOPSessionFactory";
	public static final String TX_MANAGER = "gestionaleOPTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.it.bysoftware.ct.model.BancheAppoggio"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.it.bysoftware.ct.model.BancheAppoggio"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static BancheAppoggio toModel(BancheAppoggioSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		BancheAppoggio model = new BancheAppoggioImpl();

		model.setCBanca(soapModel.getCBanca());
		model.setCodiceABI(soapModel.getCodiceABI());
		model.setCodiceAgenzia(soapModel.getCodiceAgenzia());
		model.setCodiceBanca(soapModel.getCodiceBanca());
		model.setCodiceCAB(soapModel.getCodiceCAB());
		model.setDescrizione(soapModel.getDescrizione());
		model.setPiazza(soapModel.getPiazza());
		model.setCodiceAzienda(soapModel.getCodiceAzienda());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<BancheAppoggio> toModels(BancheAppoggioSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<BancheAppoggio> models = new ArrayList<BancheAppoggio>(soapModels.length);

		for (BancheAppoggioSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.it.bysoftware.ct.model.BancheAppoggio"));

	public BancheAppoggioModelImpl() {
	}

	@Override
	public String getPrimaryKey() {
		return _codiceBanca;
	}

	@Override
	public void setPrimaryKey(String primaryKey) {
		setCodiceBanca(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _codiceBanca;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey((String)primaryKeyObj);
	}

	@Override
	public Class<?> getModelClass() {
		return BancheAppoggio.class;
	}

	@Override
	public String getModelClassName() {
		return BancheAppoggio.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("cBanca", getCBanca());
		attributes.put("codiceABI", getCodiceABI());
		attributes.put("codiceAgenzia", getCodiceAgenzia());
		attributes.put("codiceBanca", getCodiceBanca());
		attributes.put("codiceCAB", getCodiceCAB());
		attributes.put("descrizione", getDescrizione());
		attributes.put("piazza", getPiazza());
		attributes.put("codiceAzienda", getCodiceAzienda());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		String cBanca = (String)attributes.get("cBanca");

		if (cBanca != null) {
			setCBanca(cBanca);
		}

		Integer codiceABI = (Integer)attributes.get("codiceABI");

		if (codiceABI != null) {
			setCodiceABI(codiceABI);
		}

		String codiceAgenzia = (String)attributes.get("codiceAgenzia");

		if (codiceAgenzia != null) {
			setCodiceAgenzia(codiceAgenzia);
		}

		String codiceBanca = (String)attributes.get("codiceBanca");

		if (codiceBanca != null) {
			setCodiceBanca(codiceBanca);
		}

		Integer codiceCAB = (Integer)attributes.get("codiceCAB");

		if (codiceCAB != null) {
			setCodiceCAB(codiceCAB);
		}

		String descrizione = (String)attributes.get("descrizione");

		if (descrizione != null) {
			setDescrizione(descrizione);
		}

		String piazza = (String)attributes.get("piazza");

		if (piazza != null) {
			setPiazza(piazza);
		}

		String codiceAzienda = (String)attributes.get("codiceAzienda");

		if (codiceAzienda != null) {
			setCodiceAzienda(codiceAzienda);
		}
	}

	@JSON
	@Override
	public String getCBanca() {
		if (_cBanca == null) {
			return StringPool.BLANK;
		}
		else {
			return _cBanca;
		}
	}

	@Override
	public void setCBanca(String cBanca) {
		_cBanca = cBanca;
	}

	@JSON
	@Override
	public int getCodiceABI() {
		return _codiceABI;
	}

	@Override
	public void setCodiceABI(int codiceABI) {
		_codiceABI = codiceABI;
	}

	@JSON
	@Override
	public String getCodiceAgenzia() {
		if (_codiceAgenzia == null) {
			return StringPool.BLANK;
		}
		else {
			return _codiceAgenzia;
		}
	}

	@Override
	public void setCodiceAgenzia(String codiceAgenzia) {
		_codiceAgenzia = codiceAgenzia;
	}

	@JSON
	@Override
	public String getCodiceBanca() {
		if (_codiceBanca == null) {
			return StringPool.BLANK;
		}
		else {
			return _codiceBanca;
		}
	}

	@Override
	public void setCodiceBanca(String codiceBanca) {
		_codiceBanca = codiceBanca;
	}

	@JSON
	@Override
	public int getCodiceCAB() {
		return _codiceCAB;
	}

	@Override
	public void setCodiceCAB(int codiceCAB) {
		_codiceCAB = codiceCAB;
	}

	@JSON
	@Override
	public String getDescrizione() {
		if (_descrizione == null) {
			return StringPool.BLANK;
		}
		else {
			return _descrizione;
		}
	}

	@Override
	public void setDescrizione(String descrizione) {
		_descrizione = descrizione;
	}

	@JSON
	@Override
	public String getPiazza() {
		if (_piazza == null) {
			return StringPool.BLANK;
		}
		else {
			return _piazza;
		}
	}

	@Override
	public void setPiazza(String piazza) {
		_piazza = piazza;
	}

	@JSON
	@Override
	public String getCodiceAzienda() {
		if (_codiceAzienda == null) {
			return StringPool.BLANK;
		}
		else {
			return _codiceAzienda;
		}
	}

	@Override
	public void setCodiceAzienda(String codiceAzienda) {
		_codiceAzienda = codiceAzienda;
	}

	@Override
	public BancheAppoggio toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (BancheAppoggio)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		BancheAppoggioImpl bancheAppoggioImpl = new BancheAppoggioImpl();

		bancheAppoggioImpl.setCBanca(getCBanca());
		bancheAppoggioImpl.setCodiceABI(getCodiceABI());
		bancheAppoggioImpl.setCodiceAgenzia(getCodiceAgenzia());
		bancheAppoggioImpl.setCodiceBanca(getCodiceBanca());
		bancheAppoggioImpl.setCodiceCAB(getCodiceCAB());
		bancheAppoggioImpl.setDescrizione(getDescrizione());
		bancheAppoggioImpl.setPiazza(getPiazza());
		bancheAppoggioImpl.setCodiceAzienda(getCodiceAzienda());

		bancheAppoggioImpl.resetOriginalValues();

		return bancheAppoggioImpl;
	}

	@Override
	public int compareTo(BancheAppoggio bancheAppoggio) {
		String primaryKey = bancheAppoggio.getPrimaryKey();

		return getPrimaryKey().compareTo(primaryKey);
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof BancheAppoggio)) {
			return false;
		}

		BancheAppoggio bancheAppoggio = (BancheAppoggio)obj;

		String primaryKey = bancheAppoggio.getPrimaryKey();

		if (getPrimaryKey().equals(primaryKey)) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<BancheAppoggio> toCacheModel() {
		BancheAppoggioCacheModel bancheAppoggioCacheModel = new BancheAppoggioCacheModel();

		bancheAppoggioCacheModel.cBanca = getCBanca();

		String cBanca = bancheAppoggioCacheModel.cBanca;

		if ((cBanca != null) && (cBanca.length() == 0)) {
			bancheAppoggioCacheModel.cBanca = null;
		}

		bancheAppoggioCacheModel.codiceABI = getCodiceABI();

		bancheAppoggioCacheModel.codiceAgenzia = getCodiceAgenzia();

		String codiceAgenzia = bancheAppoggioCacheModel.codiceAgenzia;

		if ((codiceAgenzia != null) && (codiceAgenzia.length() == 0)) {
			bancheAppoggioCacheModel.codiceAgenzia = null;
		}

		bancheAppoggioCacheModel.codiceBanca = getCodiceBanca();

		String codiceBanca = bancheAppoggioCacheModel.codiceBanca;

		if ((codiceBanca != null) && (codiceBanca.length() == 0)) {
			bancheAppoggioCacheModel.codiceBanca = null;
		}

		bancheAppoggioCacheModel.codiceCAB = getCodiceCAB();

		bancheAppoggioCacheModel.descrizione = getDescrizione();

		String descrizione = bancheAppoggioCacheModel.descrizione;

		if ((descrizione != null) && (descrizione.length() == 0)) {
			bancheAppoggioCacheModel.descrizione = null;
		}

		bancheAppoggioCacheModel.piazza = getPiazza();

		String piazza = bancheAppoggioCacheModel.piazza;

		if ((piazza != null) && (piazza.length() == 0)) {
			bancheAppoggioCacheModel.piazza = null;
		}

		bancheAppoggioCacheModel.codiceAzienda = getCodiceAzienda();

		String codiceAzienda = bancheAppoggioCacheModel.codiceAzienda;

		if ((codiceAzienda != null) && (codiceAzienda.length() == 0)) {
			bancheAppoggioCacheModel.codiceAzienda = null;
		}

		return bancheAppoggioCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(17);

		sb.append("{cBanca=");
		sb.append(getCBanca());
		sb.append(", codiceABI=");
		sb.append(getCodiceABI());
		sb.append(", codiceAgenzia=");
		sb.append(getCodiceAgenzia());
		sb.append(", codiceBanca=");
		sb.append(getCodiceBanca());
		sb.append(", codiceCAB=");
		sb.append(getCodiceCAB());
		sb.append(", descrizione=");
		sb.append(getDescrizione());
		sb.append(", piazza=");
		sb.append(getPiazza());
		sb.append(", codiceAzienda=");
		sb.append(getCodiceAzienda());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(28);

		sb.append("<model><model-name>");
		sb.append("it.bysoftware.ct.model.BancheAppoggio");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>cBanca</column-name><column-value><![CDATA[");
		sb.append(getCBanca());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>codiceABI</column-name><column-value><![CDATA[");
		sb.append(getCodiceABI());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>codiceAgenzia</column-name><column-value><![CDATA[");
		sb.append(getCodiceAgenzia());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>codiceBanca</column-name><column-value><![CDATA[");
		sb.append(getCodiceBanca());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>codiceCAB</column-name><column-value><![CDATA[");
		sb.append(getCodiceCAB());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>descrizione</column-name><column-value><![CDATA[");
		sb.append(getDescrizione());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>piazza</column-name><column-value><![CDATA[");
		sb.append(getPiazza());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>codiceAzienda</column-name><column-value><![CDATA[");
		sb.append(getCodiceAzienda());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = BancheAppoggio.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			BancheAppoggio.class
		};
	private String _cBanca;
	private int _codiceABI;
	private String _codiceAgenzia;
	private String _codiceBanca;
	private int _codiceCAB;
	private String _descrizione;
	private String _piazza;
	private String _codiceAzienda;
	private BancheAppoggio _escapedModel;
}