/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.bysoftware.ct.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;

import it.bysoftware.ct.model.ClientiDatiAgg;
import it.bysoftware.ct.model.ClientiDatiAggModel;
import it.bysoftware.ct.model.ClientiDatiAggSoap;
import it.bysoftware.ct.service.persistence.ClientiDatiAggPK;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the ClientiDatiAgg service. Represents a row in the &quot;ClientiFornitoriDatiAgg&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link it.bysoftware.ct.model.ClientiDatiAggModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ClientiDatiAggImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ClientiDatiAggImpl
 * @see it.bysoftware.ct.model.ClientiDatiAgg
 * @see it.bysoftware.ct.model.ClientiDatiAggModel
 * @generated
 */
@JSON(strict = true)
public class ClientiDatiAggModelImpl extends BaseModelImpl<ClientiDatiAgg>
	implements ClientiDatiAggModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a clienti dati agg model instance should use the {@link it.bysoftware.ct.model.ClientiDatiAgg} interface instead.
	 */
	public static final String TABLE_NAME = "ClientiFornitoriDatiAgg";
	public static final Object[][] TABLE_COLUMNS = {
			{ "RveCodclf", Types.VARCHAR },
			{ "RveTipo", Types.BOOLEAN },
			{ "RveLibStr1", Types.VARCHAR },
			{ "RveEsenzi", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table ClientiFornitoriDatiAgg (RveCodclf VARCHAR(75) not null,RveTipo BOOLEAN not null,RveLibStr1 VARCHAR(75) null,RveEsenzi VARCHAR(75) null,primary key (RveCodclf, RveTipo))";
	public static final String TABLE_SQL_DROP = "drop table ClientiFornitoriDatiAgg";
	public static final String ORDER_BY_JPQL = " ORDER BY clientiDatiAgg.id.codiceAnagrafica ASC, clientiDatiAgg.id.tipo ASC";
	public static final String ORDER_BY_SQL = " ORDER BY ClientiFornitoriDatiAgg.RveCodclf ASC, ClientiFornitoriDatiAgg.RveTipo ASC";
	public static final String DATA_SOURCE = "gestionaleOPDataSource";
	public static final String SESSION_FACTORY = "gestionaleOPSessionFactory";
	public static final String TX_MANAGER = "gestionaleOPTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.it.bysoftware.ct.model.ClientiDatiAgg"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.it.bysoftware.ct.model.ClientiDatiAgg"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.it.bysoftware.ct.model.ClientiDatiAgg"),
			true);
	public static long CODICEANAGRAFICA_COLUMN_BITMASK = 1L;
	public static long TIPO_COLUMN_BITMASK = 2L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static ClientiDatiAgg toModel(ClientiDatiAggSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		ClientiDatiAgg model = new ClientiDatiAggImpl();

		model.setCodiceAnagrafica(soapModel.getCodiceAnagrafica());
		model.setTipo(soapModel.getTipo());
		model.setAssociati(soapModel.getAssociati());
		model.setCodiceAliquota(soapModel.getCodiceAliquota());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<ClientiDatiAgg> toModels(ClientiDatiAggSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<ClientiDatiAgg> models = new ArrayList<ClientiDatiAgg>(soapModels.length);

		for (ClientiDatiAggSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.it.bysoftware.ct.model.ClientiDatiAgg"));

	public ClientiDatiAggModelImpl() {
	}

	@Override
	public ClientiDatiAggPK getPrimaryKey() {
		return new ClientiDatiAggPK(_codiceAnagrafica, _tipo);
	}

	@Override
	public void setPrimaryKey(ClientiDatiAggPK primaryKey) {
		setCodiceAnagrafica(primaryKey.codiceAnagrafica);
		setTipo(primaryKey.tipo);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return new ClientiDatiAggPK(_codiceAnagrafica, _tipo);
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey((ClientiDatiAggPK)primaryKeyObj);
	}

	@Override
	public Class<?> getModelClass() {
		return ClientiDatiAgg.class;
	}

	@Override
	public String getModelClassName() {
		return ClientiDatiAgg.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("codiceAnagrafica", getCodiceAnagrafica());
		attributes.put("tipo", getTipo());
		attributes.put("associati", getAssociati());
		attributes.put("codiceAliquota", getCodiceAliquota());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		String codiceAnagrafica = (String)attributes.get("codiceAnagrafica");

		if (codiceAnagrafica != null) {
			setCodiceAnagrafica(codiceAnagrafica);
		}

		Boolean tipo = (Boolean)attributes.get("tipo");

		if (tipo != null) {
			setTipo(tipo);
		}

		String associati = (String)attributes.get("associati");

		if (associati != null) {
			setAssociati(associati);
		}

		String codiceAliquota = (String)attributes.get("codiceAliquota");

		if (codiceAliquota != null) {
			setCodiceAliquota(codiceAliquota);
		}
	}

	@JSON
	@Override
	public String getCodiceAnagrafica() {
		if (_codiceAnagrafica == null) {
			return StringPool.BLANK;
		}
		else {
			return _codiceAnagrafica;
		}
	}

	@Override
	public void setCodiceAnagrafica(String codiceAnagrafica) {
		_columnBitmask |= CODICEANAGRAFICA_COLUMN_BITMASK;

		if (_originalCodiceAnagrafica == null) {
			_originalCodiceAnagrafica = _codiceAnagrafica;
		}

		_codiceAnagrafica = codiceAnagrafica;
	}

	public String getOriginalCodiceAnagrafica() {
		return GetterUtil.getString(_originalCodiceAnagrafica);
	}

	@JSON
	@Override
	public boolean getTipo() {
		return _tipo;
	}

	@Override
	public boolean isTipo() {
		return _tipo;
	}

	@Override
	public void setTipo(boolean tipo) {
		_tipo = tipo;
	}

	@JSON
	@Override
	public String getAssociati() {
		if (_associati == null) {
			return StringPool.BLANK;
		}
		else {
			return _associati;
		}
	}

	@Override
	public void setAssociati(String associati) {
		_associati = associati;
	}

	@JSON
	@Override
	public String getCodiceAliquota() {
		if (_codiceAliquota == null) {
			return StringPool.BLANK;
		}
		else {
			return _codiceAliquota;
		}
	}

	@Override
	public void setCodiceAliquota(String codiceAliquota) {
		_codiceAliquota = codiceAliquota;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ClientiDatiAgg toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (ClientiDatiAgg)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ClientiDatiAggImpl clientiDatiAggImpl = new ClientiDatiAggImpl();

		clientiDatiAggImpl.setCodiceAnagrafica(getCodiceAnagrafica());
		clientiDatiAggImpl.setTipo(getTipo());
		clientiDatiAggImpl.setAssociati(getAssociati());
		clientiDatiAggImpl.setCodiceAliquota(getCodiceAliquota());

		clientiDatiAggImpl.resetOriginalValues();

		return clientiDatiAggImpl;
	}

	@Override
	public int compareTo(ClientiDatiAgg clientiDatiAgg) {
		ClientiDatiAggPK primaryKey = clientiDatiAgg.getPrimaryKey();

		return getPrimaryKey().compareTo(primaryKey);
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof ClientiDatiAgg)) {
			return false;
		}

		ClientiDatiAgg clientiDatiAgg = (ClientiDatiAgg)obj;

		ClientiDatiAggPK primaryKey = clientiDatiAgg.getPrimaryKey();

		if (getPrimaryKey().equals(primaryKey)) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	@Override
	public void resetOriginalValues() {
		ClientiDatiAggModelImpl clientiDatiAggModelImpl = this;

		clientiDatiAggModelImpl._originalCodiceAnagrafica = clientiDatiAggModelImpl._codiceAnagrafica;

		clientiDatiAggModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<ClientiDatiAgg> toCacheModel() {
		ClientiDatiAggCacheModel clientiDatiAggCacheModel = new ClientiDatiAggCacheModel();

		clientiDatiAggCacheModel.codiceAnagrafica = getCodiceAnagrafica();

		String codiceAnagrafica = clientiDatiAggCacheModel.codiceAnagrafica;

		if ((codiceAnagrafica != null) && (codiceAnagrafica.length() == 0)) {
			clientiDatiAggCacheModel.codiceAnagrafica = null;
		}

		clientiDatiAggCacheModel.tipo = getTipo();

		clientiDatiAggCacheModel.associati = getAssociati();

		String associati = clientiDatiAggCacheModel.associati;

		if ((associati != null) && (associati.length() == 0)) {
			clientiDatiAggCacheModel.associati = null;
		}

		clientiDatiAggCacheModel.codiceAliquota = getCodiceAliquota();

		String codiceAliquota = clientiDatiAggCacheModel.codiceAliquota;

		if ((codiceAliquota != null) && (codiceAliquota.length() == 0)) {
			clientiDatiAggCacheModel.codiceAliquota = null;
		}

		return clientiDatiAggCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(9);

		sb.append("{codiceAnagrafica=");
		sb.append(getCodiceAnagrafica());
		sb.append(", tipo=");
		sb.append(getTipo());
		sb.append(", associati=");
		sb.append(getAssociati());
		sb.append(", codiceAliquota=");
		sb.append(getCodiceAliquota());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(16);

		sb.append("<model><model-name>");
		sb.append("it.bysoftware.ct.model.ClientiDatiAgg");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>codiceAnagrafica</column-name><column-value><![CDATA[");
		sb.append(getCodiceAnagrafica());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tipo</column-name><column-value><![CDATA[");
		sb.append(getTipo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>associati</column-name><column-value><![CDATA[");
		sb.append(getAssociati());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>codiceAliquota</column-name><column-value><![CDATA[");
		sb.append(getCodiceAliquota());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = ClientiDatiAgg.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			ClientiDatiAgg.class
		};
	private String _codiceAnagrafica;
	private String _originalCodiceAnagrafica;
	private boolean _tipo;
	private String _associati;
	private String _codiceAliquota;
	private long _columnBitmask;
	private ClientiDatiAgg _escapedModel;
}