/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.bysoftware.ct.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;

import it.bysoftware.ct.model.RigoDocumento;
import it.bysoftware.ct.model.RigoDocumentoModel;
import it.bysoftware.ct.model.RigoDocumentoSoap;
import it.bysoftware.ct.service.persistence.RigoDocumentoPK;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the RigoDocumento service. Represents a row in the &quot;SSRIGORD&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link it.bysoftware.ct.model.RigoDocumentoModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link RigoDocumentoImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see RigoDocumentoImpl
 * @see it.bysoftware.ct.model.RigoDocumento
 * @see it.bysoftware.ct.model.RigoDocumentoModel
 * @generated
 */
@JSON(strict = true)
public class RigoDocumentoModelImpl extends BaseModelImpl<RigoDocumento>
	implements RigoDocumentoModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a rigo documento model instance should use the {@link it.bysoftware.ct.model.RigoDocumento} interface instead.
	 */
	public static final String TABLE_NAME = "SSRIGORD";
	public static final Object[][] TABLE_COLUMNS = {
			{ "WKAnno", Types.INTEGER },
			{ "WkNOrd", Types.INTEGER },
			{ "WkRigord", Types.INTEGER },
			{ "WkDesvar", Types.VARCHAR },
			{ "WkCodart", Types.VARCHAR },
			{ "WkDescri", Types.VARCHAR },
			{ "WkUnimis", Types.VARCHAR },
			{ "WkColli", Types.INTEGER },
			{ "WkPeslor", Types.DOUBLE },
			{ "WkTara", Types.DOUBLE },
			{ "WkPesnet", Types.DOUBLE },
			{ "WkPrezzo", Types.DOUBLE },
			{ "WkPedane", Types.DOUBLE },
			{ "WkNote", Types.VARCHAR },
			{ "WkTotpes", Types.DOUBLE },
			{ "WKImballo", Types.VARCHAR },
			{ "WkGesRetine", Types.BOOLEAN },
			{ "WkRtxCl", Types.DOUBLE },
			{ "WkKgRetine", Types.DOUBLE },
			{ "WkLotto", Types.VARCHAR },
			{ "CodPassaportoAlfa", Types.VARCHAR },
			{ "CodPassaportoNum", Types.INTEGER }
		};
	public static final String TABLE_SQL_CREATE = "create table SSRIGORD (WKAnno INTEGER not null,WkNOrd INTEGER not null,WkRigord INTEGER not null,WkDesvar VARCHAR(75) null,WkCodart VARCHAR(75) null,WkDescri VARCHAR(75) null,WkUnimis VARCHAR(75) null,WkColli INTEGER,WkPeslor DOUBLE,WkTara DOUBLE,WkPesnet DOUBLE,WkPrezzo DOUBLE,WkPedane DOUBLE,WkNote VARCHAR(75) null,WkTotpes DOUBLE,WKImballo VARCHAR(75) null,WkGesRetine BOOLEAN,WkRtxCl DOUBLE,WkKgRetine DOUBLE,WkLotto VARCHAR(75) null,CodPassaportoAlfa VARCHAR(75) null,CodPassaportoNum INTEGER,primary key (WKAnno, WkNOrd, WkRigord))";
	public static final String TABLE_SQL_DROP = "drop table SSRIGORD";
	public static final String ORDER_BY_JPQL = " ORDER BY rigoDocumento.id.anno ASC, rigoDocumento.id.numeroOrdine ASC, rigoDocumento.id.rigoOrdin ASC";
	public static final String ORDER_BY_SQL = " ORDER BY SSRIGORD.WKAnno ASC, SSRIGORD.WkNOrd ASC, SSRIGORD.WkRigord ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.it.bysoftware.ct.model.RigoDocumento"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.it.bysoftware.ct.model.RigoDocumento"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.it.bysoftware.ct.model.RigoDocumento"),
			true);
	public static long NUMEROORDINE_COLUMN_BITMASK = 1L;
	public static long ANNO_COLUMN_BITMASK = 2L;
	public static long RIGOORDIN_COLUMN_BITMASK = 4L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static RigoDocumento toModel(RigoDocumentoSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		RigoDocumento model = new RigoDocumentoImpl();

		model.setAnno(soapModel.getAnno());
		model.setNumeroOrdine(soapModel.getNumeroOrdine());
		model.setRigoOrdin(soapModel.getRigoOrdin());
		model.setDescrizioneVariante(soapModel.getDescrizioneVariante());
		model.setCodiceArticolo(soapModel.getCodiceArticolo());
		model.setDescrizione(soapModel.getDescrizione());
		model.setUnitaMisura(soapModel.getUnitaMisura());
		model.setColli(soapModel.getColli());
		model.setPesoLordo(soapModel.getPesoLordo());
		model.setTara(soapModel.getTara());
		model.setPesoNetto(soapModel.getPesoNetto());
		model.setPrezzo(soapModel.getPrezzo());
		model.setPedane(soapModel.getPedane());
		model.setNote(soapModel.getNote());
		model.setTotalePesata(soapModel.getTotalePesata());
		model.setImballo(soapModel.getImballo());
		model.setGestioneReti(soapModel.getGestioneReti());
		model.setRtxCl(soapModel.getRtxCl());
		model.setKgRete(soapModel.getKgRete());
		model.setLotto(soapModel.getLotto());
		model.setPassaporto(soapModel.getPassaporto());
		model.setProgressivo(soapModel.getProgressivo());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<RigoDocumento> toModels(RigoDocumentoSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<RigoDocumento> models = new ArrayList<RigoDocumento>(soapModels.length);

		for (RigoDocumentoSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.it.bysoftware.ct.model.RigoDocumento"));

	public RigoDocumentoModelImpl() {
	}

	@Override
	public RigoDocumentoPK getPrimaryKey() {
		return new RigoDocumentoPK(_anno, _numeroOrdine, _rigoOrdin);
	}

	@Override
	public void setPrimaryKey(RigoDocumentoPK primaryKey) {
		setAnno(primaryKey.anno);
		setNumeroOrdine(primaryKey.numeroOrdine);
		setRigoOrdin(primaryKey.rigoOrdin);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return new RigoDocumentoPK(_anno, _numeroOrdine, _rigoOrdin);
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey((RigoDocumentoPK)primaryKeyObj);
	}

	@Override
	public Class<?> getModelClass() {
		return RigoDocumento.class;
	}

	@Override
	public String getModelClassName() {
		return RigoDocumento.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("anno", getAnno());
		attributes.put("numeroOrdine", getNumeroOrdine());
		attributes.put("rigoOrdin", getRigoOrdin());
		attributes.put("descrizioneVariante", getDescrizioneVariante());
		attributes.put("codiceArticolo", getCodiceArticolo());
		attributes.put("descrizione", getDescrizione());
		attributes.put("unitaMisura", getUnitaMisura());
		attributes.put("colli", getColli());
		attributes.put("pesoLordo", getPesoLordo());
		attributes.put("tara", getTara());
		attributes.put("pesoNetto", getPesoNetto());
		attributes.put("prezzo", getPrezzo());
		attributes.put("pedane", getPedane());
		attributes.put("note", getNote());
		attributes.put("totalePesata", getTotalePesata());
		attributes.put("imballo", getImballo());
		attributes.put("gestioneReti", getGestioneReti());
		attributes.put("RtxCl", getRtxCl());
		attributes.put("kgRete", getKgRete());
		attributes.put("lotto", getLotto());
		attributes.put("passaporto", getPassaporto());
		attributes.put("progressivo", getProgressivo());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Integer anno = (Integer)attributes.get("anno");

		if (anno != null) {
			setAnno(anno);
		}

		Integer numeroOrdine = (Integer)attributes.get("numeroOrdine");

		if (numeroOrdine != null) {
			setNumeroOrdine(numeroOrdine);
		}

		Integer rigoOrdin = (Integer)attributes.get("rigoOrdin");

		if (rigoOrdin != null) {
			setRigoOrdin(rigoOrdin);
		}

		String descrizioneVariante = (String)attributes.get(
				"descrizioneVariante");

		if (descrizioneVariante != null) {
			setDescrizioneVariante(descrizioneVariante);
		}

		String codiceArticolo = (String)attributes.get("codiceArticolo");

		if (codiceArticolo != null) {
			setCodiceArticolo(codiceArticolo);
		}

		String descrizione = (String)attributes.get("descrizione");

		if (descrizione != null) {
			setDescrizione(descrizione);
		}

		String unitaMisura = (String)attributes.get("unitaMisura");

		if (unitaMisura != null) {
			setUnitaMisura(unitaMisura);
		}

		Integer colli = (Integer)attributes.get("colli");

		if (colli != null) {
			setColli(colli);
		}

		Double pesoLordo = (Double)attributes.get("pesoLordo");

		if (pesoLordo != null) {
			setPesoLordo(pesoLordo);
		}

		Double tara = (Double)attributes.get("tara");

		if (tara != null) {
			setTara(tara);
		}

		Double pesoNetto = (Double)attributes.get("pesoNetto");

		if (pesoNetto != null) {
			setPesoNetto(pesoNetto);
		}

		Double prezzo = (Double)attributes.get("prezzo");

		if (prezzo != null) {
			setPrezzo(prezzo);
		}

		Double pedane = (Double)attributes.get("pedane");

		if (pedane != null) {
			setPedane(pedane);
		}

		String note = (String)attributes.get("note");

		if (note != null) {
			setNote(note);
		}

		Double totalePesata = (Double)attributes.get("totalePesata");

		if (totalePesata != null) {
			setTotalePesata(totalePesata);
		}

		String imballo = (String)attributes.get("imballo");

		if (imballo != null) {
			setImballo(imballo);
		}

		Boolean gestioneReti = (Boolean)attributes.get("gestioneReti");

		if (gestioneReti != null) {
			setGestioneReti(gestioneReti);
		}

		Double RtxCl = (Double)attributes.get("RtxCl");

		if (RtxCl != null) {
			setRtxCl(RtxCl);
		}

		Double kgRete = (Double)attributes.get("kgRete");

		if (kgRete != null) {
			setKgRete(kgRete);
		}

		String lotto = (String)attributes.get("lotto");

		if (lotto != null) {
			setLotto(lotto);
		}

		String passaporto = (String)attributes.get("passaporto");

		if (passaporto != null) {
			setPassaporto(passaporto);
		}

		Integer progressivo = (Integer)attributes.get("progressivo");

		if (progressivo != null) {
			setProgressivo(progressivo);
		}
	}

	@JSON
	@Override
	public int getAnno() {
		return _anno;
	}

	@Override
	public void setAnno(int anno) {
		_anno = anno;
	}

	@JSON
	@Override
	public int getNumeroOrdine() {
		return _numeroOrdine;
	}

	@Override
	public void setNumeroOrdine(int numeroOrdine) {
		_columnBitmask |= NUMEROORDINE_COLUMN_BITMASK;

		if (!_setOriginalNumeroOrdine) {
			_setOriginalNumeroOrdine = true;

			_originalNumeroOrdine = _numeroOrdine;
		}

		_numeroOrdine = numeroOrdine;
	}

	public int getOriginalNumeroOrdine() {
		return _originalNumeroOrdine;
	}

	@JSON
	@Override
	public int getRigoOrdin() {
		return _rigoOrdin;
	}

	@Override
	public void setRigoOrdin(int rigoOrdin) {
		_rigoOrdin = rigoOrdin;
	}

	@JSON
	@Override
	public String getDescrizioneVariante() {
		if (_descrizioneVariante == null) {
			return StringPool.BLANK;
		}
		else {
			return _descrizioneVariante;
		}
	}

	@Override
	public void setDescrizioneVariante(String descrizioneVariante) {
		_descrizioneVariante = descrizioneVariante;
	}

	@JSON
	@Override
	public String getCodiceArticolo() {
		if (_codiceArticolo == null) {
			return StringPool.BLANK;
		}
		else {
			return _codiceArticolo;
		}
	}

	@Override
	public void setCodiceArticolo(String codiceArticolo) {
		_codiceArticolo = codiceArticolo;
	}

	@JSON
	@Override
	public String getDescrizione() {
		if (_descrizione == null) {
			return StringPool.BLANK;
		}
		else {
			return _descrizione;
		}
	}

	@Override
	public void setDescrizione(String descrizione) {
		_descrizione = descrizione;
	}

	@JSON
	@Override
	public String getUnitaMisura() {
		if (_unitaMisura == null) {
			return StringPool.BLANK;
		}
		else {
			return _unitaMisura;
		}
	}

	@Override
	public void setUnitaMisura(String unitaMisura) {
		_unitaMisura = unitaMisura;
	}

	@JSON
	@Override
	public int getColli() {
		return _colli;
	}

	@Override
	public void setColli(int colli) {
		_colli = colli;
	}

	@JSON
	@Override
	public double getPesoLordo() {
		return _pesoLordo;
	}

	@Override
	public void setPesoLordo(double pesoLordo) {
		_pesoLordo = pesoLordo;
	}

	@JSON
	@Override
	public double getTara() {
		return _tara;
	}

	@Override
	public void setTara(double tara) {
		_tara = tara;
	}

	@JSON
	@Override
	public double getPesoNetto() {
		return _pesoNetto;
	}

	@Override
	public void setPesoNetto(double pesoNetto) {
		_pesoNetto = pesoNetto;
	}

	@JSON
	@Override
	public double getPrezzo() {
		return _prezzo;
	}

	@Override
	public void setPrezzo(double prezzo) {
		_prezzo = prezzo;
	}

	@JSON
	@Override
	public double getPedane() {
		return _pedane;
	}

	@Override
	public void setPedane(double pedane) {
		_pedane = pedane;
	}

	@JSON
	@Override
	public String getNote() {
		if (_note == null) {
			return StringPool.BLANK;
		}
		else {
			return _note;
		}
	}

	@Override
	public void setNote(String note) {
		_note = note;
	}

	@JSON
	@Override
	public double getTotalePesata() {
		return _totalePesata;
	}

	@Override
	public void setTotalePesata(double totalePesata) {
		_totalePesata = totalePesata;
	}

	@JSON
	@Override
	public String getImballo() {
		if (_imballo == null) {
			return StringPool.BLANK;
		}
		else {
			return _imballo;
		}
	}

	@Override
	public void setImballo(String imballo) {
		_imballo = imballo;
	}

	@JSON
	@Override
	public boolean getGestioneReti() {
		return _gestioneReti;
	}

	@Override
	public boolean isGestioneReti() {
		return _gestioneReti;
	}

	@Override
	public void setGestioneReti(boolean gestioneReti) {
		_gestioneReti = gestioneReti;
	}

	@JSON
	@Override
	public double getRtxCl() {
		return _RtxCl;
	}

	@Override
	public void setRtxCl(double RtxCl) {
		_RtxCl = RtxCl;
	}

	@JSON
	@Override
	public double getKgRete() {
		return _kgRete;
	}

	@Override
	public void setKgRete(double kgRete) {
		_kgRete = kgRete;
	}

	@JSON
	@Override
	public String getLotto() {
		if (_lotto == null) {
			return StringPool.BLANK;
		}
		else {
			return _lotto;
		}
	}

	@Override
	public void setLotto(String lotto) {
		_lotto = lotto;
	}

	@JSON
	@Override
	public String getPassaporto() {
		if (_passaporto == null) {
			return StringPool.BLANK;
		}
		else {
			return _passaporto;
		}
	}

	@Override
	public void setPassaporto(String passaporto) {
		_passaporto = passaporto;
	}

	@JSON
	@Override
	public int getProgressivo() {
		return _progressivo;
	}

	@Override
	public void setProgressivo(int progressivo) {
		_progressivo = progressivo;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public RigoDocumento toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (RigoDocumento)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		RigoDocumentoImpl rigoDocumentoImpl = new RigoDocumentoImpl();

		rigoDocumentoImpl.setAnno(getAnno());
		rigoDocumentoImpl.setNumeroOrdine(getNumeroOrdine());
		rigoDocumentoImpl.setRigoOrdin(getRigoOrdin());
		rigoDocumentoImpl.setDescrizioneVariante(getDescrizioneVariante());
		rigoDocumentoImpl.setCodiceArticolo(getCodiceArticolo());
		rigoDocumentoImpl.setDescrizione(getDescrizione());
		rigoDocumentoImpl.setUnitaMisura(getUnitaMisura());
		rigoDocumentoImpl.setColli(getColli());
		rigoDocumentoImpl.setPesoLordo(getPesoLordo());
		rigoDocumentoImpl.setTara(getTara());
		rigoDocumentoImpl.setPesoNetto(getPesoNetto());
		rigoDocumentoImpl.setPrezzo(getPrezzo());
		rigoDocumentoImpl.setPedane(getPedane());
		rigoDocumentoImpl.setNote(getNote());
		rigoDocumentoImpl.setTotalePesata(getTotalePesata());
		rigoDocumentoImpl.setImballo(getImballo());
		rigoDocumentoImpl.setGestioneReti(getGestioneReti());
		rigoDocumentoImpl.setRtxCl(getRtxCl());
		rigoDocumentoImpl.setKgRete(getKgRete());
		rigoDocumentoImpl.setLotto(getLotto());
		rigoDocumentoImpl.setPassaporto(getPassaporto());
		rigoDocumentoImpl.setProgressivo(getProgressivo());

		rigoDocumentoImpl.resetOriginalValues();

		return rigoDocumentoImpl;
	}

	@Override
	public int compareTo(RigoDocumento rigoDocumento) {
		RigoDocumentoPK primaryKey = rigoDocumento.getPrimaryKey();

		return getPrimaryKey().compareTo(primaryKey);
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof RigoDocumento)) {
			return false;
		}

		RigoDocumento rigoDocumento = (RigoDocumento)obj;

		RigoDocumentoPK primaryKey = rigoDocumento.getPrimaryKey();

		if (getPrimaryKey().equals(primaryKey)) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	@Override
	public void resetOriginalValues() {
		RigoDocumentoModelImpl rigoDocumentoModelImpl = this;

		rigoDocumentoModelImpl._originalNumeroOrdine = rigoDocumentoModelImpl._numeroOrdine;

		rigoDocumentoModelImpl._setOriginalNumeroOrdine = false;

		rigoDocumentoModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<RigoDocumento> toCacheModel() {
		RigoDocumentoCacheModel rigoDocumentoCacheModel = new RigoDocumentoCacheModel();

		rigoDocumentoCacheModel.anno = getAnno();

		rigoDocumentoCacheModel.numeroOrdine = getNumeroOrdine();

		rigoDocumentoCacheModel.rigoOrdin = getRigoOrdin();

		rigoDocumentoCacheModel.descrizioneVariante = getDescrizioneVariante();

		String descrizioneVariante = rigoDocumentoCacheModel.descrizioneVariante;

		if ((descrizioneVariante != null) &&
				(descrizioneVariante.length() == 0)) {
			rigoDocumentoCacheModel.descrizioneVariante = null;
		}

		rigoDocumentoCacheModel.codiceArticolo = getCodiceArticolo();

		String codiceArticolo = rigoDocumentoCacheModel.codiceArticolo;

		if ((codiceArticolo != null) && (codiceArticolo.length() == 0)) {
			rigoDocumentoCacheModel.codiceArticolo = null;
		}

		rigoDocumentoCacheModel.descrizione = getDescrizione();

		String descrizione = rigoDocumentoCacheModel.descrizione;

		if ((descrizione != null) && (descrizione.length() == 0)) {
			rigoDocumentoCacheModel.descrizione = null;
		}

		rigoDocumentoCacheModel.unitaMisura = getUnitaMisura();

		String unitaMisura = rigoDocumentoCacheModel.unitaMisura;

		if ((unitaMisura != null) && (unitaMisura.length() == 0)) {
			rigoDocumentoCacheModel.unitaMisura = null;
		}

		rigoDocumentoCacheModel.colli = getColli();

		rigoDocumentoCacheModel.pesoLordo = getPesoLordo();

		rigoDocumentoCacheModel.tara = getTara();

		rigoDocumentoCacheModel.pesoNetto = getPesoNetto();

		rigoDocumentoCacheModel.prezzo = getPrezzo();

		rigoDocumentoCacheModel.pedane = getPedane();

		rigoDocumentoCacheModel.note = getNote();

		String note = rigoDocumentoCacheModel.note;

		if ((note != null) && (note.length() == 0)) {
			rigoDocumentoCacheModel.note = null;
		}

		rigoDocumentoCacheModel.totalePesata = getTotalePesata();

		rigoDocumentoCacheModel.imballo = getImballo();

		String imballo = rigoDocumentoCacheModel.imballo;

		if ((imballo != null) && (imballo.length() == 0)) {
			rigoDocumentoCacheModel.imballo = null;
		}

		rigoDocumentoCacheModel.gestioneReti = getGestioneReti();

		rigoDocumentoCacheModel.RtxCl = getRtxCl();

		rigoDocumentoCacheModel.kgRete = getKgRete();

		rigoDocumentoCacheModel.lotto = getLotto();

		String lotto = rigoDocumentoCacheModel.lotto;

		if ((lotto != null) && (lotto.length() == 0)) {
			rigoDocumentoCacheModel.lotto = null;
		}

		rigoDocumentoCacheModel.passaporto = getPassaporto();

		String passaporto = rigoDocumentoCacheModel.passaporto;

		if ((passaporto != null) && (passaporto.length() == 0)) {
			rigoDocumentoCacheModel.passaporto = null;
		}

		rigoDocumentoCacheModel.progressivo = getProgressivo();

		return rigoDocumentoCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(45);

		sb.append("{anno=");
		sb.append(getAnno());
		sb.append(", numeroOrdine=");
		sb.append(getNumeroOrdine());
		sb.append(", rigoOrdin=");
		sb.append(getRigoOrdin());
		sb.append(", descrizioneVariante=");
		sb.append(getDescrizioneVariante());
		sb.append(", codiceArticolo=");
		sb.append(getCodiceArticolo());
		sb.append(", descrizione=");
		sb.append(getDescrizione());
		sb.append(", unitaMisura=");
		sb.append(getUnitaMisura());
		sb.append(", colli=");
		sb.append(getColli());
		sb.append(", pesoLordo=");
		sb.append(getPesoLordo());
		sb.append(", tara=");
		sb.append(getTara());
		sb.append(", pesoNetto=");
		sb.append(getPesoNetto());
		sb.append(", prezzo=");
		sb.append(getPrezzo());
		sb.append(", pedane=");
		sb.append(getPedane());
		sb.append(", note=");
		sb.append(getNote());
		sb.append(", totalePesata=");
		sb.append(getTotalePesata());
		sb.append(", imballo=");
		sb.append(getImballo());
		sb.append(", gestioneReti=");
		sb.append(getGestioneReti());
		sb.append(", RtxCl=");
		sb.append(getRtxCl());
		sb.append(", kgRete=");
		sb.append(getKgRete());
		sb.append(", lotto=");
		sb.append(getLotto());
		sb.append(", passaporto=");
		sb.append(getPassaporto());
		sb.append(", progressivo=");
		sb.append(getProgressivo());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(70);

		sb.append("<model><model-name>");
		sb.append("it.bysoftware.ct.model.RigoDocumento");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>anno</column-name><column-value><![CDATA[");
		sb.append(getAnno());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>numeroOrdine</column-name><column-value><![CDATA[");
		sb.append(getNumeroOrdine());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>rigoOrdin</column-name><column-value><![CDATA[");
		sb.append(getRigoOrdin());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>descrizioneVariante</column-name><column-value><![CDATA[");
		sb.append(getDescrizioneVariante());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>codiceArticolo</column-name><column-value><![CDATA[");
		sb.append(getCodiceArticolo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>descrizione</column-name><column-value><![CDATA[");
		sb.append(getDescrizione());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>unitaMisura</column-name><column-value><![CDATA[");
		sb.append(getUnitaMisura());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>colli</column-name><column-value><![CDATA[");
		sb.append(getColli());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>pesoLordo</column-name><column-value><![CDATA[");
		sb.append(getPesoLordo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tara</column-name><column-value><![CDATA[");
		sb.append(getTara());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>pesoNetto</column-name><column-value><![CDATA[");
		sb.append(getPesoNetto());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>prezzo</column-name><column-value><![CDATA[");
		sb.append(getPrezzo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>pedane</column-name><column-value><![CDATA[");
		sb.append(getPedane());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>note</column-name><column-value><![CDATA[");
		sb.append(getNote());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>totalePesata</column-name><column-value><![CDATA[");
		sb.append(getTotalePesata());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>imballo</column-name><column-value><![CDATA[");
		sb.append(getImballo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>gestioneReti</column-name><column-value><![CDATA[");
		sb.append(getGestioneReti());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>RtxCl</column-name><column-value><![CDATA[");
		sb.append(getRtxCl());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>kgRete</column-name><column-value><![CDATA[");
		sb.append(getKgRete());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>lotto</column-name><column-value><![CDATA[");
		sb.append(getLotto());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>passaporto</column-name><column-value><![CDATA[");
		sb.append(getPassaporto());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>progressivo</column-name><column-value><![CDATA[");
		sb.append(getProgressivo());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = RigoDocumento.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			RigoDocumento.class
		};
	private int _anno;
	private int _numeroOrdine;
	private int _originalNumeroOrdine;
	private boolean _setOriginalNumeroOrdine;
	private int _rigoOrdin;
	private String _descrizioneVariante;
	private String _codiceArticolo;
	private String _descrizione;
	private String _unitaMisura;
	private int _colli;
	private double _pesoLordo;
	private double _tara;
	private double _pesoNetto;
	private double _prezzo;
	private double _pedane;
	private String _note;
	private double _totalePesata;
	private String _imballo;
	private boolean _gestioneReti;
	private double _RtxCl;
	private double _kgRete;
	private String _lotto;
	private String _passaporto;
	private int _progressivo;
	private long _columnBitmask;
	private RigoDocumento _escapedModel;
}