/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.bysoftware.ct.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;

import it.bysoftware.ct.model.TestataDocumento;
import it.bysoftware.ct.model.TestataDocumentoModel;
import it.bysoftware.ct.model.TestataDocumentoSoap;
import it.bysoftware.ct.service.persistence.TestataDocumentoPK;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the TestataDocumento service. Represents a row in the &quot;SSTESORD&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link it.bysoftware.ct.model.TestataDocumentoModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TestataDocumentoImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TestataDocumentoImpl
 * @see it.bysoftware.ct.model.TestataDocumento
 * @see it.bysoftware.ct.model.TestataDocumentoModel
 * @generated
 */
@JSON(strict = true)
public class TestataDocumentoModelImpl extends BaseModelImpl<TestataDocumento>
	implements TestataDocumentoModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a testata documento model instance should use the {@link it.bysoftware.ct.model.TestataDocumento} interface instead.
	 */
	public static final String TABLE_NAME = "SSTESORD";
	public static final Object[][] TABLE_COLUMNS = {
			{ "WKAnno", Types.INTEGER },
			{ "WKNOrd", Types.BIGINT },
			{ "WkCodsog", Types.VARCHAR },
			{ "WkDatord", Types.VARCHAR },
			{ "WkDatcon", Types.VARCHAR },
			{ "WkDesti2", Types.VARCHAR },
			{ "WkDesdiv", Types.VARCHAR },
			{ "WkRagsoc", Types.VARCHAR },
			{ "WKCompleto", Types.VARCHAR },
			{ "WkOperatore", Types.VARCHAR },
			{ "WKVisto", Types.INTEGER },
			{ "WKInviato", Types.INTEGER },
			{ "WKLotto", Types.VARCHAR },
			{ "WKTipdoc", Types.VARCHAR },
			{ "WkVettore", Types.VARCHAR },
			{ "WkAutista", Types.VARCHAR },
			{ "WkTelefono", Types.VARCHAR },
			{ "WKCentro", Types.VARCHAR },
			{ "EpalCaricati", Types.INTEGER },
			{ "EpalScaricati", Types.INTEGER },
			{ "CodDestiVett1", Types.VARCHAR },
			{ "DestiVett1", Types.VARCHAR },
			{ "Nota1", Types.VARCHAR },
			{ "Nota2", Types.VARCHAR },
			{ "Rigodescrittivo", Types.VARCHAR },
			{ "WkVettore2", Types.VARCHAR },
			{ "TraspCura", Types.VARCHAR },
			{ "AspEst", Types.VARCHAR },
			{ "CauTrasp", Types.VARCHAR },
			{ "porto", Types.VARCHAR },
			{ "Origine", Types.VARCHAR },
			{ "NpedEpal", Types.INTEGER },
			{ "NpedNormali", Types.INTEGER },
			{ "CostoTrasp", Types.DOUBLE },
			{ "TotPedOrd", Types.INTEGER },
			{ "TargaCamion", Types.VARCHAR },
			{ "TargaRimorchio", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table SSTESORD (WKAnno INTEGER not null,WKNOrd LONG not null,WkCodsog VARCHAR(75) null,WkDatord VARCHAR(75) null,WkDatcon VARCHAR(75) null,WkDesti2 VARCHAR(75) null,WkDesdiv VARCHAR(75) null,WkRagsoc VARCHAR(75) null,WKCompleto VARCHAR(75) null,WkOperatore VARCHAR(75) null,WKVisto INTEGER,WKInviato INTEGER,WKLotto VARCHAR(75) null,WKTipdoc VARCHAR(75) null,WkVettore VARCHAR(75) null,WkAutista VARCHAR(75) null,WkTelefono VARCHAR(75) null,WKCentro VARCHAR(75) null,EpalCaricati INTEGER,EpalScaricati INTEGER,CodDestiVett1 VARCHAR(75) null,DestiVett1 VARCHAR(75) null,Nota1 VARCHAR(75) null,Nota2 VARCHAR(75) null,Rigodescrittivo VARCHAR(75) null,WkVettore2 VARCHAR(75) null,TraspCura VARCHAR(75) null,AspEst VARCHAR(75) null,CauTrasp VARCHAR(75) null,porto VARCHAR(75) null,Origine VARCHAR(75) null,NpedEpal INTEGER,NpedNormali INTEGER,CostoTrasp DOUBLE,TotPedOrd INTEGER,TargaCamion VARCHAR(75) null,TargaRimorchio VARCHAR(75) null,primary key (WKAnno, WKNOrd))";
	public static final String TABLE_SQL_DROP = "drop table SSTESORD";
	public static final String ORDER_BY_JPQL = " ORDER BY testataDocumento.id.anno ASC, testataDocumento.id.numeroOrdine ASC";
	public static final String ORDER_BY_SQL = " ORDER BY SSTESORD.WKAnno ASC, SSTESORD.WKNOrd ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.it.bysoftware.ct.model.TestataDocumento"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.it.bysoftware.ct.model.TestataDocumento"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.it.bysoftware.ct.model.TestataDocumento"),
			true);
	public static long CODICESOGGETTO_COLUMN_BITMASK = 1L;
	public static long COMPLETO_COLUMN_BITMASK = 2L;
	public static long INVIATO_COLUMN_BITMASK = 4L;
	public static long OPERATORE_COLUMN_BITMASK = 8L;
	public static long ANNO_COLUMN_BITMASK = 16L;
	public static long NUMEROORDINE_COLUMN_BITMASK = 32L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static TestataDocumento toModel(TestataDocumentoSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		TestataDocumento model = new TestataDocumentoImpl();

		model.setAnno(soapModel.getAnno());
		model.setNumeroOrdine(soapModel.getNumeroOrdine());
		model.setCodiceSoggetto(soapModel.getCodiceSoggetto());
		model.setDataOrdine(soapModel.getDataOrdine());
		model.setDataConsegna(soapModel.getDataConsegna());
		model.setDestinazione(soapModel.getDestinazione());
		model.setCodiceDestinazione(soapModel.getCodiceDestinazione());
		model.setRagioneSociale(soapModel.getRagioneSociale());
		model.setCompleto(soapModel.getCompleto());
		model.setOperatore(soapModel.getOperatore());
		model.setVisto(soapModel.getVisto());
		model.setInviato(soapModel.getInviato());
		model.setLotto(soapModel.getLotto());
		model.setTipoDocumeto(soapModel.getTipoDocumeto());
		model.setVettore(soapModel.getVettore());
		model.setAutista(soapModel.getAutista());
		model.setTelefono(soapModel.getTelefono());
		model.setCentro(soapModel.getCentro());
		model.setPalletCaricati(soapModel.getPalletCaricati());
		model.setPalletScaricati(soapModel.getPalletScaricati());
		model.setCodiceVettore(soapModel.getCodiceVettore());
		model.setDestinazioneVettore(soapModel.getDestinazioneVettore());
		model.setNota1(soapModel.getNota1());
		model.setNota2(soapModel.getNota2());
		model.setRigoDescrittivo(soapModel.getRigoDescrittivo());
		model.setVettore2(soapModel.getVettore2());
		model.setCuraTrasporto(soapModel.getCuraTrasporto());
		model.setAspettoEsteriore(soapModel.getAspettoEsteriore());
		model.setCausaleTrasporto(soapModel.getCausaleTrasporto());
		model.setPorto(soapModel.getPorto());
		model.setOrigine(soapModel.getOrigine());
		model.setNumeroPedaneEuro(soapModel.getNumeroPedaneEuro());
		model.setNumeroPedaneNormali(soapModel.getNumeroPedaneNormali());
		model.setCostoTrasporto(soapModel.getCostoTrasporto());
		model.setTotalePedaneOrdine(soapModel.getTotalePedaneOrdine());
		model.setTargaCamion(soapModel.getTargaCamion());
		model.setTargaRimorchio(soapModel.getTargaRimorchio());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<TestataDocumento> toModels(
		TestataDocumentoSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<TestataDocumento> models = new ArrayList<TestataDocumento>(soapModels.length);

		for (TestataDocumentoSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.it.bysoftware.ct.model.TestataDocumento"));

	public TestataDocumentoModelImpl() {
	}

	@Override
	public TestataDocumentoPK getPrimaryKey() {
		return new TestataDocumentoPK(_anno, _numeroOrdine);
	}

	@Override
	public void setPrimaryKey(TestataDocumentoPK primaryKey) {
		setAnno(primaryKey.anno);
		setNumeroOrdine(primaryKey.numeroOrdine);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return new TestataDocumentoPK(_anno, _numeroOrdine);
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey((TestataDocumentoPK)primaryKeyObj);
	}

	@Override
	public Class<?> getModelClass() {
		return TestataDocumento.class;
	}

	@Override
	public String getModelClassName() {
		return TestataDocumento.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("anno", getAnno());
		attributes.put("numeroOrdine", getNumeroOrdine());
		attributes.put("codiceSoggetto", getCodiceSoggetto());
		attributes.put("dataOrdine", getDataOrdine());
		attributes.put("dataConsegna", getDataConsegna());
		attributes.put("destinazione", getDestinazione());
		attributes.put("codiceDestinazione", getCodiceDestinazione());
		attributes.put("ragioneSociale", getRagioneSociale());
		attributes.put("completo", getCompleto());
		attributes.put("operatore", getOperatore());
		attributes.put("visto", getVisto());
		attributes.put("inviato", getInviato());
		attributes.put("lotto", getLotto());
		attributes.put("tipoDocumeto", getTipoDocumeto());
		attributes.put("vettore", getVettore());
		attributes.put("autista", getAutista());
		attributes.put("telefono", getTelefono());
		attributes.put("centro", getCentro());
		attributes.put("palletCaricati", getPalletCaricati());
		attributes.put("palletScaricati", getPalletScaricati());
		attributes.put("codiceVettore", getCodiceVettore());
		attributes.put("destinazioneVettore", getDestinazioneVettore());
		attributes.put("nota1", getNota1());
		attributes.put("nota2", getNota2());
		attributes.put("rigoDescrittivo", getRigoDescrittivo());
		attributes.put("vettore2", getVettore2());
		attributes.put("curaTrasporto", getCuraTrasporto());
		attributes.put("aspettoEsteriore", getAspettoEsteriore());
		attributes.put("causaleTrasporto", getCausaleTrasporto());
		attributes.put("porto", getPorto());
		attributes.put("origine", getOrigine());
		attributes.put("numeroPedaneEuro", getNumeroPedaneEuro());
		attributes.put("numeroPedaneNormali", getNumeroPedaneNormali());
		attributes.put("costoTrasporto", getCostoTrasporto());
		attributes.put("totalePedaneOrdine", getTotalePedaneOrdine());
		attributes.put("targaCamion", getTargaCamion());
		attributes.put("targaRimorchio", getTargaRimorchio());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Integer anno = (Integer)attributes.get("anno");

		if (anno != null) {
			setAnno(anno);
		}

		Long numeroOrdine = (Long)attributes.get("numeroOrdine");

		if (numeroOrdine != null) {
			setNumeroOrdine(numeroOrdine);
		}

		String codiceSoggetto = (String)attributes.get("codiceSoggetto");

		if (codiceSoggetto != null) {
			setCodiceSoggetto(codiceSoggetto);
		}

		String dataOrdine = (String)attributes.get("dataOrdine");

		if (dataOrdine != null) {
			setDataOrdine(dataOrdine);
		}

		String dataConsegna = (String)attributes.get("dataConsegna");

		if (dataConsegna != null) {
			setDataConsegna(dataConsegna);
		}

		String destinazione = (String)attributes.get("destinazione");

		if (destinazione != null) {
			setDestinazione(destinazione);
		}

		String codiceDestinazione = (String)attributes.get("codiceDestinazione");

		if (codiceDestinazione != null) {
			setCodiceDestinazione(codiceDestinazione);
		}

		String ragioneSociale = (String)attributes.get("ragioneSociale");

		if (ragioneSociale != null) {
			setRagioneSociale(ragioneSociale);
		}

		String completo = (String)attributes.get("completo");

		if (completo != null) {
			setCompleto(completo);
		}

		String operatore = (String)attributes.get("operatore");

		if (operatore != null) {
			setOperatore(operatore);
		}

		Integer visto = (Integer)attributes.get("visto");

		if (visto != null) {
			setVisto(visto);
		}

		Integer inviato = (Integer)attributes.get("inviato");

		if (inviato != null) {
			setInviato(inviato);
		}

		String lotto = (String)attributes.get("lotto");

		if (lotto != null) {
			setLotto(lotto);
		}

		String tipoDocumeto = (String)attributes.get("tipoDocumeto");

		if (tipoDocumeto != null) {
			setTipoDocumeto(tipoDocumeto);
		}

		String vettore = (String)attributes.get("vettore");

		if (vettore != null) {
			setVettore(vettore);
		}

		String autista = (String)attributes.get("autista");

		if (autista != null) {
			setAutista(autista);
		}

		String telefono = (String)attributes.get("telefono");

		if (telefono != null) {
			setTelefono(telefono);
		}

		String centro = (String)attributes.get("centro");

		if (centro != null) {
			setCentro(centro);
		}

		Integer palletCaricati = (Integer)attributes.get("palletCaricati");

		if (palletCaricati != null) {
			setPalletCaricati(palletCaricati);
		}

		Integer palletScaricati = (Integer)attributes.get("palletScaricati");

		if (palletScaricati != null) {
			setPalletScaricati(palletScaricati);
		}

		String codiceVettore = (String)attributes.get("codiceVettore");

		if (codiceVettore != null) {
			setCodiceVettore(codiceVettore);
		}

		String destinazioneVettore = (String)attributes.get(
				"destinazioneVettore");

		if (destinazioneVettore != null) {
			setDestinazioneVettore(destinazioneVettore);
		}

		String nota1 = (String)attributes.get("nota1");

		if (nota1 != null) {
			setNota1(nota1);
		}

		String nota2 = (String)attributes.get("nota2");

		if (nota2 != null) {
			setNota2(nota2);
		}

		String rigoDescrittivo = (String)attributes.get("rigoDescrittivo");

		if (rigoDescrittivo != null) {
			setRigoDescrittivo(rigoDescrittivo);
		}

		String vettore2 = (String)attributes.get("vettore2");

		if (vettore2 != null) {
			setVettore2(vettore2);
		}

		String curaTrasporto = (String)attributes.get("curaTrasporto");

		if (curaTrasporto != null) {
			setCuraTrasporto(curaTrasporto);
		}

		String aspettoEsteriore = (String)attributes.get("aspettoEsteriore");

		if (aspettoEsteriore != null) {
			setAspettoEsteriore(aspettoEsteriore);
		}

		String causaleTrasporto = (String)attributes.get("causaleTrasporto");

		if (causaleTrasporto != null) {
			setCausaleTrasporto(causaleTrasporto);
		}

		String porto = (String)attributes.get("porto");

		if (porto != null) {
			setPorto(porto);
		}

		String origine = (String)attributes.get("origine");

		if (origine != null) {
			setOrigine(origine);
		}

		Integer numeroPedaneEuro = (Integer)attributes.get("numeroPedaneEuro");

		if (numeroPedaneEuro != null) {
			setNumeroPedaneEuro(numeroPedaneEuro);
		}

		Integer numeroPedaneNormali = (Integer)attributes.get(
				"numeroPedaneNormali");

		if (numeroPedaneNormali != null) {
			setNumeroPedaneNormali(numeroPedaneNormali);
		}

		Double costoTrasporto = (Double)attributes.get("costoTrasporto");

		if (costoTrasporto != null) {
			setCostoTrasporto(costoTrasporto);
		}

		Integer totalePedaneOrdine = (Integer)attributes.get(
				"totalePedaneOrdine");

		if (totalePedaneOrdine != null) {
			setTotalePedaneOrdine(totalePedaneOrdine);
		}

		String targaCamion = (String)attributes.get("targaCamion");

		if (targaCamion != null) {
			setTargaCamion(targaCamion);
		}

		String targaRimorchio = (String)attributes.get("targaRimorchio");

		if (targaRimorchio != null) {
			setTargaRimorchio(targaRimorchio);
		}
	}

	@JSON
	@Override
	public int getAnno() {
		return _anno;
	}

	@Override
	public void setAnno(int anno) {
		_anno = anno;
	}

	@JSON
	@Override
	public long getNumeroOrdine() {
		return _numeroOrdine;
	}

	@Override
	public void setNumeroOrdine(long numeroOrdine) {
		_numeroOrdine = numeroOrdine;
	}

	@JSON
	@Override
	public String getCodiceSoggetto() {
		if (_codiceSoggetto == null) {
			return StringPool.BLANK;
		}
		else {
			return _codiceSoggetto;
		}
	}

	@Override
	public void setCodiceSoggetto(String codiceSoggetto) {
		_columnBitmask |= CODICESOGGETTO_COLUMN_BITMASK;

		if (_originalCodiceSoggetto == null) {
			_originalCodiceSoggetto = _codiceSoggetto;
		}

		_codiceSoggetto = codiceSoggetto;
	}

	public String getOriginalCodiceSoggetto() {
		return GetterUtil.getString(_originalCodiceSoggetto);
	}

	@JSON
	@Override
	public String getDataOrdine() {
		if (_dataOrdine == null) {
			return StringPool.BLANK;
		}
		else {
			return _dataOrdine;
		}
	}

	@Override
	public void setDataOrdine(String dataOrdine) {
		_dataOrdine = dataOrdine;
	}

	@JSON
	@Override
	public String getDataConsegna() {
		if (_dataConsegna == null) {
			return StringPool.BLANK;
		}
		else {
			return _dataConsegna;
		}
	}

	@Override
	public void setDataConsegna(String dataConsegna) {
		_dataConsegna = dataConsegna;
	}

	@JSON
	@Override
	public String getDestinazione() {
		if (_destinazione == null) {
			return StringPool.BLANK;
		}
		else {
			return _destinazione;
		}
	}

	@Override
	public void setDestinazione(String destinazione) {
		_destinazione = destinazione;
	}

	@JSON
	@Override
	public String getCodiceDestinazione() {
		if (_codiceDestinazione == null) {
			return StringPool.BLANK;
		}
		else {
			return _codiceDestinazione;
		}
	}

	@Override
	public void setCodiceDestinazione(String codiceDestinazione) {
		_codiceDestinazione = codiceDestinazione;
	}

	@JSON
	@Override
	public String getRagioneSociale() {
		if (_ragioneSociale == null) {
			return StringPool.BLANK;
		}
		else {
			return _ragioneSociale;
		}
	}

	@Override
	public void setRagioneSociale(String ragioneSociale) {
		_ragioneSociale = ragioneSociale;
	}

	@JSON
	@Override
	public String getCompleto() {
		if (_completo == null) {
			return StringPool.BLANK;
		}
		else {
			return _completo;
		}
	}

	@Override
	public void setCompleto(String completo) {
		_columnBitmask |= COMPLETO_COLUMN_BITMASK;

		if (_originalCompleto == null) {
			_originalCompleto = _completo;
		}

		_completo = completo;
	}

	public String getOriginalCompleto() {
		return GetterUtil.getString(_originalCompleto);
	}

	@JSON
	@Override
	public String getOperatore() {
		if (_operatore == null) {
			return StringPool.BLANK;
		}
		else {
			return _operatore;
		}
	}

	@Override
	public void setOperatore(String operatore) {
		_columnBitmask |= OPERATORE_COLUMN_BITMASK;

		if (_originalOperatore == null) {
			_originalOperatore = _operatore;
		}

		_operatore = operatore;
	}

	public String getOriginalOperatore() {
		return GetterUtil.getString(_originalOperatore);
	}

	@JSON
	@Override
	public int getVisto() {
		return _visto;
	}

	@Override
	public void setVisto(int visto) {
		_visto = visto;
	}

	@JSON
	@Override
	public int getInviato() {
		return _inviato;
	}

	@Override
	public void setInviato(int inviato) {
		_columnBitmask |= INVIATO_COLUMN_BITMASK;

		if (!_setOriginalInviato) {
			_setOriginalInviato = true;

			_originalInviato = _inviato;
		}

		_inviato = inviato;
	}

	public int getOriginalInviato() {
		return _originalInviato;
	}

	@JSON
	@Override
	public String getLotto() {
		if (_lotto == null) {
			return StringPool.BLANK;
		}
		else {
			return _lotto;
		}
	}

	@Override
	public void setLotto(String lotto) {
		_lotto = lotto;
	}

	@JSON
	@Override
	public String getTipoDocumeto() {
		if (_tipoDocumeto == null) {
			return StringPool.BLANK;
		}
		else {
			return _tipoDocumeto;
		}
	}

	@Override
	public void setTipoDocumeto(String tipoDocumeto) {
		_tipoDocumeto = tipoDocumeto;
	}

	@JSON
	@Override
	public String getVettore() {
		if (_vettore == null) {
			return StringPool.BLANK;
		}
		else {
			return _vettore;
		}
	}

	@Override
	public void setVettore(String vettore) {
		_vettore = vettore;
	}

	@JSON
	@Override
	public String getAutista() {
		if (_autista == null) {
			return StringPool.BLANK;
		}
		else {
			return _autista;
		}
	}

	@Override
	public void setAutista(String autista) {
		_autista = autista;
	}

	@JSON
	@Override
	public String getTelefono() {
		if (_telefono == null) {
			return StringPool.BLANK;
		}
		else {
			return _telefono;
		}
	}

	@Override
	public void setTelefono(String telefono) {
		_telefono = telefono;
	}

	@JSON
	@Override
	public String getCentro() {
		if (_centro == null) {
			return StringPool.BLANK;
		}
		else {
			return _centro;
		}
	}

	@Override
	public void setCentro(String centro) {
		_centro = centro;
	}

	@JSON
	@Override
	public int getPalletCaricati() {
		return _palletCaricati;
	}

	@Override
	public void setPalletCaricati(int palletCaricati) {
		_palletCaricati = palletCaricati;
	}

	@JSON
	@Override
	public int getPalletScaricati() {
		return _palletScaricati;
	}

	@Override
	public void setPalletScaricati(int palletScaricati) {
		_palletScaricati = palletScaricati;
	}

	@JSON
	@Override
	public String getCodiceVettore() {
		if (_codiceVettore == null) {
			return StringPool.BLANK;
		}
		else {
			return _codiceVettore;
		}
	}

	@Override
	public void setCodiceVettore(String codiceVettore) {
		_codiceVettore = codiceVettore;
	}

	@JSON
	@Override
	public String getDestinazioneVettore() {
		if (_destinazioneVettore == null) {
			return StringPool.BLANK;
		}
		else {
			return _destinazioneVettore;
		}
	}

	@Override
	public void setDestinazioneVettore(String destinazioneVettore) {
		_destinazioneVettore = destinazioneVettore;
	}

	@JSON
	@Override
	public String getNota1() {
		if (_nota1 == null) {
			return StringPool.BLANK;
		}
		else {
			return _nota1;
		}
	}

	@Override
	public void setNota1(String nota1) {
		_nota1 = nota1;
	}

	@JSON
	@Override
	public String getNota2() {
		if (_nota2 == null) {
			return StringPool.BLANK;
		}
		else {
			return _nota2;
		}
	}

	@Override
	public void setNota2(String nota2) {
		_nota2 = nota2;
	}

	@JSON
	@Override
	public String getRigoDescrittivo() {
		if (_rigoDescrittivo == null) {
			return StringPool.BLANK;
		}
		else {
			return _rigoDescrittivo;
		}
	}

	@Override
	public void setRigoDescrittivo(String rigoDescrittivo) {
		_rigoDescrittivo = rigoDescrittivo;
	}

	@JSON
	@Override
	public String getVettore2() {
		if (_vettore2 == null) {
			return StringPool.BLANK;
		}
		else {
			return _vettore2;
		}
	}

	@Override
	public void setVettore2(String vettore2) {
		_vettore2 = vettore2;
	}

	@JSON
	@Override
	public String getCuraTrasporto() {
		if (_curaTrasporto == null) {
			return StringPool.BLANK;
		}
		else {
			return _curaTrasporto;
		}
	}

	@Override
	public void setCuraTrasporto(String curaTrasporto) {
		_curaTrasporto = curaTrasporto;
	}

	@JSON
	@Override
	public String getAspettoEsteriore() {
		if (_aspettoEsteriore == null) {
			return StringPool.BLANK;
		}
		else {
			return _aspettoEsteriore;
		}
	}

	@Override
	public void setAspettoEsteriore(String aspettoEsteriore) {
		_aspettoEsteriore = aspettoEsteriore;
	}

	@JSON
	@Override
	public String getCausaleTrasporto() {
		if (_causaleTrasporto == null) {
			return StringPool.BLANK;
		}
		else {
			return _causaleTrasporto;
		}
	}

	@Override
	public void setCausaleTrasporto(String causaleTrasporto) {
		_causaleTrasporto = causaleTrasporto;
	}

	@JSON
	@Override
	public String getPorto() {
		if (_porto == null) {
			return StringPool.BLANK;
		}
		else {
			return _porto;
		}
	}

	@Override
	public void setPorto(String porto) {
		_porto = porto;
	}

	@JSON
	@Override
	public String getOrigine() {
		if (_origine == null) {
			return StringPool.BLANK;
		}
		else {
			return _origine;
		}
	}

	@Override
	public void setOrigine(String origine) {
		_origine = origine;
	}

	@JSON
	@Override
	public int getNumeroPedaneEuro() {
		return _numeroPedaneEuro;
	}

	@Override
	public void setNumeroPedaneEuro(int numeroPedaneEuro) {
		_numeroPedaneEuro = numeroPedaneEuro;
	}

	@JSON
	@Override
	public int getNumeroPedaneNormali() {
		return _numeroPedaneNormali;
	}

	@Override
	public void setNumeroPedaneNormali(int numeroPedaneNormali) {
		_numeroPedaneNormali = numeroPedaneNormali;
	}

	@JSON
	@Override
	public double getCostoTrasporto() {
		return _costoTrasporto;
	}

	@Override
	public void setCostoTrasporto(double costoTrasporto) {
		_costoTrasporto = costoTrasporto;
	}

	@JSON
	@Override
	public int getTotalePedaneOrdine() {
		return _totalePedaneOrdine;
	}

	@Override
	public void setTotalePedaneOrdine(int totalePedaneOrdine) {
		_totalePedaneOrdine = totalePedaneOrdine;
	}

	@JSON
	@Override
	public String getTargaCamion() {
		if (_targaCamion == null) {
			return StringPool.BLANK;
		}
		else {
			return _targaCamion;
		}
	}

	@Override
	public void setTargaCamion(String targaCamion) {
		_targaCamion = targaCamion;
	}

	@JSON
	@Override
	public String getTargaRimorchio() {
		if (_targaRimorchio == null) {
			return StringPool.BLANK;
		}
		else {
			return _targaRimorchio;
		}
	}

	@Override
	public void setTargaRimorchio(String targaRimorchio) {
		_targaRimorchio = targaRimorchio;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public TestataDocumento toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (TestataDocumento)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		TestataDocumentoImpl testataDocumentoImpl = new TestataDocumentoImpl();

		testataDocumentoImpl.setAnno(getAnno());
		testataDocumentoImpl.setNumeroOrdine(getNumeroOrdine());
		testataDocumentoImpl.setCodiceSoggetto(getCodiceSoggetto());
		testataDocumentoImpl.setDataOrdine(getDataOrdine());
		testataDocumentoImpl.setDataConsegna(getDataConsegna());
		testataDocumentoImpl.setDestinazione(getDestinazione());
		testataDocumentoImpl.setCodiceDestinazione(getCodiceDestinazione());
		testataDocumentoImpl.setRagioneSociale(getRagioneSociale());
		testataDocumentoImpl.setCompleto(getCompleto());
		testataDocumentoImpl.setOperatore(getOperatore());
		testataDocumentoImpl.setVisto(getVisto());
		testataDocumentoImpl.setInviato(getInviato());
		testataDocumentoImpl.setLotto(getLotto());
		testataDocumentoImpl.setTipoDocumeto(getTipoDocumeto());
		testataDocumentoImpl.setVettore(getVettore());
		testataDocumentoImpl.setAutista(getAutista());
		testataDocumentoImpl.setTelefono(getTelefono());
		testataDocumentoImpl.setCentro(getCentro());
		testataDocumentoImpl.setPalletCaricati(getPalletCaricati());
		testataDocumentoImpl.setPalletScaricati(getPalletScaricati());
		testataDocumentoImpl.setCodiceVettore(getCodiceVettore());
		testataDocumentoImpl.setDestinazioneVettore(getDestinazioneVettore());
		testataDocumentoImpl.setNota1(getNota1());
		testataDocumentoImpl.setNota2(getNota2());
		testataDocumentoImpl.setRigoDescrittivo(getRigoDescrittivo());
		testataDocumentoImpl.setVettore2(getVettore2());
		testataDocumentoImpl.setCuraTrasporto(getCuraTrasporto());
		testataDocumentoImpl.setAspettoEsteriore(getAspettoEsteriore());
		testataDocumentoImpl.setCausaleTrasporto(getCausaleTrasporto());
		testataDocumentoImpl.setPorto(getPorto());
		testataDocumentoImpl.setOrigine(getOrigine());
		testataDocumentoImpl.setNumeroPedaneEuro(getNumeroPedaneEuro());
		testataDocumentoImpl.setNumeroPedaneNormali(getNumeroPedaneNormali());
		testataDocumentoImpl.setCostoTrasporto(getCostoTrasporto());
		testataDocumentoImpl.setTotalePedaneOrdine(getTotalePedaneOrdine());
		testataDocumentoImpl.setTargaCamion(getTargaCamion());
		testataDocumentoImpl.setTargaRimorchio(getTargaRimorchio());

		testataDocumentoImpl.resetOriginalValues();

		return testataDocumentoImpl;
	}

	@Override
	public int compareTo(TestataDocumento testataDocumento) {
		TestataDocumentoPK primaryKey = testataDocumento.getPrimaryKey();

		return getPrimaryKey().compareTo(primaryKey);
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof TestataDocumento)) {
			return false;
		}

		TestataDocumento testataDocumento = (TestataDocumento)obj;

		TestataDocumentoPK primaryKey = testataDocumento.getPrimaryKey();

		if (getPrimaryKey().equals(primaryKey)) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	@Override
	public void resetOriginalValues() {
		TestataDocumentoModelImpl testataDocumentoModelImpl = this;

		testataDocumentoModelImpl._originalCodiceSoggetto = testataDocumentoModelImpl._codiceSoggetto;

		testataDocumentoModelImpl._originalCompleto = testataDocumentoModelImpl._completo;

		testataDocumentoModelImpl._originalOperatore = testataDocumentoModelImpl._operatore;

		testataDocumentoModelImpl._originalInviato = testataDocumentoModelImpl._inviato;

		testataDocumentoModelImpl._setOriginalInviato = false;

		testataDocumentoModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<TestataDocumento> toCacheModel() {
		TestataDocumentoCacheModel testataDocumentoCacheModel = new TestataDocumentoCacheModel();

		testataDocumentoCacheModel.anno = getAnno();

		testataDocumentoCacheModel.numeroOrdine = getNumeroOrdine();

		testataDocumentoCacheModel.codiceSoggetto = getCodiceSoggetto();

		String codiceSoggetto = testataDocumentoCacheModel.codiceSoggetto;

		if ((codiceSoggetto != null) && (codiceSoggetto.length() == 0)) {
			testataDocumentoCacheModel.codiceSoggetto = null;
		}

		testataDocumentoCacheModel.dataOrdine = getDataOrdine();

		String dataOrdine = testataDocumentoCacheModel.dataOrdine;

		if ((dataOrdine != null) && (dataOrdine.length() == 0)) {
			testataDocumentoCacheModel.dataOrdine = null;
		}

		testataDocumentoCacheModel.dataConsegna = getDataConsegna();

		String dataConsegna = testataDocumentoCacheModel.dataConsegna;

		if ((dataConsegna != null) && (dataConsegna.length() == 0)) {
			testataDocumentoCacheModel.dataConsegna = null;
		}

		testataDocumentoCacheModel.destinazione = getDestinazione();

		String destinazione = testataDocumentoCacheModel.destinazione;

		if ((destinazione != null) && (destinazione.length() == 0)) {
			testataDocumentoCacheModel.destinazione = null;
		}

		testataDocumentoCacheModel.codiceDestinazione = getCodiceDestinazione();

		String codiceDestinazione = testataDocumentoCacheModel.codiceDestinazione;

		if ((codiceDestinazione != null) && (codiceDestinazione.length() == 0)) {
			testataDocumentoCacheModel.codiceDestinazione = null;
		}

		testataDocumentoCacheModel.ragioneSociale = getRagioneSociale();

		String ragioneSociale = testataDocumentoCacheModel.ragioneSociale;

		if ((ragioneSociale != null) && (ragioneSociale.length() == 0)) {
			testataDocumentoCacheModel.ragioneSociale = null;
		}

		testataDocumentoCacheModel.completo = getCompleto();

		String completo = testataDocumentoCacheModel.completo;

		if ((completo != null) && (completo.length() == 0)) {
			testataDocumentoCacheModel.completo = null;
		}

		testataDocumentoCacheModel.operatore = getOperatore();

		String operatore = testataDocumentoCacheModel.operatore;

		if ((operatore != null) && (operatore.length() == 0)) {
			testataDocumentoCacheModel.operatore = null;
		}

		testataDocumentoCacheModel.visto = getVisto();

		testataDocumentoCacheModel.inviato = getInviato();

		testataDocumentoCacheModel.lotto = getLotto();

		String lotto = testataDocumentoCacheModel.lotto;

		if ((lotto != null) && (lotto.length() == 0)) {
			testataDocumentoCacheModel.lotto = null;
		}

		testataDocumentoCacheModel.tipoDocumeto = getTipoDocumeto();

		String tipoDocumeto = testataDocumentoCacheModel.tipoDocumeto;

		if ((tipoDocumeto != null) && (tipoDocumeto.length() == 0)) {
			testataDocumentoCacheModel.tipoDocumeto = null;
		}

		testataDocumentoCacheModel.vettore = getVettore();

		String vettore = testataDocumentoCacheModel.vettore;

		if ((vettore != null) && (vettore.length() == 0)) {
			testataDocumentoCacheModel.vettore = null;
		}

		testataDocumentoCacheModel.autista = getAutista();

		String autista = testataDocumentoCacheModel.autista;

		if ((autista != null) && (autista.length() == 0)) {
			testataDocumentoCacheModel.autista = null;
		}

		testataDocumentoCacheModel.telefono = getTelefono();

		String telefono = testataDocumentoCacheModel.telefono;

		if ((telefono != null) && (telefono.length() == 0)) {
			testataDocumentoCacheModel.telefono = null;
		}

		testataDocumentoCacheModel.centro = getCentro();

		String centro = testataDocumentoCacheModel.centro;

		if ((centro != null) && (centro.length() == 0)) {
			testataDocumentoCacheModel.centro = null;
		}

		testataDocumentoCacheModel.palletCaricati = getPalletCaricati();

		testataDocumentoCacheModel.palletScaricati = getPalletScaricati();

		testataDocumentoCacheModel.codiceVettore = getCodiceVettore();

		String codiceVettore = testataDocumentoCacheModel.codiceVettore;

		if ((codiceVettore != null) && (codiceVettore.length() == 0)) {
			testataDocumentoCacheModel.codiceVettore = null;
		}

		testataDocumentoCacheModel.destinazioneVettore = getDestinazioneVettore();

		String destinazioneVettore = testataDocumentoCacheModel.destinazioneVettore;

		if ((destinazioneVettore != null) &&
				(destinazioneVettore.length() == 0)) {
			testataDocumentoCacheModel.destinazioneVettore = null;
		}

		testataDocumentoCacheModel.nota1 = getNota1();

		String nota1 = testataDocumentoCacheModel.nota1;

		if ((nota1 != null) && (nota1.length() == 0)) {
			testataDocumentoCacheModel.nota1 = null;
		}

		testataDocumentoCacheModel.nota2 = getNota2();

		String nota2 = testataDocumentoCacheModel.nota2;

		if ((nota2 != null) && (nota2.length() == 0)) {
			testataDocumentoCacheModel.nota2 = null;
		}

		testataDocumentoCacheModel.rigoDescrittivo = getRigoDescrittivo();

		String rigoDescrittivo = testataDocumentoCacheModel.rigoDescrittivo;

		if ((rigoDescrittivo != null) && (rigoDescrittivo.length() == 0)) {
			testataDocumentoCacheModel.rigoDescrittivo = null;
		}

		testataDocumentoCacheModel.vettore2 = getVettore2();

		String vettore2 = testataDocumentoCacheModel.vettore2;

		if ((vettore2 != null) && (vettore2.length() == 0)) {
			testataDocumentoCacheModel.vettore2 = null;
		}

		testataDocumentoCacheModel.curaTrasporto = getCuraTrasporto();

		String curaTrasporto = testataDocumentoCacheModel.curaTrasporto;

		if ((curaTrasporto != null) && (curaTrasporto.length() == 0)) {
			testataDocumentoCacheModel.curaTrasporto = null;
		}

		testataDocumentoCacheModel.aspettoEsteriore = getAspettoEsteriore();

		String aspettoEsteriore = testataDocumentoCacheModel.aspettoEsteriore;

		if ((aspettoEsteriore != null) && (aspettoEsteriore.length() == 0)) {
			testataDocumentoCacheModel.aspettoEsteriore = null;
		}

		testataDocumentoCacheModel.causaleTrasporto = getCausaleTrasporto();

		String causaleTrasporto = testataDocumentoCacheModel.causaleTrasporto;

		if ((causaleTrasporto != null) && (causaleTrasporto.length() == 0)) {
			testataDocumentoCacheModel.causaleTrasporto = null;
		}

		testataDocumentoCacheModel.porto = getPorto();

		String porto = testataDocumentoCacheModel.porto;

		if ((porto != null) && (porto.length() == 0)) {
			testataDocumentoCacheModel.porto = null;
		}

		testataDocumentoCacheModel.origine = getOrigine();

		String origine = testataDocumentoCacheModel.origine;

		if ((origine != null) && (origine.length() == 0)) {
			testataDocumentoCacheModel.origine = null;
		}

		testataDocumentoCacheModel.numeroPedaneEuro = getNumeroPedaneEuro();

		testataDocumentoCacheModel.numeroPedaneNormali = getNumeroPedaneNormali();

		testataDocumentoCacheModel.costoTrasporto = getCostoTrasporto();

		testataDocumentoCacheModel.totalePedaneOrdine = getTotalePedaneOrdine();

		testataDocumentoCacheModel.targaCamion = getTargaCamion();

		String targaCamion = testataDocumentoCacheModel.targaCamion;

		if ((targaCamion != null) && (targaCamion.length() == 0)) {
			testataDocumentoCacheModel.targaCamion = null;
		}

		testataDocumentoCacheModel.targaRimorchio = getTargaRimorchio();

		String targaRimorchio = testataDocumentoCacheModel.targaRimorchio;

		if ((targaRimorchio != null) && (targaRimorchio.length() == 0)) {
			testataDocumentoCacheModel.targaRimorchio = null;
		}

		return testataDocumentoCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(75);

		sb.append("{anno=");
		sb.append(getAnno());
		sb.append(", numeroOrdine=");
		sb.append(getNumeroOrdine());
		sb.append(", codiceSoggetto=");
		sb.append(getCodiceSoggetto());
		sb.append(", dataOrdine=");
		sb.append(getDataOrdine());
		sb.append(", dataConsegna=");
		sb.append(getDataConsegna());
		sb.append(", destinazione=");
		sb.append(getDestinazione());
		sb.append(", codiceDestinazione=");
		sb.append(getCodiceDestinazione());
		sb.append(", ragioneSociale=");
		sb.append(getRagioneSociale());
		sb.append(", completo=");
		sb.append(getCompleto());
		sb.append(", operatore=");
		sb.append(getOperatore());
		sb.append(", visto=");
		sb.append(getVisto());
		sb.append(", inviato=");
		sb.append(getInviato());
		sb.append(", lotto=");
		sb.append(getLotto());
		sb.append(", tipoDocumeto=");
		sb.append(getTipoDocumeto());
		sb.append(", vettore=");
		sb.append(getVettore());
		sb.append(", autista=");
		sb.append(getAutista());
		sb.append(", telefono=");
		sb.append(getTelefono());
		sb.append(", centro=");
		sb.append(getCentro());
		sb.append(", palletCaricati=");
		sb.append(getPalletCaricati());
		sb.append(", palletScaricati=");
		sb.append(getPalletScaricati());
		sb.append(", codiceVettore=");
		sb.append(getCodiceVettore());
		sb.append(", destinazioneVettore=");
		sb.append(getDestinazioneVettore());
		sb.append(", nota1=");
		sb.append(getNota1());
		sb.append(", nota2=");
		sb.append(getNota2());
		sb.append(", rigoDescrittivo=");
		sb.append(getRigoDescrittivo());
		sb.append(", vettore2=");
		sb.append(getVettore2());
		sb.append(", curaTrasporto=");
		sb.append(getCuraTrasporto());
		sb.append(", aspettoEsteriore=");
		sb.append(getAspettoEsteriore());
		sb.append(", causaleTrasporto=");
		sb.append(getCausaleTrasporto());
		sb.append(", porto=");
		sb.append(getPorto());
		sb.append(", origine=");
		sb.append(getOrigine());
		sb.append(", numeroPedaneEuro=");
		sb.append(getNumeroPedaneEuro());
		sb.append(", numeroPedaneNormali=");
		sb.append(getNumeroPedaneNormali());
		sb.append(", costoTrasporto=");
		sb.append(getCostoTrasporto());
		sb.append(", totalePedaneOrdine=");
		sb.append(getTotalePedaneOrdine());
		sb.append(", targaCamion=");
		sb.append(getTargaCamion());
		sb.append(", targaRimorchio=");
		sb.append(getTargaRimorchio());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(115);

		sb.append("<model><model-name>");
		sb.append("it.bysoftware.ct.model.TestataDocumento");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>anno</column-name><column-value><![CDATA[");
		sb.append(getAnno());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>numeroOrdine</column-name><column-value><![CDATA[");
		sb.append(getNumeroOrdine());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>codiceSoggetto</column-name><column-value><![CDATA[");
		sb.append(getCodiceSoggetto());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>dataOrdine</column-name><column-value><![CDATA[");
		sb.append(getDataOrdine());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>dataConsegna</column-name><column-value><![CDATA[");
		sb.append(getDataConsegna());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>destinazione</column-name><column-value><![CDATA[");
		sb.append(getDestinazione());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>codiceDestinazione</column-name><column-value><![CDATA[");
		sb.append(getCodiceDestinazione());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ragioneSociale</column-name><column-value><![CDATA[");
		sb.append(getRagioneSociale());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>completo</column-name><column-value><![CDATA[");
		sb.append(getCompleto());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>operatore</column-name><column-value><![CDATA[");
		sb.append(getOperatore());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>visto</column-name><column-value><![CDATA[");
		sb.append(getVisto());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>inviato</column-name><column-value><![CDATA[");
		sb.append(getInviato());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>lotto</column-name><column-value><![CDATA[");
		sb.append(getLotto());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tipoDocumeto</column-name><column-value><![CDATA[");
		sb.append(getTipoDocumeto());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>vettore</column-name><column-value><![CDATA[");
		sb.append(getVettore());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>autista</column-name><column-value><![CDATA[");
		sb.append(getAutista());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>telefono</column-name><column-value><![CDATA[");
		sb.append(getTelefono());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>centro</column-name><column-value><![CDATA[");
		sb.append(getCentro());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>palletCaricati</column-name><column-value><![CDATA[");
		sb.append(getPalletCaricati());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>palletScaricati</column-name><column-value><![CDATA[");
		sb.append(getPalletScaricati());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>codiceVettore</column-name><column-value><![CDATA[");
		sb.append(getCodiceVettore());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>destinazioneVettore</column-name><column-value><![CDATA[");
		sb.append(getDestinazioneVettore());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nota1</column-name><column-value><![CDATA[");
		sb.append(getNota1());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nota2</column-name><column-value><![CDATA[");
		sb.append(getNota2());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>rigoDescrittivo</column-name><column-value><![CDATA[");
		sb.append(getRigoDescrittivo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>vettore2</column-name><column-value><![CDATA[");
		sb.append(getVettore2());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>curaTrasporto</column-name><column-value><![CDATA[");
		sb.append(getCuraTrasporto());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>aspettoEsteriore</column-name><column-value><![CDATA[");
		sb.append(getAspettoEsteriore());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>causaleTrasporto</column-name><column-value><![CDATA[");
		sb.append(getCausaleTrasporto());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>porto</column-name><column-value><![CDATA[");
		sb.append(getPorto());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>origine</column-name><column-value><![CDATA[");
		sb.append(getOrigine());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>numeroPedaneEuro</column-name><column-value><![CDATA[");
		sb.append(getNumeroPedaneEuro());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>numeroPedaneNormali</column-name><column-value><![CDATA[");
		sb.append(getNumeroPedaneNormali());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>costoTrasporto</column-name><column-value><![CDATA[");
		sb.append(getCostoTrasporto());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>totalePedaneOrdine</column-name><column-value><![CDATA[");
		sb.append(getTotalePedaneOrdine());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>targaCamion</column-name><column-value><![CDATA[");
		sb.append(getTargaCamion());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>targaRimorchio</column-name><column-value><![CDATA[");
		sb.append(getTargaRimorchio());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = TestataDocumento.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			TestataDocumento.class
		};
	private int _anno;
	private long _numeroOrdine;
	private String _codiceSoggetto;
	private String _originalCodiceSoggetto;
	private String _dataOrdine;
	private String _dataConsegna;
	private String _destinazione;
	private String _codiceDestinazione;
	private String _ragioneSociale;
	private String _completo;
	private String _originalCompleto;
	private String _operatore;
	private String _originalOperatore;
	private int _visto;
	private int _inviato;
	private int _originalInviato;
	private boolean _setOriginalInviato;
	private String _lotto;
	private String _tipoDocumeto;
	private String _vettore;
	private String _autista;
	private String _telefono;
	private String _centro;
	private int _palletCaricati;
	private int _palletScaricati;
	private String _codiceVettore;
	private String _destinazioneVettore;
	private String _nota1;
	private String _nota2;
	private String _rigoDescrittivo;
	private String _vettore2;
	private String _curaTrasporto;
	private String _aspettoEsteriore;
	private String _causaleTrasporto;
	private String _porto;
	private String _origine;
	private int _numeroPedaneEuro;
	private int _numeroPedaneNormali;
	private double _costoTrasporto;
	private int _totalePedaneOrdine;
	private String _targaCamion;
	private String _targaRimorchio;
	private long _columnBitmask;
	private TestataDocumento _escapedModel;
}