/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.bysoftware.ct.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import it.bysoftware.ct.service.persistence.AnagraficaAssociatoOPPK;

import java.io.Serializable;

/**
 * The base model interface for the AnagraficaAssociatoOP service. Represents a row in the &quot;anagrafica_associato_op&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link it.bysoftware.ct.model.impl.AnagraficaAssociatoOPModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link it.bysoftware.ct.model.impl.AnagraficaAssociatoOPImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AnagraficaAssociatoOP
 * @see it.bysoftware.ct.model.impl.AnagraficaAssociatoOPImpl
 * @see it.bysoftware.ct.model.impl.AnagraficaAssociatoOPModelImpl
 * @generated
 */
public interface AnagraficaAssociatoOPModel extends BaseModel<AnagraficaAssociatoOP> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a anagrafica associato o p model instance should use the {@link AnagraficaAssociatoOP} interface instead.
	 */

	/**
	 * Returns the primary key of this anagrafica associato o p.
	 *
	 * @return the primary key of this anagrafica associato o p
	 */
	public AnagraficaAssociatoOPPK getPrimaryKey();

	/**
	 * Sets the primary key of this anagrafica associato o p.
	 *
	 * @param primaryKey the primary key of this anagrafica associato o p
	 */
	public void setPrimaryKey(AnagraficaAssociatoOPPK primaryKey);

	/**
	 * Returns the id associato of this anagrafica associato o p.
	 *
	 * @return the id associato of this anagrafica associato o p
	 */
	public long getIdAssociato();

	/**
	 * Sets the id associato of this anagrafica associato o p.
	 *
	 * @param idAssociato the id associato of this anagrafica associato o p
	 */
	public void setIdAssociato(long idAssociato);

	/**
	 * Returns the codice sogetto associato of this anagrafica associato o p.
	 *
	 * @return the codice sogetto associato of this anagrafica associato o p
	 */
	@AutoEscape
	public String getCodiceSogettoAssociato();

	/**
	 * Sets the codice sogetto associato of this anagrafica associato o p.
	 *
	 * @param codiceSogettoAssociato the codice sogetto associato of this anagrafica associato o p
	 */
	public void setCodiceSogettoAssociato(String codiceSogettoAssociato);

	/**
	 * Returns the codice sogetto o p of this anagrafica associato o p.
	 *
	 * @return the codice sogetto o p of this anagrafica associato o p
	 */
	@AutoEscape
	public String getCodiceSogettoOP();

	/**
	 * Sets the codice sogetto o p of this anagrafica associato o p.
	 *
	 * @param codiceSogettoOP the codice sogetto o p of this anagrafica associato o p
	 */
	public void setCodiceSogettoOP(String codiceSogettoOP);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		it.bysoftware.ct.model.AnagraficaAssociatoOP anagraficaAssociatoOP);

	@Override
	public int hashCode();

	@Override
	public CacheModel<it.bysoftware.ct.model.AnagraficaAssociatoOP> toCacheModel();

	@Override
	public it.bysoftware.ct.model.AnagraficaAssociatoOP toEscapedModel();

	@Override
	public it.bysoftware.ct.model.AnagraficaAssociatoOP toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}