/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.bysoftware.ct.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the AspettoEsterioreBeni service. Represents a row in the &quot;AspettoEsterioreBeni&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link it.bysoftware.ct.model.impl.AspettoEsterioreBeniModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link it.bysoftware.ct.model.impl.AspettoEsterioreBeniImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AspettoEsterioreBeni
 * @see it.bysoftware.ct.model.impl.AspettoEsterioreBeniImpl
 * @see it.bysoftware.ct.model.impl.AspettoEsterioreBeniModelImpl
 * @generated
 */
public interface AspettoEsterioreBeniModel extends BaseModel<AspettoEsterioreBeni> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a aspetto esteriore beni model instance should use the {@link AspettoEsterioreBeni} interface instead.
	 */

	/**
	 * Returns the primary key of this aspetto esteriore beni.
	 *
	 * @return the primary key of this aspetto esteriore beni
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this aspetto esteriore beni.
	 *
	 * @param primaryKey the primary key of this aspetto esteriore beni
	 */
	public void setPrimaryKey(String primaryKey);

	/**
	 * Returns the codice aspetto esteriore of this aspetto esteriore beni.
	 *
	 * @return the codice aspetto esteriore of this aspetto esteriore beni
	 */
	@AutoEscape
	public String getCodiceAspettoEsteriore();

	/**
	 * Sets the codice aspetto esteriore of this aspetto esteriore beni.
	 *
	 * @param codiceAspettoEsteriore the codice aspetto esteriore of this aspetto esteriore beni
	 */
	public void setCodiceAspettoEsteriore(String codiceAspettoEsteriore);

	/**
	 * Returns the descrizione of this aspetto esteriore beni.
	 *
	 * @return the descrizione of this aspetto esteriore beni
	 */
	@AutoEscape
	public String getDescrizione();

	/**
	 * Sets the descrizione of this aspetto esteriore beni.
	 *
	 * @param descrizione the descrizione of this aspetto esteriore beni
	 */
	public void setDescrizione(String descrizione);

	/**
	 * Returns the codice azienda of this aspetto esteriore beni.
	 *
	 * @return the codice azienda of this aspetto esteriore beni
	 */
	@AutoEscape
	public String getCodiceAzienda();

	/**
	 * Sets the codice azienda of this aspetto esteriore beni.
	 *
	 * @param codiceAzienda the codice azienda of this aspetto esteriore beni
	 */
	public void setCodiceAzienda(String codiceAzienda);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		it.bysoftware.ct.model.AspettoEsterioreBeni aspettoEsterioreBeni);

	@Override
	public int hashCode();

	@Override
	public CacheModel<it.bysoftware.ct.model.AspettoEsterioreBeni> toCacheModel();

	@Override
	public it.bysoftware.ct.model.AspettoEsterioreBeni toEscapedModel();

	@Override
	public it.bysoftware.ct.model.AspettoEsterioreBeni toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}