/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.bysoftware.ct.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the CessioneCredito service. Represents a row in the &quot;cessioneCredito&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link it.bysoftware.ct.model.impl.CessioneCreditoModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link it.bysoftware.ct.model.impl.CessioneCreditoImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CessioneCredito
 * @see it.bysoftware.ct.model.impl.CessioneCreditoImpl
 * @see it.bysoftware.ct.model.impl.CessioneCreditoModelImpl
 * @generated
 */
public interface CessioneCreditoModel extends BaseModel<CessioneCredito> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a cessione credito model instance should use the {@link CessioneCredito} interface instead.
	 */

	/**
	 * Returns the primary key of this cessione credito.
	 *
	 * @return the primary key of this cessione credito
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this cessione credito.
	 *
	 * @param primaryKey the primary key of this cessione credito
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this cessione credito.
	 *
	 * @return the ID of this cessione credito
	 */
	public long getId();

	/**
	 * Sets the ID of this cessione credito.
	 *
	 * @param id the ID of this cessione credito
	 */
	public void setId(long id);

	/**
	 * Returns the data of this cessione credito.
	 *
	 * @return the data of this cessione credito
	 */
	public Date getData();

	/**
	 * Sets the data of this cessione credito.
	 *
	 * @param data the data of this cessione credito
	 */
	public void setData(Date data);

	/**
	 * Returns the codice soggetto of this cessione credito.
	 *
	 * @return the codice soggetto of this cessione credito
	 */
	@AutoEscape
	public String getCodiceSoggetto();

	/**
	 * Sets the codice soggetto of this cessione credito.
	 *
	 * @param codiceSoggetto the codice soggetto of this cessione credito
	 */
	public void setCodiceSoggetto(String codiceSoggetto);

	/**
	 * Returns the id associato of this cessione credito.
	 *
	 * @return the id associato of this cessione credito
	 */
	public long getIdAssociato();

	/**
	 * Sets the id associato of this cessione credito.
	 *
	 * @param idAssociato the id associato of this cessione credito
	 */
	public void setIdAssociato(long idAssociato);

	/**
	 * Returns the id file of this cessione credito.
	 *
	 * @return the id file of this cessione credito
	 */
	public long getIdFile();

	/**
	 * Sets the id file of this cessione credito.
	 *
	 * @param idFile the id file of this cessione credito
	 */
	public void setIdFile(long idFile);

	/**
	 * Returns the anno of this cessione credito.
	 *
	 * @return the anno of this cessione credito
	 */
	public int getAnno();

	/**
	 * Sets the anno of this cessione credito.
	 *
	 * @param anno the anno of this cessione credito
	 */
	public void setAnno(int anno);

	/**
	 * Returns the numero fattura of this cessione credito.
	 *
	 * @return the numero fattura of this cessione credito
	 */
	public int getNumeroFattura();

	/**
	 * Sets the numero fattura of this cessione credito.
	 *
	 * @param numeroFattura the numero fattura of this cessione credito
	 */
	public void setNumeroFattura(int numeroFattura);

	/**
	 * Returns the totale of this cessione credito.
	 *
	 * @return the totale of this cessione credito
	 */
	public double getTotale();

	/**
	 * Sets the totale of this cessione credito.
	 *
	 * @param totale the totale of this cessione credito
	 */
	public void setTotale(double totale);

	/**
	 * Returns the note of this cessione credito.
	 *
	 * @return the note of this cessione credito
	 */
	@AutoEscape
	public String getNote();

	/**
	 * Sets the note of this cessione credito.
	 *
	 * @param note the note of this cessione credito
	 */
	public void setNote(String note);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(it.bysoftware.ct.model.CessioneCredito cessioneCredito);

	@Override
	public int hashCode();

	@Override
	public CacheModel<it.bysoftware.ct.model.CessioneCredito> toCacheModel();

	@Override
	public it.bysoftware.ct.model.CessioneCredito toEscapedModel();

	@Override
	public it.bysoftware.ct.model.CessioneCredito toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}