/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.bysoftware.ct.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the CuraTrasporto service. Represents a row in the &quot;CuraTrasporto&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link it.bysoftware.ct.model.impl.CuraTrasportoModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link it.bysoftware.ct.model.impl.CuraTrasportoImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CuraTrasporto
 * @see it.bysoftware.ct.model.impl.CuraTrasportoImpl
 * @see it.bysoftware.ct.model.impl.CuraTrasportoModelImpl
 * @generated
 */
public interface CuraTrasportoModel extends BaseModel<CuraTrasporto> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a cura trasporto model instance should use the {@link CuraTrasporto} interface instead.
	 */

	/**
	 * Returns the primary key of this cura trasporto.
	 *
	 * @return the primary key of this cura trasporto
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this cura trasporto.
	 *
	 * @param primaryKey the primary key of this cura trasporto
	 */
	public void setPrimaryKey(String primaryKey);

	/**
	 * Returns the codice cura trasporto of this cura trasporto.
	 *
	 * @return the codice cura trasporto of this cura trasporto
	 */
	@AutoEscape
	public String getCodiceCuraTrasporto();

	/**
	 * Sets the codice cura trasporto of this cura trasporto.
	 *
	 * @param codiceCuraTrasporto the codice cura trasporto of this cura trasporto
	 */
	public void setCodiceCuraTrasporto(String codiceCuraTrasporto);

	/**
	 * Returns the descrizione of this cura trasporto.
	 *
	 * @return the descrizione of this cura trasporto
	 */
	@AutoEscape
	public String getDescrizione();

	/**
	 * Sets the descrizione of this cura trasporto.
	 *
	 * @param descrizione the descrizione of this cura trasporto
	 */
	public void setDescrizione(String descrizione);

	/**
	 * Returns the codice azienda of this cura trasporto.
	 *
	 * @return the codice azienda of this cura trasporto
	 */
	@AutoEscape
	public String getCodiceAzienda();

	/**
	 * Sets the codice azienda of this cura trasporto.
	 *
	 * @param codiceAzienda the codice azienda of this cura trasporto
	 */
	public void setCodiceAzienda(String codiceAzienda);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(CuraTrasporto curaTrasporto);

	@Override
	public int hashCode();

	@Override
	public CacheModel<CuraTrasporto> toCacheModel();

	@Override
	public CuraTrasporto toEscapedModel();

	@Override
	public CuraTrasporto toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}