/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.bysoftware.ct.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the DescrizioniDocumenti service. Represents a row in the &quot;DescrizioniDocumenti&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link it.bysoftware.ct.model.impl.DescrizioniDocumentiModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link it.bysoftware.ct.model.impl.DescrizioniDocumentiImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see DescrizioniDocumenti
 * @see it.bysoftware.ct.model.impl.DescrizioniDocumentiImpl
 * @see it.bysoftware.ct.model.impl.DescrizioniDocumentiModelImpl
 * @generated
 */
public interface DescrizioniDocumentiModel extends BaseModel<DescrizioniDocumenti> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a descrizioni documenti model instance should use the {@link DescrizioniDocumenti} interface instead.
	 */

	/**
	 * Returns the primary key of this descrizioni documenti.
	 *
	 * @return the primary key of this descrizioni documenti
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this descrizioni documenti.
	 *
	 * @param primaryKey the primary key of this descrizioni documenti
	 */
	public void setPrimaryKey(String primaryKey);

	/**
	 * Returns the codice descrizione of this descrizioni documenti.
	 *
	 * @return the codice descrizione of this descrizioni documenti
	 */
	@AutoEscape
	public String getCodiceDescrizione();

	/**
	 * Sets the codice descrizione of this descrizioni documenti.
	 *
	 * @param codiceDescrizione the codice descrizione of this descrizioni documenti
	 */
	public void setCodiceDescrizione(String codiceDescrizione);

	/**
	 * Returns the codice i v a of this descrizioni documenti.
	 *
	 * @return the codice i v a of this descrizioni documenti
	 */
	@AutoEscape
	public String getCodiceIVA();

	/**
	 * Sets the codice i v a of this descrizioni documenti.
	 *
	 * @param codiceIVA the codice i v a of this descrizioni documenti
	 */
	public void setCodiceIVA(String codiceIVA);

	/**
	 * Returns the descrizione of this descrizioni documenti.
	 *
	 * @return the descrizione of this descrizioni documenti
	 */
	@AutoEscape
	public String getDescrizione();

	/**
	 * Sets the descrizione of this descrizioni documenti.
	 *
	 * @param descrizione the descrizione of this descrizioni documenti
	 */
	public void setDescrizione(String descrizione);

	/**
	 * Returns the descrizione fiscale of this descrizioni documenti.
	 *
	 * @return the descrizione fiscale of this descrizioni documenti
	 */
	@AutoEscape
	public String getDescrizioneFiscale();

	/**
	 * Sets the descrizione fiscale of this descrizioni documenti.
	 *
	 * @param descrizioneFiscale the descrizione fiscale of this descrizioni documenti
	 */
	public void setDescrizioneFiscale(String descrizioneFiscale);

	/**
	 * Returns the codice azienda of this descrizioni documenti.
	 *
	 * @return the codice azienda of this descrizioni documenti
	 */
	@AutoEscape
	public String getCodiceAzienda();

	/**
	 * Sets the codice azienda of this descrizioni documenti.
	 *
	 * @param codiceAzienda the codice azienda of this descrizioni documenti
	 */
	public void setCodiceAzienda(String codiceAzienda);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		it.bysoftware.ct.model.DescrizioniDocumenti descrizioniDocumenti);

	@Override
	public int hashCode();

	@Override
	public CacheModel<it.bysoftware.ct.model.DescrizioniDocumenti> toCacheModel();

	@Override
	public it.bysoftware.ct.model.DescrizioniDocumenti toEscapedModel();

	@Override
	public it.bysoftware.ct.model.DescrizioniDocumenti toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}