/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.bysoftware.ct.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the DescrizioniVarianti service. Represents a row in the &quot;DescrizioniVarianti&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link it.bysoftware.ct.model.impl.DescrizioniVariantiModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link it.bysoftware.ct.model.impl.DescrizioniVariantiImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see DescrizioniVarianti
 * @see it.bysoftware.ct.model.impl.DescrizioniVariantiImpl
 * @see it.bysoftware.ct.model.impl.DescrizioniVariantiModelImpl
 * @generated
 */
public interface DescrizioniVariantiModel extends BaseModel<DescrizioniVarianti> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a descrizioni varianti model instance should use the {@link DescrizioniVarianti} interface instead.
	 */

	/**
	 * Returns the primary key of this descrizioni varianti.
	 *
	 * @return the primary key of this descrizioni varianti
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this descrizioni varianti.
	 *
	 * @param primaryKey the primary key of this descrizioni varianti
	 */
	public void setPrimaryKey(String primaryKey);

	/**
	 * Returns the codice variante of this descrizioni varianti.
	 *
	 * @return the codice variante of this descrizioni varianti
	 */
	@AutoEscape
	public String getCodiceVariante();

	/**
	 * Sets the codice variante of this descrizioni varianti.
	 *
	 * @param codiceVariante the codice variante of this descrizioni varianti
	 */
	public void setCodiceVariante(String codiceVariante);

	/**
	 * Returns the descrizione variante of this descrizioni varianti.
	 *
	 * @return the descrizione variante of this descrizioni varianti
	 */
	@AutoEscape
	public String getDescrizioneVariante();

	/**
	 * Sets the descrizione variante of this descrizioni varianti.
	 *
	 * @param descrizioneVariante the descrizione variante of this descrizioni varianti
	 */
	public void setDescrizioneVariante(String descrizioneVariante);

	/**
	 * Returns the ordine of this descrizioni varianti.
	 *
	 * @return the ordine of this descrizioni varianti
	 */
	public int getOrdine();

	/**
	 * Sets the ordine of this descrizioni varianti.
	 *
	 * @param ordine the ordine of this descrizioni varianti
	 */
	public void setOrdine(int ordine);

	/**
	 * Returns the tipo variante of this descrizioni varianti.
	 *
	 * @return the tipo variante of this descrizioni varianti
	 */
	@AutoEscape
	public String getTipoVariante();

	/**
	 * Sets the tipo variante of this descrizioni varianti.
	 *
	 * @param tipoVariante the tipo variante of this descrizioni varianti
	 */
	public void setTipoVariante(String tipoVariante);

	/**
	 * Returns the codice azienda of this descrizioni varianti.
	 *
	 * @return the codice azienda of this descrizioni varianti
	 */
	@AutoEscape
	public String getCodiceAzienda();

	/**
	 * Sets the codice azienda of this descrizioni varianti.
	 *
	 * @param codiceAzienda the codice azienda of this descrizioni varianti
	 */
	public void setCodiceAzienda(String codiceAzienda);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		it.bysoftware.ct.model.DescrizioniVarianti descrizioniVarianti);

	@Override
	public int hashCode();

	@Override
	public CacheModel<it.bysoftware.ct.model.DescrizioniVarianti> toCacheModel();

	@Override
	public it.bysoftware.ct.model.DescrizioniVarianti toEscapedModel();

	@Override
	public it.bysoftware.ct.model.DescrizioniVarianti toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}