/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.bysoftware.ct.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the DestinatariDiversi service. Represents a row in the &quot;DestinatariDiversi&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link it.bysoftware.ct.model.impl.DestinatariDiversiModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link it.bysoftware.ct.model.impl.DestinatariDiversiImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see DestinatariDiversi
 * @see it.bysoftware.ct.model.impl.DestinatariDiversiImpl
 * @see it.bysoftware.ct.model.impl.DestinatariDiversiModelImpl
 * @generated
 */
public interface DestinatariDiversiModel extends BaseModel<DestinatariDiversi> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a destinatari diversi model instance should use the {@link DestinatariDiversi} interface instead.
	 */

	/**
	 * Returns the primary key of this destinatari diversi.
	 *
	 * @return the primary key of this destinatari diversi
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this destinatari diversi.
	 *
	 * @param primaryKey the primary key of this destinatari diversi
	 */
	public void setPrimaryKey(String primaryKey);

	/**
	 * Returns the codice anagrafica of this destinatari diversi.
	 *
	 * @return the codice anagrafica of this destinatari diversi
	 */
	@AutoEscape
	public String getCodiceAnagrafica();

	/**
	 * Sets the codice anagrafica of this destinatari diversi.
	 *
	 * @param codiceAnagrafica the codice anagrafica of this destinatari diversi
	 */
	public void setCodiceAnagrafica(String codiceAnagrafica);

	/**
	 * Returns the codice riferimento of this destinatari diversi.
	 *
	 * @return the codice riferimento of this destinatari diversi
	 */
	@AutoEscape
	public String getCodiceRiferimento();

	/**
	 * Sets the codice riferimento of this destinatari diversi.
	 *
	 * @param codiceRiferimento the codice riferimento of this destinatari diversi
	 */
	public void setCodiceRiferimento(String codiceRiferimento);

	/**
	 * Returns the c a p of this destinatari diversi.
	 *
	 * @return the c a p of this destinatari diversi
	 */
	@AutoEscape
	public String getCAP();

	/**
	 * Sets the c a p of this destinatari diversi.
	 *
	 * @param CAP the c a p of this destinatari diversi
	 */
	public void setCAP(String CAP);

	/**
	 * Returns the comune of this destinatari diversi.
	 *
	 * @return the comune of this destinatari diversi
	 */
	@AutoEscape
	public String getComune();

	/**
	 * Sets the comune of this destinatari diversi.
	 *
	 * @param comune the comune of this destinatari diversi
	 */
	public void setComune(String comune);

	/**
	 * Returns the indirizzo of this destinatari diversi.
	 *
	 * @return the indirizzo of this destinatari diversi
	 */
	@AutoEscape
	public String getIndirizzo();

	/**
	 * Sets the indirizzo of this destinatari diversi.
	 *
	 * @param indirizzo the indirizzo of this destinatari diversi
	 */
	public void setIndirizzo(String indirizzo);

	/**
	 * Returns the provincia of this destinatari diversi.
	 *
	 * @return the provincia of this destinatari diversi
	 */
	@AutoEscape
	public String getProvincia();

	/**
	 * Sets the provincia of this destinatari diversi.
	 *
	 * @param provincia the provincia of this destinatari diversi
	 */
	public void setProvincia(String provincia);

	/**
	 * Returns the stato of this destinatari diversi.
	 *
	 * @return the stato of this destinatari diversi
	 */
	@AutoEscape
	public String getStato();

	/**
	 * Sets the stato of this destinatari diversi.
	 *
	 * @param stato the stato of this destinatari diversi
	 */
	public void setStato(String stato);

	/**
	 * Returns the tipo anagrafica of this destinatari diversi.
	 *
	 * @return the tipo anagrafica of this destinatari diversi
	 */
	@AutoEscape
	public String getTipoAnagrafica();

	/**
	 * Sets the tipo anagrafica of this destinatari diversi.
	 *
	 * @param tipoAnagrafica the tipo anagrafica of this destinatari diversi
	 */
	public void setTipoAnagrafica(String tipoAnagrafica);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(DestinatariDiversi destinatariDiversi);

	@Override
	public int hashCode();

	@Override
	public CacheModel<DestinatariDiversi> toCacheModel();

	@Override
	public DestinatariDiversi toEscapedModel();

	@Override
	public DestinatariDiversi toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}