/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.bysoftware.ct.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the FileUploader service. Represents a row in the &quot;fileuploader&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link it.bysoftware.ct.model.impl.FileUploaderModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link it.bysoftware.ct.model.impl.FileUploaderImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see FileUploader
 * @see it.bysoftware.ct.model.impl.FileUploaderImpl
 * @see it.bysoftware.ct.model.impl.FileUploaderModelImpl
 * @generated
 */
public interface FileUploaderModel extends BaseModel<FileUploader> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a file uploader model instance should use the {@link FileUploader} interface instead.
	 */

	/**
	 * Returns the primary key of this file uploader.
	 *
	 * @return the primary key of this file uploader
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this file uploader.
	 *
	 * @param primaryKey the primary key of this file uploader
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the fid of this file uploader.
	 *
	 * @return the fid of this file uploader
	 */
	public long getFid();

	/**
	 * Sets the fid of this file uploader.
	 *
	 * @param fid the fid of this file uploader
	 */
	public void setFid(long fid);

	/**
	 * Returns the content of this file uploader.
	 *
	 * @return the content of this file uploader
	 */
	@AutoEscape
	public String getContent();

	/**
	 * Sets the content of this file uploader.
	 *
	 * @param content the content of this file uploader
	 */
	public void setContent(String content);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(it.bysoftware.ct.model.FileUploader fileUploader);

	@Override
	public int hashCode();

	@Override
	public CacheModel<it.bysoftware.ct.model.FileUploader> toCacheModel();

	@Override
	public it.bysoftware.ct.model.FileUploader toEscapedModel();

	@Override
	public it.bysoftware.ct.model.FileUploader toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}