/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.bysoftware.ct.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the OrganizzazioneProduttori service. Represents a row in the &quot;op&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link it.bysoftware.ct.model.impl.OrganizzazioneProduttoriModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link it.bysoftware.ct.model.impl.OrganizzazioneProduttoriImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see OrganizzazioneProduttori
 * @see it.bysoftware.ct.model.impl.OrganizzazioneProduttoriImpl
 * @see it.bysoftware.ct.model.impl.OrganizzazioneProduttoriModelImpl
 * @generated
 */
public interface OrganizzazioneProduttoriModel extends BaseModel<OrganizzazioneProduttori> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a organizzazione produttori model instance should use the {@link OrganizzazioneProduttori} interface instead.
	 */

	/**
	 * Returns the primary key of this organizzazione produttori.
	 *
	 * @return the primary key of this organizzazione produttori
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this organizzazione produttori.
	 *
	 * @param primaryKey the primary key of this organizzazione produttori
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this organizzazione produttori.
	 *
	 * @return the ID of this organizzazione produttori
	 */
	public long getId();

	/**
	 * Sets the ID of this organizzazione produttori.
	 *
	 * @param id the ID of this organizzazione produttori
	 */
	public void setId(long id);

	/**
	 * Returns the ragione sociale of this organizzazione produttori.
	 *
	 * @return the ragione sociale of this organizzazione produttori
	 */
	@AutoEscape
	public String getRagioneSociale();

	/**
	 * Sets the ragione sociale of this organizzazione produttori.
	 *
	 * @param ragioneSociale the ragione sociale of this organizzazione produttori
	 */
	public void setRagioneSociale(String ragioneSociale);

	/**
	 * Returns the partita i v a of this organizzazione produttori.
	 *
	 * @return the partita i v a of this organizzazione produttori
	 */
	@AutoEscape
	public String getPartitaIVA();

	/**
	 * Sets the partita i v a of this organizzazione produttori.
	 *
	 * @param partitaIVA the partita i v a of this organizzazione produttori
	 */
	public void setPartitaIVA(String partitaIVA);

	/**
	 * Returns the indirizzo of this organizzazione produttori.
	 *
	 * @return the indirizzo of this organizzazione produttori
	 */
	@AutoEscape
	public String getIndirizzo();

	/**
	 * Sets the indirizzo of this organizzazione produttori.
	 *
	 * @param indirizzo the indirizzo of this organizzazione produttori
	 */
	public void setIndirizzo(String indirizzo);

	/**
	 * Returns the telefono of this organizzazione produttori.
	 *
	 * @return the telefono of this organizzazione produttori
	 */
	@AutoEscape
	public String getTelefono();

	/**
	 * Sets the telefono of this organizzazione produttori.
	 *
	 * @param telefono the telefono of this organizzazione produttori
	 */
	public void setTelefono(String telefono);

	/**
	 * Returns the fax of this organizzazione produttori.
	 *
	 * @return the fax of this organizzazione produttori
	 */
	@AutoEscape
	public String getFax();

	/**
	 * Sets the fax of this organizzazione produttori.
	 *
	 * @param fax the fax of this organizzazione produttori
	 */
	public void setFax(String fax);

	/**
	 * Returns the sito web of this organizzazione produttori.
	 *
	 * @return the sito web of this organizzazione produttori
	 */
	@AutoEscape
	public String getSitoWeb();

	/**
	 * Sets the sito web of this organizzazione produttori.
	 *
	 * @param sitoWeb the sito web of this organizzazione produttori
	 */
	public void setSitoWeb(String sitoWeb);

	/**
	 * Returns the email of this organizzazione produttori.
	 *
	 * @return the email of this organizzazione produttori
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this organizzazione produttori.
	 *
	 * @param email the email of this organizzazione produttori
	 */
	public void setEmail(String email);

	/**
	 * Returns the password of this organizzazione produttori.
	 *
	 * @return the password of this organizzazione produttori
	 */
	@AutoEscape
	public String getPassword();

	/**
	 * Sets the password of this organizzazione produttori.
	 *
	 * @param password the password of this organizzazione produttori
	 */
	public void setPassword(String password);

	/**
	 * Returns the id liferay of this organizzazione produttori.
	 *
	 * @return the id liferay of this organizzazione produttori
	 */
	public long getIdLiferay();

	/**
	 * Sets the id liferay of this organizzazione produttori.
	 *
	 * @param idLiferay the id liferay of this organizzazione produttori
	 */
	public void setIdLiferay(long idLiferay);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(OrganizzazioneProduttori organizzazioneProduttori);

	@Override
	public int hashCode();

	@Override
	public CacheModel<OrganizzazioneProduttori> toCacheModel();

	@Override
	public OrganizzazioneProduttori toEscapedModel();

	@Override
	public OrganizzazioneProduttori toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}