/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.bysoftware.ct.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Porto service. Represents a row in the &quot;Porto&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link it.bysoftware.ct.model.impl.PortoModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link it.bysoftware.ct.model.impl.PortoImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Porto
 * @see it.bysoftware.ct.model.impl.PortoImpl
 * @see it.bysoftware.ct.model.impl.PortoModelImpl
 * @generated
 */
public interface PortoModel extends BaseModel<Porto> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a porto model instance should use the {@link Porto} interface instead.
	 */

	/**
	 * Returns the primary key of this porto.
	 *
	 * @return the primary key of this porto
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this porto.
	 *
	 * @param primaryKey the primary key of this porto
	 */
	public void setPrimaryKey(String primaryKey);

	/**
	 * Returns the cdinco of this porto.
	 *
	 * @return the cdinco of this porto
	 */
	@AutoEscape
	public String getCdinco();

	/**
	 * Sets the cdinco of this porto.
	 *
	 * @param Cdinco the cdinco of this porto
	 */
	public void setCdinco(String Cdinco);

	/**
	 * Returns the codice porto of this porto.
	 *
	 * @return the codice porto of this porto
	 */
	@AutoEscape
	public String getCodicePorto();

	/**
	 * Sets the codice porto of this porto.
	 *
	 * @param codicePorto the codice porto of this porto
	 */
	public void setCodicePorto(String codicePorto);

	/**
	 * Returns the descrizione of this porto.
	 *
	 * @return the descrizione of this porto
	 */
	@AutoEscape
	public String getDescrizione();

	/**
	 * Sets the descrizione of this porto.
	 *
	 * @param descrizione the descrizione of this porto
	 */
	public void setDescrizione(String descrizione);

	/**
	 * Returns the incoterm of this porto.
	 *
	 * @return the incoterm of this porto
	 */
	@AutoEscape
	public String getIncoterm();

	/**
	 * Sets the incoterm of this porto.
	 *
	 * @param Incoterm the incoterm of this porto
	 */
	public void setIncoterm(String Incoterm);

	/**
	 * Returns the codice azienda of this porto.
	 *
	 * @return the codice azienda of this porto
	 */
	@AutoEscape
	public String getCodiceAzienda();

	/**
	 * Sets the codice azienda of this porto.
	 *
	 * @param codiceAzienda the codice azienda of this porto
	 */
	public void setCodiceAzienda(String codiceAzienda);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(it.bysoftware.ct.model.Porto porto);

	@Override
	public int hashCode();

	@Override
	public CacheModel<it.bysoftware.ct.model.Porto> toCacheModel();

	@Override
	public it.bysoftware.ct.model.Porto toEscapedModel();

	@Override
	public it.bysoftware.ct.model.Porto toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}