/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.bysoftware.ct.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the TracciabilitaGrezzi service. Represents a row in the &quot;TracciabilitaGrezzi&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link it.bysoftware.ct.model.impl.TracciabilitaGrezziModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link it.bysoftware.ct.model.impl.TracciabilitaGrezziImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TracciabilitaGrezzi
 * @see it.bysoftware.ct.model.impl.TracciabilitaGrezziImpl
 * @see it.bysoftware.ct.model.impl.TracciabilitaGrezziModelImpl
 * @generated
 */
public interface TracciabilitaGrezziModel extends BaseModel<TracciabilitaGrezzi> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a tracciabilita grezzi model instance should use the {@link TracciabilitaGrezzi} interface instead.
	 */

	/**
	 * Returns the primary key of this tracciabilita grezzi.
	 *
	 * @return the primary key of this tracciabilita grezzi
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this tracciabilita grezzi.
	 *
	 * @param primaryKey the primary key of this tracciabilita grezzi
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this tracciabilita grezzi.
	 *
	 * @return the ID of this tracciabilita grezzi
	 */
	public long getId();

	/**
	 * Sets the ID of this tracciabilita grezzi.
	 *
	 * @param id the ID of this tracciabilita grezzi
	 */
	public void setId(long id);

	/**
	 * Returns the lotto grezzo of this tracciabilita grezzi.
	 *
	 * @return the lotto grezzo of this tracciabilita grezzi
	 */
	@AutoEscape
	public String getLottoGrezzo();

	/**
	 * Sets the lotto grezzo of this tracciabilita grezzi.
	 *
	 * @param lottoGrezzo the lotto grezzo of this tracciabilita grezzi
	 */
	public void setLottoGrezzo(String lottoGrezzo);

	/**
	 * Returns the prodotto of this tracciabilita grezzi.
	 *
	 * @return the prodotto of this tracciabilita grezzi
	 */
	@AutoEscape
	public String getProdotto();

	/**
	 * Sets the prodotto of this tracciabilita grezzi.
	 *
	 * @param prodotto the prodotto of this tracciabilita grezzi
	 */
	public void setProdotto(String prodotto);

	/**
	 * Returns the kg of this tracciabilita grezzi.
	 *
	 * @return the kg of this tracciabilita grezzi
	 */
	public double getKg();

	/**
	 * Sets the kg of this tracciabilita grezzi.
	 *
	 * @param kg the kg of this tracciabilita grezzi
	 */
	public void setKg(double kg);

	/**
	 * Returns the produttore of this tracciabilita grezzi.
	 *
	 * @return the produttore of this tracciabilita grezzi
	 */
	@AutoEscape
	public String getProduttore();

	/**
	 * Sets the produttore of this tracciabilita grezzi.
	 *
	 * @param produttore the produttore of this tracciabilita grezzi
	 */
	public void setProduttore(String produttore);

	/**
	 * Returns the foglio of this tracciabilita grezzi.
	 *
	 * @return the foglio of this tracciabilita grezzi
	 */
	public int getFoglio();

	/**
	 * Sets the foglio of this tracciabilita grezzi.
	 *
	 * @param foglio the foglio of this tracciabilita grezzi
	 */
	public void setFoglio(int foglio);

	/**
	 * Returns the particella of this tracciabilita grezzi.
	 *
	 * @return the particella of this tracciabilita grezzi
	 */
	public int getParticella();

	/**
	 * Sets the particella of this tracciabilita grezzi.
	 *
	 * @param particella the particella of this tracciabilita grezzi
	 */
	public void setParticella(int particella);

	/**
	 * Returns the note of this tracciabilita grezzi.
	 *
	 * @return the note of this tracciabilita grezzi
	 */
	@AutoEscape
	public String getNote();

	/**
	 * Sets the note of this tracciabilita grezzi.
	 *
	 * @param note the note of this tracciabilita grezzi
	 */
	public void setNote(String note);

	/**
	 * Returns the numero colli of this tracciabilita grezzi.
	 *
	 * @return the numero colli of this tracciabilita grezzi
	 */
	public int getNumeroColli();

	/**
	 * Sets the numero colli of this tracciabilita grezzi.
	 *
	 * @param numeroColli the numero colli of this tracciabilita grezzi
	 */
	public void setNumeroColli(int numeroColli);

	/**
	 * Returns the kg scarto of this tracciabilita grezzi.
	 *
	 * @return the kg scarto of this tracciabilita grezzi
	 */
	public double getKgScarto();

	/**
	 * Sets the kg scarto of this tracciabilita grezzi.
	 *
	 * @param kgScarto the kg scarto of this tracciabilita grezzi
	 */
	public void setKgScarto(double kgScarto);

	/**
	 * Returns the id scheda tracciabilta of this tracciabilita grezzi.
	 *
	 * @return the id scheda tracciabilta of this tracciabilita grezzi
	 */
	public long getIdSchedaTracciabilta();

	/**
	 * Sets the id scheda tracciabilta of this tracciabilita grezzi.
	 *
	 * @param idSchedaTracciabilta the id scheda tracciabilta of this tracciabilita grezzi
	 */
	public void setIdSchedaTracciabilta(long idSchedaTracciabilta);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		it.bysoftware.ct.model.TracciabilitaGrezzi tracciabilitaGrezzi);

	@Override
	public int hashCode();

	@Override
	public CacheModel<it.bysoftware.ct.model.TracciabilitaGrezzi> toCacheModel();

	@Override
	public it.bysoftware.ct.model.TracciabilitaGrezzi toEscapedModel();

	@Override
	public it.bysoftware.ct.model.TracciabilitaGrezzi toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}