/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.bysoftware.ct.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the TracciabilitaScheda service. Represents a row in the &quot;tracciabilitaScheda&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link it.bysoftware.ct.model.impl.TracciabilitaSchedaModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link it.bysoftware.ct.model.impl.TracciabilitaSchedaImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TracciabilitaScheda
 * @see it.bysoftware.ct.model.impl.TracciabilitaSchedaImpl
 * @see it.bysoftware.ct.model.impl.TracciabilitaSchedaModelImpl
 * @generated
 */
public interface TracciabilitaSchedaModel extends BaseModel<TracciabilitaScheda> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a tracciabilita scheda model instance should use the {@link TracciabilitaScheda} interface instead.
	 */

	/**
	 * Returns the primary key of this tracciabilita scheda.
	 *
	 * @return the primary key of this tracciabilita scheda
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this tracciabilita scheda.
	 *
	 * @param primaryKey the primary key of this tracciabilita scheda
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this tracciabilita scheda.
	 *
	 * @return the ID of this tracciabilita scheda
	 */
	public long getId();

	/**
	 * Sets the ID of this tracciabilita scheda.
	 *
	 * @param id the ID of this tracciabilita scheda
	 */
	public void setId(long id);

	/**
	 * Returns the codice prodotto of this tracciabilita scheda.
	 *
	 * @return the codice prodotto of this tracciabilita scheda
	 */
	@AutoEscape
	public String getCodiceProdotto();

	/**
	 * Sets the codice prodotto of this tracciabilita scheda.
	 *
	 * @param codiceProdotto the codice prodotto of this tracciabilita scheda
	 */
	public void setCodiceProdotto(String codiceProdotto);

	/**
	 * Returns the prodotto venduto of this tracciabilita scheda.
	 *
	 * @return the prodotto venduto of this tracciabilita scheda
	 */
	@AutoEscape
	public String getProdottoVenduto();

	/**
	 * Sets the prodotto venduto of this tracciabilita scheda.
	 *
	 * @param prodottoVenduto the prodotto venduto of this tracciabilita scheda
	 */
	public void setProdottoVenduto(String prodottoVenduto);

	/**
	 * Returns the kg venduti of this tracciabilita scheda.
	 *
	 * @return the kg venduti of this tracciabilita scheda
	 */
	public double getKgVenduti();

	/**
	 * Sets the kg venduti of this tracciabilita scheda.
	 *
	 * @param kgVenduti the kg venduti of this tracciabilita scheda
	 */
	public void setKgVenduti(double kgVenduti);

	/**
	 * Returns the lotto vendita of this tracciabilita scheda.
	 *
	 * @return the lotto vendita of this tracciabilita scheda
	 */
	@AutoEscape
	public String getLottoVendita();

	/**
	 * Sets the lotto vendita of this tracciabilita scheda.
	 *
	 * @param lottoVendita the lotto vendita of this tracciabilita scheda
	 */
	public void setLottoVendita(String lottoVendita);

	/**
	 * Returns the anno of this tracciabilita scheda.
	 *
	 * @return the anno of this tracciabilita scheda
	 */
	public int getAnno();

	/**
	 * Sets the anno of this tracciabilita scheda.
	 *
	 * @param anno the anno of this tracciabilita scheda
	 */
	public void setAnno(int anno);

	/**
	 * Returns the numero documento of this tracciabilita scheda.
	 *
	 * @return the numero documento of this tracciabilita scheda
	 */
	public long getNumeroDocumento();

	/**
	 * Sets the numero documento of this tracciabilita scheda.
	 *
	 * @param numeroDocumento the numero documento of this tracciabilita scheda
	 */
	public void setNumeroDocumento(long numeroDocumento);

	/**
	 * Returns the rigo ordine of this tracciabilita scheda.
	 *
	 * @return the rigo ordine of this tracciabilita scheda
	 */
	public int getRigoOrdine();

	/**
	 * Sets the rigo ordine of this tracciabilita scheda.
	 *
	 * @param rigoOrdine the rigo ordine of this tracciabilita scheda
	 */
	public void setRigoOrdine(int rigoOrdine);

	/**
	 * Returns the tipo documento of this tracciabilita scheda.
	 *
	 * @return the tipo documento of this tracciabilita scheda
	 */
	@AutoEscape
	public String getTipoDocumento();

	/**
	 * Sets the tipo documento of this tracciabilita scheda.
	 *
	 * @param tipoDocumento the tipo documento of this tracciabilita scheda
	 */
	public void setTipoDocumento(String tipoDocumento);

	/**
	 * Returns the id associato of this tracciabilita scheda.
	 *
	 * @return the id associato of this tracciabilita scheda
	 */
	public long getIdAssociato();

	/**
	 * Sets the id associato of this tracciabilita scheda.
	 *
	 * @param idAssociato the id associato of this tracciabilita scheda
	 */
	public void setIdAssociato(long idAssociato);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		it.bysoftware.ct.model.TracciabilitaScheda tracciabilitaScheda);

	@Override
	public int hashCode();

	@Override
	public CacheModel<it.bysoftware.ct.model.TracciabilitaScheda> toCacheModel();

	@Override
	public it.bysoftware.ct.model.TracciabilitaScheda toEscapedModel();

	@Override
	public it.bysoftware.ct.model.TracciabilitaScheda toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}