/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.bysoftware.ct.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Vettori service. Represents a row in the &quot;Vettori&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link it.bysoftware.ct.model.impl.VettoriModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link it.bysoftware.ct.model.impl.VettoriImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Vettori
 * @see it.bysoftware.ct.model.impl.VettoriImpl
 * @see it.bysoftware.ct.model.impl.VettoriModelImpl
 * @generated
 */
public interface VettoriModel extends BaseModel<Vettori> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a vettori model instance should use the {@link Vettori} interface instead.
	 */

	/**
	 * Returns the primary key of this vettori.
	 *
	 * @return the primary key of this vettori
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this vettori.
	 *
	 * @param primaryKey the primary key of this vettori
	 */
	public void setPrimaryKey(String primaryKey);

	/**
	 * Returns the albo of this vettori.
	 *
	 * @return the albo of this vettori
	 */
	@AutoEscape
	public String getAlbo();

	/**
	 * Sets the albo of this vettori.
	 *
	 * @param albo the albo of this vettori
	 */
	public void setAlbo(String albo);

	/**
	 * Returns the c a p of this vettori.
	 *
	 * @return the c a p of this vettori
	 */
	@AutoEscape
	public String getCAP();

	/**
	 * Sets the c a p of this vettori.
	 *
	 * @param CAP the c a p of this vettori
	 */
	public void setCAP(String CAP);

	/**
	 * Returns the codice vettore of this vettori.
	 *
	 * @return the codice vettore of this vettori
	 */
	@AutoEscape
	public String getCodiceVettore();

	/**
	 * Sets the codice vettore of this vettori.
	 *
	 * @param codiceVettore the codice vettore of this vettori
	 */
	public void setCodiceVettore(String codiceVettore);

	/**
	 * Returns the codice fiscale of this vettori.
	 *
	 * @return the codice fiscale of this vettori
	 */
	@AutoEscape
	public String getCodiceFiscale();

	/**
	 * Sets the codice fiscale of this vettori.
	 *
	 * @param codiceFiscale the codice fiscale of this vettori
	 */
	public void setCodiceFiscale(String codiceFiscale);

	/**
	 * Returns the codice riferimento of this vettori.
	 *
	 * @return the codice riferimento of this vettori
	 */
	@AutoEscape
	public String getCodiceRiferimento();

	/**
	 * Sets the codice riferimento of this vettori.
	 *
	 * @param codiceRiferimento the codice riferimento of this vettori
	 */
	public void setCodiceRiferimento(String codiceRiferimento);

	/**
	 * Returns the comune of this vettori.
	 *
	 * @return the comune of this vettori
	 */
	@AutoEscape
	public String getComune();

	/**
	 * Sets the comune of this vettori.
	 *
	 * @param comune the comune of this vettori
	 */
	public void setComune(String comune);

	/**
	 * Returns the indirizzo of this vettori.
	 *
	 * @return the indirizzo of this vettori
	 */
	@AutoEscape
	public String getIndirizzo();

	/**
	 * Sets the indirizzo of this vettori.
	 *
	 * @param indirizzo the indirizzo of this vettori
	 */
	public void setIndirizzo(String indirizzo);

	/**
	 * Returns the note of this vettori.
	 *
	 * @return the note of this vettori
	 */
	@AutoEscape
	public String getNote();

	/**
	 * Sets the note of this vettori.
	 *
	 * @param note the note of this vettori
	 */
	public void setNote(String note);

	/**
	 * Returns the partita i v a of this vettori.
	 *
	 * @return the partita i v a of this vettori
	 */
	@AutoEscape
	public String getPartitaIVA();

	/**
	 * Sets the partita i v a of this vettori.
	 *
	 * @param partitaIVA the partita i v a of this vettori
	 */
	public void setPartitaIVA(String partitaIVA);

	/**
	 * Returns the ragione sociale of this vettori.
	 *
	 * @return the ragione sociale of this vettori
	 */
	@AutoEscape
	public String getRagioneSociale();

	/**
	 * Sets the ragione sociale of this vettori.
	 *
	 * @param ragioneSociale the ragione sociale of this vettori
	 */
	public void setRagioneSociale(String ragioneSociale);

	/**
	 * Returns the ragione sociale2 of this vettori.
	 *
	 * @return the ragione sociale2 of this vettori
	 */
	@AutoEscape
	public String getRagioneSociale2();

	/**
	 * Sets the ragione sociale2 of this vettori.
	 *
	 * @param ragioneSociale2 the ragione sociale2 of this vettori
	 */
	public void setRagioneSociale2(String ragioneSociale2);

	/**
	 * Returns the provincia of this vettori.
	 *
	 * @return the provincia of this vettori
	 */
	@AutoEscape
	public String getProvincia();

	/**
	 * Sets the provincia of this vettori.
	 *
	 * @param provincia the provincia of this vettori
	 */
	public void setProvincia(String provincia);

	/**
	 * Returns the stato of this vettori.
	 *
	 * @return the stato of this vettori
	 */
	@AutoEscape
	public String getStato();

	/**
	 * Sets the stato of this vettori.
	 *
	 * @param stato the stato of this vettori
	 */
	public void setStato(String stato);

	/**
	 * Returns the tipo anagrafica of this vettori.
	 *
	 * @return the tipo anagrafica of this vettori
	 */
	@AutoEscape
	public String getTipoAnagrafica();

	/**
	 * Sets the tipo anagrafica of this vettori.
	 *
	 * @param tipoAnagrafica the tipo anagrafica of this vettori
	 */
	public void setTipoAnagrafica(String tipoAnagrafica);

	/**
	 * Returns the codice azienda of this vettori.
	 *
	 * @return the codice azienda of this vettori
	 */
	@AutoEscape
	public String getCodiceAzienda();

	/**
	 * Sets the codice azienda of this vettori.
	 *
	 * @param codiceAzienda the codice azienda of this vettori
	 */
	public void setCodiceAzienda(String codiceAzienda);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Vettori vettori);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Vettori> toCacheModel();

	@Override
	public Vettori toEscapedModel();

	@Override
	public Vettori toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}