/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.bysoftware.ct.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the VociIva service. Represents a row in the &quot;VociIva&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link it.bysoftware.ct.model.impl.VociIvaModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link it.bysoftware.ct.model.impl.VociIvaImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see VociIva
 * @see it.bysoftware.ct.model.impl.VociIvaImpl
 * @see it.bysoftware.ct.model.impl.VociIvaModelImpl
 * @generated
 */
public interface VociIvaModel extends BaseModel<VociIva> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a voci iva model instance should use the {@link VociIva} interface instead.
	 */

	/**
	 * Returns the primary key of this voci iva.
	 *
	 * @return the primary key of this voci iva
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this voci iva.
	 *
	 * @param primaryKey the primary key of this voci iva
	 */
	public void setPrimaryKey(String primaryKey);

	/**
	 * Returns the codice iva of this voci iva.
	 *
	 * @return the codice iva of this voci iva
	 */
	@AutoEscape
	public String getCodiceIva();

	/**
	 * Sets the codice iva of this voci iva.
	 *
	 * @param codiceIva the codice iva of this voci iva
	 */
	public void setCodiceIva(String codiceIva);

	/**
	 * Returns the descrizione of this voci iva.
	 *
	 * @return the descrizione of this voci iva
	 */
	@AutoEscape
	public String getDescrizione();

	/**
	 * Sets the descrizione of this voci iva.
	 *
	 * @param descrizione the descrizione of this voci iva
	 */
	public void setDescrizione(String descrizione);

	/**
	 * Returns the descrizione documento of this voci iva.
	 *
	 * @return the descrizione documento of this voci iva
	 */
	@AutoEscape
	public String getDescrizioneDocumento();

	/**
	 * Sets the descrizione documento of this voci iva.
	 *
	 * @param descrizioneDocumento the descrizione documento of this voci iva
	 */
	public void setDescrizioneDocumento(String descrizioneDocumento);

	/**
	 * Returns the aliquota of this voci iva.
	 *
	 * @return the aliquota of this voci iva
	 */
	public double getAliquota();

	/**
	 * Sets the aliquota of this voci iva.
	 *
	 * @param aliquota the aliquota of this voci iva
	 */
	public void setAliquota(double aliquota);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(it.bysoftware.ct.model.VociIva vociIva);

	@Override
	public int hashCode();

	@Override
	public CacheModel<it.bysoftware.ct.model.VociIva> toCacheModel();

	@Override
	public it.bysoftware.ct.model.VociIva toEscapedModel();

	@Override
	public it.bysoftware.ct.model.VociIva toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}