/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.bysoftware.ct.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import it.bysoftware.ct.service.persistence.WKTestataDocumentoPK;

import java.io.Serializable;

/**
 * The base model interface for the WKTestataDocumento service. Represents a row in the &quot;WK_SSTESORD&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link it.bysoftware.ct.model.impl.WKTestataDocumentoModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link it.bysoftware.ct.model.impl.WKTestataDocumentoImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see WKTestataDocumento
 * @see it.bysoftware.ct.model.impl.WKTestataDocumentoImpl
 * @see it.bysoftware.ct.model.impl.WKTestataDocumentoModelImpl
 * @generated
 */
public interface WKTestataDocumentoModel extends BaseModel<WKTestataDocumento> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a w k testata documento model instance should use the {@link WKTestataDocumento} interface instead.
	 */

	/**
	 * Returns the primary key of this w k testata documento.
	 *
	 * @return the primary key of this w k testata documento
	 */
	public WKTestataDocumentoPK getPrimaryKey();

	/**
	 * Sets the primary key of this w k testata documento.
	 *
	 * @param primaryKey the primary key of this w k testata documento
	 */
	public void setPrimaryKey(WKTestataDocumentoPK primaryKey);

	/**
	 * Returns the anno of this w k testata documento.
	 *
	 * @return the anno of this w k testata documento
	 */
	public int getAnno();

	/**
	 * Sets the anno of this w k testata documento.
	 *
	 * @param anno the anno of this w k testata documento
	 */
	public void setAnno(int anno);

	/**
	 * Returns the numero ordine of this w k testata documento.
	 *
	 * @return the numero ordine of this w k testata documento
	 */
	public long getNumeroOrdine();

	/**
	 * Sets the numero ordine of this w k testata documento.
	 *
	 * @param numeroOrdine the numero ordine of this w k testata documento
	 */
	public void setNumeroOrdine(long numeroOrdine);

	/**
	 * Returns the codice soggetto of this w k testata documento.
	 *
	 * @return the codice soggetto of this w k testata documento
	 */
	@AutoEscape
	public String getCodiceSoggetto();

	/**
	 * Sets the codice soggetto of this w k testata documento.
	 *
	 * @param codiceSoggetto the codice soggetto of this w k testata documento
	 */
	public void setCodiceSoggetto(String codiceSoggetto);

	/**
	 * Returns the data ordine of this w k testata documento.
	 *
	 * @return the data ordine of this w k testata documento
	 */
	@AutoEscape
	public String getDataOrdine();

	/**
	 * Sets the data ordine of this w k testata documento.
	 *
	 * @param dataOrdine the data ordine of this w k testata documento
	 */
	public void setDataOrdine(String dataOrdine);

	/**
	 * Returns the data consegna of this w k testata documento.
	 *
	 * @return the data consegna of this w k testata documento
	 */
	@AutoEscape
	public String getDataConsegna();

	/**
	 * Sets the data consegna of this w k testata documento.
	 *
	 * @param dataConsegna the data consegna of this w k testata documento
	 */
	public void setDataConsegna(String dataConsegna);

	/**
	 * Returns the destinazione of this w k testata documento.
	 *
	 * @return the destinazione of this w k testata documento
	 */
	@AutoEscape
	public String getDestinazione();

	/**
	 * Sets the destinazione of this w k testata documento.
	 *
	 * @param destinazione the destinazione of this w k testata documento
	 */
	public void setDestinazione(String destinazione);

	/**
	 * Returns the codice destinazione of this w k testata documento.
	 *
	 * @return the codice destinazione of this w k testata documento
	 */
	@AutoEscape
	public String getCodiceDestinazione();

	/**
	 * Sets the codice destinazione of this w k testata documento.
	 *
	 * @param codiceDestinazione the codice destinazione of this w k testata documento
	 */
	public void setCodiceDestinazione(String codiceDestinazione);

	/**
	 * Returns the ragione sociale of this w k testata documento.
	 *
	 * @return the ragione sociale of this w k testata documento
	 */
	@AutoEscape
	public String getRagioneSociale();

	/**
	 * Sets the ragione sociale of this w k testata documento.
	 *
	 * @param ragioneSociale the ragione sociale of this w k testata documento
	 */
	public void setRagioneSociale(String ragioneSociale);

	/**
	 * Returns the completo of this w k testata documento.
	 *
	 * @return the completo of this w k testata documento
	 */
	@AutoEscape
	public String getCompleto();

	/**
	 * Sets the completo of this w k testata documento.
	 *
	 * @param completo the completo of this w k testata documento
	 */
	public void setCompleto(String completo);

	/**
	 * Returns the operatore of this w k testata documento.
	 *
	 * @return the operatore of this w k testata documento
	 */
	@AutoEscape
	public String getOperatore();

	/**
	 * Sets the operatore of this w k testata documento.
	 *
	 * @param operatore the operatore of this w k testata documento
	 */
	public void setOperatore(String operatore);

	/**
	 * Returns the visto of this w k testata documento.
	 *
	 * @return the visto of this w k testata documento
	 */
	public int getVisto();

	/**
	 * Sets the visto of this w k testata documento.
	 *
	 * @param visto the visto of this w k testata documento
	 */
	public void setVisto(int visto);

	/**
	 * Returns the inviato of this w k testata documento.
	 *
	 * @return the inviato of this w k testata documento
	 */
	public int getInviato();

	/**
	 * Sets the inviato of this w k testata documento.
	 *
	 * @param inviato the inviato of this w k testata documento
	 */
	public void setInviato(int inviato);

	/**
	 * Returns the lotto of this w k testata documento.
	 *
	 * @return the lotto of this w k testata documento
	 */
	@AutoEscape
	public String getLotto();

	/**
	 * Sets the lotto of this w k testata documento.
	 *
	 * @param lotto the lotto of this w k testata documento
	 */
	public void setLotto(String lotto);

	/**
	 * Returns the tipo documento of this w k testata documento.
	 *
	 * @return the tipo documento of this w k testata documento
	 */
	@AutoEscape
	public String getTipoDocumento();

	/**
	 * Sets the tipo documento of this w k testata documento.
	 *
	 * @param tipoDocumento the tipo documento of this w k testata documento
	 */
	public void setTipoDocumento(String tipoDocumento);

	/**
	 * Returns the vettore of this w k testata documento.
	 *
	 * @return the vettore of this w k testata documento
	 */
	@AutoEscape
	public String getVettore();

	/**
	 * Sets the vettore of this w k testata documento.
	 *
	 * @param vettore the vettore of this w k testata documento
	 */
	public void setVettore(String vettore);

	/**
	 * Returns the autista of this w k testata documento.
	 *
	 * @return the autista of this w k testata documento
	 */
	@AutoEscape
	public String getAutista();

	/**
	 * Sets the autista of this w k testata documento.
	 *
	 * @param autista the autista of this w k testata documento
	 */
	public void setAutista(String autista);

	/**
	 * Returns the telefono of this w k testata documento.
	 *
	 * @return the telefono of this w k testata documento
	 */
	@AutoEscape
	public String getTelefono();

	/**
	 * Sets the telefono of this w k testata documento.
	 *
	 * @param telefono the telefono of this w k testata documento
	 */
	public void setTelefono(String telefono);

	/**
	 * Returns the centro of this w k testata documento.
	 *
	 * @return the centro of this w k testata documento
	 */
	@AutoEscape
	public String getCentro();

	/**
	 * Sets the centro of this w k testata documento.
	 *
	 * @param centro the centro of this w k testata documento
	 */
	public void setCentro(String centro);

	/**
	 * Returns the pallet caricati of this w k testata documento.
	 *
	 * @return the pallet caricati of this w k testata documento
	 */
	public int getPalletCaricati();

	/**
	 * Sets the pallet caricati of this w k testata documento.
	 *
	 * @param palletCaricati the pallet caricati of this w k testata documento
	 */
	public void setPalletCaricati(int palletCaricati);

	/**
	 * Returns the pallet scaricati of this w k testata documento.
	 *
	 * @return the pallet scaricati of this w k testata documento
	 */
	public int getPalletScaricati();

	/**
	 * Sets the pallet scaricati of this w k testata documento.
	 *
	 * @param palletScaricati the pallet scaricati of this w k testata documento
	 */
	public void setPalletScaricati(int palletScaricati);

	/**
	 * Returns the codice vettore of this w k testata documento.
	 *
	 * @return the codice vettore of this w k testata documento
	 */
	@AutoEscape
	public String getCodiceVettore();

	/**
	 * Sets the codice vettore of this w k testata documento.
	 *
	 * @param codiceVettore the codice vettore of this w k testata documento
	 */
	public void setCodiceVettore(String codiceVettore);

	/**
	 * Returns the destinazione vettore of this w k testata documento.
	 *
	 * @return the destinazione vettore of this w k testata documento
	 */
	@AutoEscape
	public String getDestinazioneVettore();

	/**
	 * Sets the destinazione vettore of this w k testata documento.
	 *
	 * @param destinazioneVettore the destinazione vettore of this w k testata documento
	 */
	public void setDestinazioneVettore(String destinazioneVettore);

	/**
	 * Returns the nota1 of this w k testata documento.
	 *
	 * @return the nota1 of this w k testata documento
	 */
	@AutoEscape
	public String getNota1();

	/**
	 * Sets the nota1 of this w k testata documento.
	 *
	 * @param nota1 the nota1 of this w k testata documento
	 */
	public void setNota1(String nota1);

	/**
	 * Returns the nota2 of this w k testata documento.
	 *
	 * @return the nota2 of this w k testata documento
	 */
	@AutoEscape
	public String getNota2();

	/**
	 * Sets the nota2 of this w k testata documento.
	 *
	 * @param nota2 the nota2 of this w k testata documento
	 */
	public void setNota2(String nota2);

	/**
	 * Returns the rigo descrittivo of this w k testata documento.
	 *
	 * @return the rigo descrittivo of this w k testata documento
	 */
	@AutoEscape
	public String getRigoDescrittivo();

	/**
	 * Sets the rigo descrittivo of this w k testata documento.
	 *
	 * @param rigoDescrittivo the rigo descrittivo of this w k testata documento
	 */
	public void setRigoDescrittivo(String rigoDescrittivo);

	/**
	 * Returns the vettore2 of this w k testata documento.
	 *
	 * @return the vettore2 of this w k testata documento
	 */
	@AutoEscape
	public String getVettore2();

	/**
	 * Sets the vettore2 of this w k testata documento.
	 *
	 * @param vettore2 the vettore2 of this w k testata documento
	 */
	public void setVettore2(String vettore2);

	/**
	 * Returns the cura trasporto of this w k testata documento.
	 *
	 * @return the cura trasporto of this w k testata documento
	 */
	@AutoEscape
	public String getCuraTrasporto();

	/**
	 * Sets the cura trasporto of this w k testata documento.
	 *
	 * @param curaTrasporto the cura trasporto of this w k testata documento
	 */
	public void setCuraTrasporto(String curaTrasporto);

	/**
	 * Returns the aspetto esteriore of this w k testata documento.
	 *
	 * @return the aspetto esteriore of this w k testata documento
	 */
	@AutoEscape
	public String getAspettoEsteriore();

	/**
	 * Sets the aspetto esteriore of this w k testata documento.
	 *
	 * @param aspettoEsteriore the aspetto esteriore of this w k testata documento
	 */
	public void setAspettoEsteriore(String aspettoEsteriore);

	/**
	 * Returns the causale trasporto of this w k testata documento.
	 *
	 * @return the causale trasporto of this w k testata documento
	 */
	@AutoEscape
	public String getCausaleTrasporto();

	/**
	 * Sets the causale trasporto of this w k testata documento.
	 *
	 * @param causaleTrasporto the causale trasporto of this w k testata documento
	 */
	public void setCausaleTrasporto(String causaleTrasporto);

	/**
	 * Returns the porto of this w k testata documento.
	 *
	 * @return the porto of this w k testata documento
	 */
	@AutoEscape
	public String getPorto();

	/**
	 * Sets the porto of this w k testata documento.
	 *
	 * @param porto the porto of this w k testata documento
	 */
	public void setPorto(String porto);

	/**
	 * Returns the origine of this w k testata documento.
	 *
	 * @return the origine of this w k testata documento
	 */
	@AutoEscape
	public String getOrigine();

	/**
	 * Sets the origine of this w k testata documento.
	 *
	 * @param origine the origine of this w k testata documento
	 */
	public void setOrigine(String origine);

	/**
	 * Returns the numero pedane euro of this w k testata documento.
	 *
	 * @return the numero pedane euro of this w k testata documento
	 */
	public int getNumeroPedaneEuro();

	/**
	 * Sets the numero pedane euro of this w k testata documento.
	 *
	 * @param numeroPedaneEuro the numero pedane euro of this w k testata documento
	 */
	public void setNumeroPedaneEuro(int numeroPedaneEuro);

	/**
	 * Returns the numero pedane normali of this w k testata documento.
	 *
	 * @return the numero pedane normali of this w k testata documento
	 */
	public int getNumeroPedaneNormali();

	/**
	 * Sets the numero pedane normali of this w k testata documento.
	 *
	 * @param numeroPedaneNormali the numero pedane normali of this w k testata documento
	 */
	public void setNumeroPedaneNormali(int numeroPedaneNormali);

	/**
	 * Returns the costo trasporto of this w k testata documento.
	 *
	 * @return the costo trasporto of this w k testata documento
	 */
	public double getCostoTrasporto();

	/**
	 * Sets the costo trasporto of this w k testata documento.
	 *
	 * @param costoTrasporto the costo trasporto of this w k testata documento
	 */
	public void setCostoTrasporto(double costoTrasporto);

	/**
	 * Returns the totale pedane ordine of this w k testata documento.
	 *
	 * @return the totale pedane ordine of this w k testata documento
	 */
	public int getTotalePedaneOrdine();

	/**
	 * Sets the totale pedane ordine of this w k testata documento.
	 *
	 * @param totalePedaneOrdine the totale pedane ordine of this w k testata documento
	 */
	public void setTotalePedaneOrdine(int totalePedaneOrdine);

	/**
	 * Returns the targa camion of this w k testata documento.
	 *
	 * @return the targa camion of this w k testata documento
	 */
	@AutoEscape
	public String getTargaCamion();

	/**
	 * Sets the targa camion of this w k testata documento.
	 *
	 * @param targaCamion the targa camion of this w k testata documento
	 */
	public void setTargaCamion(String targaCamion);

	/**
	 * Returns the targa rimorchio of this w k testata documento.
	 *
	 * @return the targa rimorchio of this w k testata documento
	 */
	@AutoEscape
	public String getTargaRimorchio();

	/**
	 * Sets the targa rimorchio of this w k testata documento.
	 *
	 * @param targaRimorchio the targa rimorchio of this w k testata documento
	 */
	public void setTargaRimorchio(String targaRimorchio);

	/**
	 * Returns the id associato of this w k testata documento.
	 *
	 * @return the id associato of this w k testata documento
	 */
	public long getIdAssociato();

	/**
	 * Sets the id associato of this w k testata documento.
	 *
	 * @param idAssociato the id associato of this w k testata documento
	 */
	public void setIdAssociato(long idAssociato);

	/**
	 * Returns the verificato of this w k testata documento.
	 *
	 * @return the verificato of this w k testata documento
	 */
	public boolean getVerificato();

	/**
	 * Returns <code>true</code> if this w k testata documento is verificato.
	 *
	 * @return <code>true</code> if this w k testata documento is verificato; <code>false</code> otherwise
	 */
	public boolean isVerificato();

	/**
	 * Sets whether this w k testata documento is verificato.
	 *
	 * @param verificato the verificato of this w k testata documento
	 */
	public void setVerificato(boolean verificato);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		it.bysoftware.ct.model.WKTestataDocumento wkTestataDocumento);

	@Override
	public int hashCode();

	@Override
	public CacheModel<it.bysoftware.ct.model.WKTestataDocumento> toCacheModel();

	@Override
	public it.bysoftware.ct.model.WKTestataDocumento toEscapedModel();

	@Override
	public it.bysoftware.ct.model.WKTestataDocumento toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}